Repository zaproxy/zaproxy, pull requests merged in 2018-03, with the labels that each got.

#4461 Remove unnecessary resource message
  src/lang/Messages.properties
  src/org/parosproxy/paros/extension/option/OptionsViewPanel.java
  src/org/zaproxy/zap/extension/option/OptionsLocalePanel.java
Labels: Type-Task

#4451 Include input elements with related form attribute
  src/org/zaproxy/zap/spider/parser/SpiderHtmlFormParser.java
  test/org/zaproxy/zap/spider/parser/SpiderHtmlFormParserUnitTest.java
  test/resources/org/zaproxy/zap/spider/parser/htmlform/FormAndInputsWithFormAttributes.html
Labels: Type-Task

#4463 Remove redundant local variables
  src/org/zaproxy/zap/control/AddOnLoaderUtils.java
  src/org/zaproxy/zap/control/ExtensionFactory.java
  src/org/zaproxy/zap/db/sql/SqlTableAlert.java
  src/org/zaproxy/zap/db/sql/SqlTableContext.java
  src/org/zaproxy/zap/db/sql/SqlTableParam.java
  src/org/zaproxy/zap/db/sql/SqlTableScan.java
  src/org/zaproxy/zap/db/sql/SqlTableTag.java
  src/org/zaproxy/zap/extension/ascan/ChallengeCallbackAPI.java
  src/org/zaproxy/zap/extension/help/ZapTocView.java
  src/org/zaproxy/zap/extension/params/ExtensionParams.java
  src/org/zaproxy/zap/extension/users/UsersAPI.java
  src/org/zaproxy/zap/utils/TimeStampUtils.java
  src/org/zaproxy/zap/view/AbstractMultipleOrderedOptionsBaseTableModel.java
Labels: Type-Task

#4402 Add option to show request/response in same tab
  src/lang/Messages.properties
  src/org/parosproxy/paros/extension/option/OptionsViewPanel.java
  src/org/parosproxy/paros/view/MainFrame.java
  src/org/parosproxy/paros/view/WorkbenchPanel.java
  src/resource/icon/layout_tabbed_split.png
Labels: Type-Task

#4471 Update Webswing to 2.5 in Docker images
  build/docker/Dockerfile-live
  build/docker/Dockerfile-stable
  build/docker/Dockerfile-weekly
  build/docker/webswing.config
  build/docker/zap-webswing.sh
Labels: Type-Task

#4443 Use custom label in History Filter dialogue
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/history/HistoryFilterPlusDialog.java
Labels: Type-Task

#4474 Expose getPluginPassiveScanners()
  src/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
Labels: enhancement

#4476 Change standard fields dialogue to document modal
  src/org/zaproxy/zap/view/StandardFieldsDialog.java
Labels: bug, minor

#4477 Enable help in Add/Edit Break Point dialogue
  src/org/zaproxy/zap/extension/brk/impl/http/BreakAddEditDialog.java
Labels: Component-UI, Usability, enhancement

#4473 Assert vulnerabilities files are properly loaded
  test/org/zaproxy/zap/model/ValidateTranslatedVulnerabilitiesFilesUnitTest.java
Labels: Type-Task

#4340 Fix Issue 1161 - Manual Request SessionTracking Button Sync
  src/org/parosproxy/paros/extension/manualrequest/ExtensionManualRequestEditor.java
  src/org/parosproxy/paros/extension/manualrequest/http/impl/HttpPanelSender.java
  src/org/parosproxy/paros/extension/manualrequest/http/impl/ManualHttpRequestEditorDialog.java
  src/org/parosproxy/paros/network/HttpSender.java
Labels: Type-Task

#4449 Reload scripts if they have changed on disk
  src/org/zaproxy/zap/extension/script/ExtensionScript.java
  src/org/zaproxy/zap/extension/script/ScriptWrapper.java
Labels: Type-Task

#4484 Added Django csrf_token
  src/org/zaproxy/zap/extension/anticsrf/AntiCsrfParam.java
  src/xml/config.xml
Labels: enhancement

#4486 Correct case checks in HttpClient classes
  src/org/apache/commons/httpclient/HttpMethodDirector.java
  src/org/apache/commons/httpclient/URI.java
Labels: Type-Task

#4487 Normalise Source instantiations
  src/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  src/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  src/org/zaproxy/zap/httputils/HtmlContextAnalyser.java
Labels: Type-Task

#4440 Added method to unregister event consumer from all publishers
  src/org/zaproxy/zap/eventBus/EventBus.java
  src/org/zaproxy/zap/eventBus/SimpleEventBus.java
  test/org/zaproxy/zap/eventBus/SimpleEventBusUnitTest.java
Labels: Type-Task

#4495 Plugin ID Reservations (HttpsInfo)
  src/doc/scanners.md
Labels: Type-Task, minor

#4498 Added support for launching JVM enabled for remote debugging
  src/zap.sh
Labels: enhancement

#4493 Reload script of changed on disk in getScript()
  src/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: Type-Task

#4438 Allow to select the look and feel
  src/lang/Messages.properties
  src/org/parosproxy/paros/extension/option/OptionsParamView.java
  src/org/parosproxy/paros/extension/option/OptionsViewPanel.java
  src/org/zaproxy/zap/GuiBootstrap.java
Labels: Type-Task

#4501 Use same help page in request editor dialogues
  src/org/parosproxy/paros/extension/history/ExtensionHistory.java
Labels: Type-Task

#4503 Fix NPE with scripts from custom directories
  src/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: Type-Task, waiting-for:zaproxy-team

#4489 Move docker dir to a top level dir
  docker/.xinitrc
  docker/Dockerfile-bare
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
  docker/Dockerfile-zapcli
  docker/docker-compose.yml
  docker/policies/API-Minimal.policy
  docker/policies/Default Policy.policy
  docker/policies/St-High-Th-High.policy
  docker/policies/St-High-Th-Low.policy
  docker/policies/St-High-Th-Med.policy
  docker/policies/St-Ins-Th-High.policy
  docker/policies/St-Ins-Th-Low.policy
  docker/policies/St-Ins-Th-Med.policy
  docker/policies/St-Low-Th-High.policy
  docker/policies/St-Low-Th-Low.policy
  docker/policies/St-Low-Th-Med.policy
  docker/policies/St-Med-Th-High.policy
  docker/policies/St-Med-Th-Low.policy
  docker/requirements.txt
  docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js
  docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
  docker/tox.ini
  docker/webswing.config
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
  docker/zap-webswing.sh
  docker/zap-x.sh
  docker/zap_common.py
Labels: Type-Task

#4502 Add more events and data
  src/org/parosproxy/paros/extension/history/ProxyListenerLog.java
  src/org/parosproxy/paros/extension/history/ProxyListenerLogEventPublisher.java
  src/org/parosproxy/paros/network/HttpMessage.java
  src/org/zaproxy/zap/extension/alert/AlertEventPublisher.java
  src/org/zaproxy/zap/extension/alert/ExtensionAlert.java
  src/org/zaproxy/zap/extension/brk/BreakEventPublisher.java
  src/org/zaproxy/zap/extension/brk/BreakpointMessageHandler2.java
  src/org/zaproxy/zap/extension/httppanel/Message.java
Labels: Type-Task

#4507 Allow to create ScriptEngineWrapper with a factory
  src/org/zaproxy/zap/extension/script/DefaultEngineWrapper.java
  src/org/zaproxy/zap/extension/script/ExtensionScript.java
  src/org/zaproxy/zap/extension/script/JavascriptEngineWrapper.java
  src/org/zaproxy/zap/extension/script/ScriptEngineWrapper.java
Labels: Component-Scripts, Type-Task, waiting-for:zaproxy-team

#4510 Update ID 40033 for MongoDB (NoSQL Injection)
  src/doc/scanners.md
Labels: Type-Task

#4511 Remove AbstractPanel from internal list, always
  src/org/zaproxy/zap/view/TabbedPanel2.java
Labels: bug, minor

#4516 Fixes #4515; AuthenticationScript (Python, Ruby, Groovy) does not work
  src/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
Labels: Type-Task

#4514 Do not change case when ignoring case in equals
  src/org/parosproxy/paros/Constant.java
  src/org/zaproxy/zap/extension/api/DotNetAPIGenerator.java
  src/org/zaproxy/zap/extension/api/GoAPIGenerator.java
  src/org/zaproxy/zap/extension/api/JavaAPIGenerator.java
  src/org/zaproxy/zap/extension/brk/BreakAPI.java
  src/org/zaproxy/zap/utils/HttpUserAgent.java
Labels: Type-Task, waiting-for:zaproxy-team

#4518 Do not allow to add null users
  src/org/zaproxy/zap/extension/users/ContextUserAuthManager.java
Labels: Type-Task

#4523 Allow direct access to add-ons' optional classes
  src/org/zaproxy/zap/control/AddOnClassLoader.java
  src/org/zaproxy/zap/control/AddOnLoader.java
Labels: Type-Task

#4532 Fix NPE when removing scripts with unsaved script
  src/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: bug, minor

#4531 Update list of parameters to ignore
  src/lang/Messages.properties
  src/org/parosproxy/paros/core/scanner/NameValuePair.java
  src/org/parosproxy/paros/core/scanner/ScannerParamFilter.java
Labels: Type-Task

#4538 Local ZapVersions.xml not correctly saved in all locales
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: bug

#4542 Ensure node selected param panel is visible
  src/org/parosproxy/paros/view/AbstractParamContainerPanel.java
Labels: Component-UI, Usability, enhancement

#4541 Expand node of selected context
  src/org/parosproxy/paros/view/SiteMapPanel.java
Labels: Component-UI, Usability, enhancement

#4540 Include cause of failed API format/type conversion
  src/org/zaproxy/zap/extension/api/API.java
Labels: Type-Task

#4544 AlertsViewPanel Yet Another Tweak
  src/org/zaproxy/zap/extension/alert/AlertAddDialog.java
  src/org/zaproxy/zap/extension/alert/AlertViewPanel.java
Labels: Type-Task
