Repository zaproxy/zaproxy, pull requests merged in 2018-07, with the labels that each got.

#4802 Allow to enable dev mode through the command line
  src/org/parosproxy/paros/CommandLine.java
  src/org/parosproxy/paros/Constant.java
  src/org/parosproxy/paros/model/SiteMap.java
  src/org/zaproxy/zap/GuiBootstrap.java
  src/org/zaproxy/zap/extension/log4j/ExtensionLog4j.java
Labels: Type-Task

#4810 Exit on exception during GUI start
  src/org/zaproxy/zap/GuiBootstrap.java
Labels: Usability, enhancement

#4808 Fix XML configuration's indentation with Java 9+
  src/org/zaproxy/zap/utils/ZapXmlConfiguration.java
  test/org/zaproxy/zap/utils/ZapXmlConfigurationUnitTest.java
Labels: Type-Task

#4806 Fix typo in SimpleEventBus
  src/org/zaproxy/zap/eventBus/SimpleEventBus.java
Labels: Type-Task

#4817 Skip dependent extensions of failed uninstallation
  src/org/zaproxy/zap/control/AddOnLoader.java
Labels: bug

#4818 Correct API response on failed installations
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Component-API, bug

#4820 Fix NPE after error loading a session
  src/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
Labels: bug, weekly

#4807 Add all dangling event consumers
  src/org/zaproxy/zap/eventBus/SimpleEventBus.java
  test/org/zaproxy/zap/eventBus/SimpleEventBusUnitTest.java
Labels: bug

#4821 Bundle files for report generation
  build/build.xml
  src/org/parosproxy/paros/extension/report/ReportGenerator.java
  src/org/parosproxy/paros/extension/report/ReportLastScan.java
  src/org/zaproxy/zap/extension/api/CoreAPI.java
  src/org/zaproxy/zap/extension/compare/ExtensionCompare.java
Labels: Type-Task

#4819 Added childNodes view
  src/lang/Messages.properties
  src/org/parosproxy/paros/extension/report/ReportLastScan.java
  src/org/parosproxy/paros/model/Session.java
  src/org/parosproxy/paros/model/SiteMap.java
  src/org/zaproxy/zap/extension/alert/ExtensionAlert.java
  src/org/zaproxy/zap/extension/api/CoreAPI.java
  src/org/zaproxy/zap/extension/ascan/ExtensionActiveScan.java
  src/org/zaproxy/zap/extension/params/ExtensionParams.java
  src/org/zaproxy/zap/model/Context.java
  src/org/zaproxy/zap/model/SessionStructure.java
  src/org/zaproxy/zap/model/StructuralNode.java
  src/org/zaproxy/zap/model/StructuralSiteNode.java
  src/org/zaproxy/zap/model/StructuralTableNode.java
  src/org/zaproxy/zap/view/NodeSelectDialog.java
  src/org/zaproxy/zap/view/ScanPanel.java
Labels: Component-API, enhancement

#4825 Option to ignore warnings
  docker/zap-baseline.py
Labels: Type-Task

#4827 Allow consumers to remove themselves during events
  src/org/zaproxy/zap/eventBus/SimpleEventBus.java
  test/org/zaproxy/zap/eventBus/SimpleEventBusUnitTest.java
Labels: Usability, bug

#4829 Add description to search API endpoints
  src/lang/Messages.properties
Labels: Component-API, Component-Docs, Type-Task

#3919 Add Java 9 to Travis CI builds
  .classpath
  .travis.yml
  src/org/parosproxy/paros/core/scanner/PluginFactory.java
  test/ch/csnc/extension/httpclient/AliasKeyManagerUnitTest.java
  test/org/parosproxy/paros/CommandLineUnitTest.java
  test/org/parosproxy/paros/core/scanner/PluginFactoryUnitTest.java
  test/org/zaproxy/zap/users/UsersTableModelUnitTest.java
  test/org/zaproxy/zap/view/widgets/UsersListModelUnitTest.java
  testlib/powermock-mockito-release-full-1.5.6-full.jar
Labels: Type-Task

#4831 Don't require an options button in scan panels
  src/org/zaproxy/zap/view/ScanPanel2.java
Labels: Type-Task

#4830 Tidy up tests
  test/org/parosproxy/paros/core/scanner/VariantJSONQueryUnitTest.java
  test/org/parosproxy/paros/network/HttpBodyUnitTest.java
  test/org/zaproxy/zap/VersionUnitTest.java
  test/org/zaproxy/zap/authentication/UsernamePasswordAuthenticationCredentialsUnitTest.java
  test/org/zaproxy/zap/extension/alert/ExtensionAlertUnitTest.java
  test/org/zaproxy/zap/extension/api/APIUnitTest.java
  test/org/zaproxy/zap/extension/api/ApiResponseConversionUtilsUnitTest.java
  test/org/zaproxy/zap/model/SessionUtilsUnitTest.java
  test/org/zaproxy/zap/spider/filters/DefaultFetchFilterUnitTest.java
  test/org/zaproxy/zap/spider/parser/SpiderHtmlFormParserUnitTest.java
  test/org/zaproxy/zap/users/UserUnitTest.java
  test/org/zaproxy/zap/users/UsersTableModelUnitTest.java
  test/org/zaproxy/zap/view/widgets/UsersListModelUnitTest.java
Labels: Type-Task

#4835 Improve 'port in use' error message
  src/lang/Messages.properties
  src/org/parosproxy/paros/core/proxy/ProxyServer.java
Labels: Usability, enhancement

#4836 Add option to prevent windows from grabbing focus from other apps
  src/org/parosproxy/paros/view/View.java
  src/org/zaproxy/zap/extension/ascan/AttackModeScanner.java
  src/org/zaproxy/zap/extension/brk/BreakPanel.java
Labels: Component-UI, Usability, enhancement

#4838 Bundle drivers.xml file
  build/build.xml
  src/ch/csnc/extension/util/DriverConfiguration.java
  src/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java
Labels: Type-Task

#4837 Add description to keyboard API endpoints
  src/lang/Messages.properties
Labels: Component-API, Component-Docs, Type-Task

#4845 Remove unnecessary statement in test class
  test/ch/csnc/extension/httpclient/AliasKeyManagerUnitTest.java
Labels: Type-Task

#4844 Remove unused build related files
  build/build-debian.xml
  build/lib/crowdin-0.0.1-SNAPSHOT.jar
Labels: Type-Task

#4833 Added alert api endpoints
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/alert/AlertAPI.java
  src/org/zaproxy/zap/extension/alert/ExtensionAlert.java
  src/org/zaproxy/zap/extension/api/CoreAPI.java
Labels: Component-API, enhancement

#4848 Don't require lang dir on the classpath
  .classpath
  .project
  build/build.xml
  src/org/zaproxy/zap/utils/I18N.java
Labels: Type-Task

#4854 Remove duplicated logger
  src/org/zaproxy/zap/extension/search/ExtensionSearch.java
Labels: Type-Task

#4857 Be more defensive when installing add-ons
  src/org/zaproxy/zap/control/AddOnInstaller.java
Labels: Type-Task

#4856 Suppress Nashorn removal warnings
  src/org/zaproxy/zap/ZAP.java
Labels: Type-Task

#4855 Tweak log message in ExtensionLoader
  src/org/parosproxy/paros/extension/ExtensionLoader.java
Labels: Type-Task

#4853 Address compilation warnings with Java 10
  .travis.yml
  src/org/parosproxy/paros/extension/ViewDelegate.java
  src/org/parosproxy/paros/extension/edit/ExtensionEdit.java
  src/org/parosproxy/paros/extension/history/LogPanel.java
  src/org/parosproxy/paros/extension/manualrequest/http/impl/ManualHttpRequestEditorDialog.java
  src/org/parosproxy/paros/view/MainMenuBar.java
  src/org/parosproxy/paros/view/OutputPanel.java
  src/org/parosproxy/paros/view/SiteMapPanel.java
  src/org/parosproxy/paros/view/View.java
  src/org/zaproxy/zap/extension/alert/AlertPanel.java
  src/org/zaproxy/zap/extension/ascan/ActiveScanPanel.java
  src/org/zaproxy/zap/extension/ascan/ExtensionActiveScan.java
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  src/org/zaproxy/zap/extension/brk/BreakPanel.java
  src/org/zaproxy/zap/extension/brk/BreakpointsPanel.java
  src/org/zaproxy/zap/extension/brk/ExtensionBreak.java
  src/org/zaproxy/zap/extension/encoder2/ExtensionEncoder2.java
  src/org/zaproxy/zap/extension/httpsessions/HttpSessionsPanel.java
  src/org/zaproxy/zap/extension/params/ParamsPanel.java
  src/org/zaproxy/zap/extension/search/ExtensionSearch.java
  src/org/zaproxy/zap/extension/spider/ExtensionSpider.java
  src/org/zaproxy/zap/extension/spider/SpiderPanel.java
Labels: Type-Task

#4860 Bundle DB script and ZAP/log configurations
  build/build.xml
  src/org/parosproxy/paros/Constant.java
  src/org/parosproxy/paros/model/Model.java
  test/org/zaproxy/zap/WithConfigsTest.java
Labels: Type-Task

#4861 Add client side passive and active scripts IDs
  docs/scanners.md
Labels: Type-Task

#4859 Include installation directory in support info
  src/lang/Messages.properties
  src/org/zaproxy/zap/utils/ZapSupportUtils.java
Labels: Type-Task

#4862 Add Java 11 to Travis CI builds
  .travis.yml
Labels: Type-Task

#4869 Delay initialisation of keyboard mappings
  src/org/zaproxy/zap/extension/keyboard/ExtensionKeyboard.java
Labels: Component-UI, Usability, bug

#4867 Add CSP headers
  src/org/parosproxy/paros/network/HttpResponseHeader.java
Labels: Type-Task

#4868 Reduce code duplication in ExtensionKeyboard
  src/org/zaproxy/zap/extension/keyboard/ExtensionKeyboard.java
  src/org/zaproxy/zap/extension/keyboard/KeyboardMapping.java
  src/org/zaproxy/zap/view/ZapMenuItem.java
Labels: Type-Task

#4872 Added param to alert data
  src/org/zaproxy/zap/extension/alert/AlertAPI.java
Labels: minor

#4873 Test initialisation of home directory
  src/org/parosproxy/paros/Constant.java
  test/org/parosproxy/paros/ConstantUnitTest.java
Labels: Type-Task

#4874 Ignore (and log) duplicated default accelerators
  src/org/zaproxy/zap/extension/keyboard/ExtensionKeyboard.java
  src/org/zaproxy/zap/extension/keyboard/KeyboardMapping.java
Labels: Type-Task

#4889 Log duplicated default accelerators just once
  src/org/zaproxy/zap/extension/keyboard/ExtensionKeyboard.java
Labels: bug, weekly

#4887 Remove unused build targets and bundled file
  build/build.xml
Labels: Type-Task
