Repository zaproxy/zaproxy, pull requests merged in 2018-04, with the labels that each got.

#4545 Validate parameters for ContextDataFactory
  src/org/parosproxy/paros/model/Model.java
  src/org/zaproxy/zap/model/ContextDataFactory.java
Labels: Type-Task

#4552 Log target in Docker API scans
  docker/zap-api-scan.py
Labels: Docker, Type-Task

#4553 Tweak API response cache directives
  src/org/zaproxy/zap/extension/api/API.java
Labels: Component-API, Type-Task

#4556 Use FileNameExtensionFilter where possible
  src/ch/csnc/extension/ui/DriversView.java
  src/org/parosproxy/paros/extension/history/PopupMenuExportMessage.java
  src/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java
  src/org/zaproxy/zap/extension/ascan/PolicyManagerDialog.java
  src/org/zaproxy/zap/extension/compare/ExtensionCompare.java
  src/org/zaproxy/zap/extension/dynssl/DynamicSSLPanel.java
  src/org/zaproxy/zap/extension/lang/OptionsLangPanel.java
  src/org/zaproxy/zap/utils/FilenameExtensionFilter.java
Labels: Type-Task

#4557 Tweak JVM panel to resize properly
  src/org/parosproxy/paros/extension/option/OptionsJvmPanel.java
Labels: Component-UI, Usability, enhancement

#4558 Allow to specify ResourceBundle in API generators
  src/org/zaproxy/zap/extension/api/AbstractAPIGenerator.java
  src/org/zaproxy/zap/extension/api/DotNetAPIGenerator.java
  src/org/zaproxy/zap/extension/api/GoAPIGenerator.java
  src/org/zaproxy/zap/extension/api/JavaAPIGenerator.java
  src/org/zaproxy/zap/extension/api/NodeJSAPIGenerator.java
  src/org/zaproxy/zap/extension/api/PhpAPIGenerator.java
  src/org/zaproxy/zap/extension/api/PythonAPIGenerator.java
  src/org/zaproxy/zap/extension/api/WikiAPIGenerator.java
Labels: Type-Task

#4562 Persist copy of proxied message
  src/org/parosproxy/paros/extension/history/ProxyListenerLog.java
Labels: bug, minor

#4559 Do not throw MissingResourceException in I18N
  src/org/parosproxy/paros/view/View.java
  src/org/zaproxy/zap/extension/api/WebUI.java
  src/org/zaproxy/zap/utils/I18N.java
Labels: Type-Task

#4563 Tweak TabbedPanel2
  src/org/zaproxy/zap/view/TabbedPanel2.java
Labels: Type-Task

#4554 Do not try to scan without URLs in Docker API scan
  docker/zap-api-scan.py
Labels: Docker, enhancement

#4565 Fix main layouts
  src/org/parosproxy/paros/view/WorkbenchPanel.java
  src/org/zaproxy/zap/view/TabbedPanel2.java
Labels: Component-UI, bug, weekly

#4568 Correct persistence of proxied messages
  src/org/parosproxy/paros/extension/history/ProxyListenerLog.java
  src/org/parosproxy/paros/network/HttpMessage.java
  test/org/parosproxy/paros/network/HttpMessageUnitTest.java
Labels: bug, weekly

#4569 Move ISO8601 Timestamp format out of properties
  src/lang/Messages.properties
  src/org/parosproxy/paros/extension/option/OptionsParamView.java
  src/org/parosproxy/paros/extension/option/OptionsViewPanel.java
  src/org/zaproxy/zap/utils/TimeStampUtils.java
Labels: minor

#4572 Display Memory Info on JVM Options Panel
  src/lang/Messages.properties
  src/org/parosproxy/paros/extension/option/OptionsJvmPanel.java
  src/org/zaproxy/zap/view/renderer/SizeBytesStringValue.java
Labels: Type-Task

#4575 Stop spider scans when mode changed to Safe
  src/org/zaproxy/zap/extension/spider/ExtensionSpider.java
Labels: bug

#4441 Validate i18n time stamp patterns
  test/org/zaproxy/zap/utils/TimeStampLocaleUnitTest.java
Labels: Type-Task

#4573 Add BreakAPI through the ExtensionHook
  src/org/zaproxy/zap/extension/brk/ExtensionBreak.java
Labels: Type-Task

#4576 Skip Token Generator responses for HTTP Sessions
  src/org/zaproxy/zap/extension/httpsessions/ExtensionHttpSessions.java
Labels: bug

#4581 Skip Access Control responses for HTTP Sessions
  src/org/zaproxy/zap/extension/httpsessions/ExtensionHttpSessions.java
Labels: bug

#4599 Keep backup of malformed config.xml file
  src/org/parosproxy/paros/Constant.java
Labels: Usability, enhancement

#4587 Add description to ascan scanners endpoints
  src/lang/Messages.properties
Labels: Component-API, Component-Docs, Type-Task

#4595 Add description to authentication API endpoints
  src/lang/Messages.properties
Labels: Component-API, Component-Docs, Type-Task

#4594 Add description to users API endpoints
  src/lang/Messages.properties
Labels: Component-API, Component-Docs, Type-Task

#4593 Do not include zero Content-Length in GET requests
  src/org/zaproxy/zap/ZapGetMethod.java
Labels: bug, weekly

#4592 Keep panel of selected context selected
  src/org/parosproxy/paros/view/AbstractParamContainerPanel.java
  src/org/parosproxy/paros/view/AbstractParamDialog.java
  src/org/parosproxy/paros/view/SiteMapPanel.java
Labels: Component-UI, Usability, enhancement

#4588 Tweak label in Exclude from Spider panel
  src/lang/Messages.properties
Labels: Type-Task

#4586 Persist proxied message synchronously
  src/org/parosproxy/paros/extension/history/ProxyListenerLog.java
Labels: bug, weekly

#4583 Passive Scan Tag Interpolation
  src/org/zaproxy/zap/extension/pscan/scanner/RegexAutoTagScanner.java
Labels: Type-Task

#4608 Added support for spider and ascan events
  src/org/parosproxy/paros/core/scanner/Scanner.java
  src/org/zaproxy/zap/extension/ascan/ActiveScan.java
  src/org/zaproxy/zap/extension/ascan/ActiveScanEventPublisher.java
  src/org/zaproxy/zap/extension/spider/SpiderEventPublisher.java
  src/org/zaproxy/zap/extension/spider/SpiderScan.java
  src/org/zaproxy/zap/model/ScanEventPublisher.java
Labels: Type-Task

#4614 Validate login URL not empty in form-based auth
  src/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodType.java
Labels: Component-UI, bug, minor

#4624 Add JSON-based authentication method
  .classpath
  LEGALNOTICE.md
  lib/commons-lang3-3.7.jar
  lib/commons-text-1.3.jar
  src/lang/Messages.properties
  src/org/parosproxy/paros/network/HttpHeader.java
  src/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodType.java
  src/org/zaproxy/zap/authentication/JsonBasedAuthenticationMethodType.java
  src/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  src/org/zaproxy/zap/extension/authentication/ExtensionAuthentication.java
Labels: Type-Task

#4625 Do not allow remove HTTP Session if none selected
  src/org/zaproxy/zap/extension/httpsessions/PopupMenuRemoveSession.java
Labels: Component-UI, bug, minor

#4627 Add proxy related listeners to alternative proxies
  src/org/parosproxy/paros/extension/ExtensionLoader.java
  src/org/zaproxy/zap/extension/proxies/ExtensionProxies.java
Labels: bug

#4629 Added approval process
  CONTRIBUTING.md
Labels: Type-Task
