Repository zaproxy/zaproxy, pull requests merged in 2018-06, with the labels that each got.

#4714 Inform if passive scanner is still running
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
Labels: Component-UI, enhancement

#4712 Add Passive Scan Footer Icon/Status
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  src/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  src/resource/icon/16/pscan.png
Labels: Component-UI, enhancement

#4713 Issue 2000 - Title Caps Minor Tweak
  src/lang/Messages.properties
Labels: minor

#4719 Reduce number of progress events
  src/org/zaproxy/zap/extension/ascan/ActiveScan.java
  src/org/zaproxy/zap/extension/spider/SpiderScan.java
Labels: Type-Task

#4725 Allow add-ons to declare a resource bundle
  src/org/zaproxy/zap/control/AddOn.java
  src/org/zaproxy/zap/control/AddOnInstaller.java
  src/org/zaproxy/zap/control/AddOnLoader.java
  src/org/zaproxy/zap/control/ExtensionFactory.java
  src/org/zaproxy/zap/control/ZapAddOnXmlFile.java
Labels: Type-Task

#4724 Log missing resource keys just once
  src/org/zaproxy/zap/utils/I18N.java
Labels: Type-Task

#4723 Document messages methods in Extension
  src/org/parosproxy/paros/extension/Extension.java
Labels: Type-Task

#4722 Fix typos in JavaDoc of LocaleUtils
  src/org/zaproxy/zap/utils/LocaleUtils.java
Labels: Type-Task

#4727 Allow add-ons to declare a helpset
  src/org/zaproxy/zap/control/AddOn.java
  src/org/zaproxy/zap/control/AddOnLoader.java
  src/org/zaproxy/zap/control/ZapAddOnXmlFile.java
  src/org/zaproxy/zap/extension/help/ExtensionHelp.java
Labels: Type-Task

#4726 Added contexts setContextRegexs API endpoint
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/api/ContextAPI.java
  src/org/zaproxy/zap/utils/JsonUtil.java
Labels: Component-API, enhancement

#4730 Params Tab - Add/Remove Param Name as Anti-CSRF Token for Any Param
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/params/PopupMenuAddAntiCSRF.java
  src/org/zaproxy/zap/extension/params/PopupMenuRemoveAntiCSRF.java
Labels: Type-Task

#4737 Update JavaDoc of Extension.getMessages()
  src/org/parosproxy/paros/extension/Extension.java
Labels: Type-Task

#4735 Don't add null node to spider target
  src/org/zaproxy/zap/extension/spider/SpiderAPI.java
  src/org/zaproxy/zap/model/Target.java
Labels: Type-Task

#4744 Fix some typos in docs/scanners.md
  docs/scanners.md
Labels: Type-Task

#4746 Don't enable client cert if none set
  src/org/parosproxy/paros/network/SSLConnector.java
Labels: Type-Task

#4742 Don't save add-ons' runnable state if not changed
  src/org/zaproxy/zap/control/AddOnLoader.java
Labels: bug, minor

#4743 Dynamically add/remove extensions' help
  src/org/zaproxy/zap/control/AddOnInstaller.java
  src/org/zaproxy/zap/control/ExtensionFactory.java
  src/org/zaproxy/zap/extension/help/ExtensionHelp.java
Labels: Component-UI, Usability, enhancement

#4754 Remove HttpUserAgent class
  src/org/zaproxy/zap/utils/HttpUserAgent.java
  src/xml/chrome-user-agents.txt
  src/xml/firefox-user-agents.txt
  src/xml/internet-explorer-user-agents.txt
  src/xml/safari-user-agents.txt
Labels: Type-Task

#4755 Stop relying on ClassLoaderUtil
  build/build.xml
  src/org/zaproxy/zap/ZAP.java
  src/org/zaproxy/zap/utils/ClassLoaderUtil.java
  test/org/zaproxy/zap/WithConfigsTest.java
Labels: Type-Task

#4756 Correct install dir detection from ZAP JAR
  src/org/parosproxy/paros/Constant.java
Labels: bug

#4761 Include more details for script listener errors
  src/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: Type-Task

#4762 Added pscan stats and API call for getting current rule
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  src/org/zaproxy/zap/extension/pscan/PassiveScanAPI.java
  src/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
Labels: Component-API, enhancement

#4764 Deprecate unused active scan callback classes
  src/org/zaproxy/zap/extension/ascan/ChallengeCallbackAPI.java
  src/org/zaproxy/zap/extension/ascan/ChallengeCallbackPlugin.java
  src/org/zaproxy/zap/extension/callback/CallbackImplementor.java
Labels: Type-Task

#4763 Fix ContextGeneralPanel.setName Null Pointer Exception
  src/org/zaproxy/zap/view/ContextGeneralPanel.java
Labels: Component-UI, bug, minor

#4766 Add tests for declared add-on resources
  test/org/zaproxy/zap/control/AddOnUnitTest.java
Labels: Type-Task

#4773 Bundle Messages.properties and vulnerabilities.xml
  build/build.xml
  src/org/zaproxy/zap/model/Vulnerabilities.java
  src/org/zaproxy/zap/model/VulnerabilitiesLoader.java
  src/org/zaproxy/zap/utils/I18N.java
  src/org/zaproxy/zap/utils/LocaleUtils.java
  src/org/zaproxy/zap/utils/ZapXmlConfiguration.java
Labels: Type-Task

#4772 Correct generated certificates' validity period
  src/org/parosproxy/paros/security/SslCertificateServiceImpl.java
  src/org/zaproxy/zap/extension/dynssl/SslCertificateUtils.java
Labels: bug

#4767 Be more lenient when parsing techs through the API
  src/org/zaproxy/zap/extension/api/ContextAPI.java
Labels: Component-API, Usability, enhancement

#4768 Restore the accessible name in Sites' nodes
  src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java
Labels: Type-Task

#4775 Tweak Eclipse classpath to include Messages files
  .classpath
  .project
Labels: Type-Task

#4782 Remove BrowserLauncher library
  .classpath
  LEGALNOTICE.md
  lib/BrowserLauncher2-1_3.jar
  src/org/parosproxy/paros/extension/history/PopupMenuEmbeddedBrowser.java
  src/org/zaproxy/zap/utils/DesktopUtils.java
Labels: Type-Task

#4784 Adjust log msg/levels related to plugin dirs
  src/org/zaproxy/zap/control/AddOnCollection.java
  src/org/zaproxy/zap/control/AddOnLoader.java
Labels: Type-Task

#4790 Output Panel Auth Failure Include URL
  src/lang/Messages.properties
  src/org/zaproxy/zap/authentication/AuthenticationHelper.java
Labels: minor

#4791 Properly re-parent panels in TabbedPanel2
  src/org/zaproxy/zap/view/TabbedPanel2.java
Labels: Type-Task

#4794 Remove HttpComponents libraries
  .classpath
  LEGALNOTICE.md
  lib/httpclient-4.5.jar
  lib/httpcore-4.4.1.jar
Labels: Type-Task

#4800 Bundle license file
  build/build.xml
  src/org/zaproxy/zap/view/LicenseFrame.java
Labels: Type-Task
