Repository zaproxy/zaproxy, pull requests merged in 2018-09, with the labels that each got.

#4970 Don't parse (plain) API parameters as JSON
  src/org/zaproxy/zap/extension/api/API.java
  src/org/zaproxy/zap/utils/JsonUtil.java
  test/org/zaproxy/zap/utils/JsonUtilUnitTest.java
Labels: Component-API, bug

#4971 Made active scan progress consistent with spider, show progress of 100 if scan is stopped
  src/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java
Labels: Component-API, Usability, bug

#4973 Correct Docker scripts' -u argument
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
  docker/zap_common.py
Labels: Type-Task

#4978 Update Webswing to 2.5.5 in Docker images
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task

#4982 Shutdown xvfb
  docker/zap-x.sh
Labels: Type-Task

#4983 Set user when following redirections
  src/org/parosproxy/paros/network/HttpSender.java
Labels: Type-Task

#4987 Don't allow Event with null parameters
  src/org/zaproxy/zap/eventBus/Event.java
Labels: Type-Task

#4990 Added a code of conduct
  CODE_OF_CONDUCT.md
Labels: Type-Task

#4991 Remove redundant add-on validations
  src/org/zaproxy/zap/control/AddOn.java
  src/org/zaproxy/zap/control/AddOnCollection.java
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Type-Task

#4992 Add tests for SpiderRobotstxtParser
  src/org/zaproxy/zap/spider/parser/SpiderRobotstxtParser.java
  test/org/zaproxy/zap/spider/parser/SpiderRobotstxtParserUnitTest.java
Labels: Type-Task

#4993 Change API view optionTokensNames to return a list
  src/org/zaproxy/zap/extension/anticsrf/AntiCsrfAPI.java
  src/org/zaproxy/zap/extension/anticsrf/AntiCsrfParam.java
Labels: Component-API, bug

#4994 Apply JSON workaround to JSON response only
  src/org/zaproxy/zap/extension/api/ApiResponseElement.java
Labels: bug, weekly

#4995 Correct redirections for GET requests
  src/org/parosproxy/paros/network/HttpSender.java
Labels: bug, weekly

#4996 Prevent duplicated API elements
  src/org/zaproxy/zap/extension/api/ApiImplementor.java
Labels: Type-Task

#4997 Allow to manage default session tokens (API)
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/httpsessions/HttpSessionsAPI.java
  src/org/zaproxy/zap/extension/httpsessions/HttpSessionsParam.java
Labels: Component-API, enhancement

#4999 Test add-on validations
  src/org/zaproxy/zap/control/AddOn.java
  test/org/zaproxy/zap/control/AddOnUnitTest.java
Labels: Type-Task

#5000 Test AddOnClassnames
  src/org/zaproxy/zap/control/AddOnClassnames.java
  test/org/zaproxy/zap/control/AddOnClassnamesUnitTest.java
Labels: Type-Task

#5005 Correct SSE Content-Type checks
  src/org/parosproxy/paros/network/HttpHeader.java
  src/org/parosproxy/paros/network/HttpMessage.java
  src/org/zaproxy/zap/ZapGetMethod.java
  test/org/parosproxy/paros/network/HttpMessageUnitTest.java
Labels: Type-Task

#5006 Add some JavaDoc to AttackStrength/AlertThreshold
  src/org/parosproxy/paros/core/scanner/Plugin.java
Labels: Type-Task

#4965 Upgrade snap to stable
  snap/README.md
  snap/build-snap.sh
  snap/snapcraft.yaml
Labels: Type-Task

#5010 Show Version in Marketplace Installed Addons Tab
  src/org/zaproxy/zap/extension/autoupdate/InstalledAddOnsTableModel.java
  src/org/zaproxy/zap/extension/autoupdate/ManageAddOnsDialog.java
Labels: Component-UI, Usability, enhancement

#5011 Do not disable break buttons if msgs still caught
  src/org/zaproxy/zap/extension/brk/BreakPanel.java
  src/org/zaproxy/zap/extension/brk/BreakPanelToolbarFactory.java
Labels: Type-Task

#5012 Correct break events with multiple messages
  src/org/zaproxy/zap/extension/brk/BreakEventPublisher.java
  src/org/zaproxy/zap/extension/brk/BreakpointMessageHandler2.java
Labels: bug, weekly

#5013 Reset caret after setting text to ZapLabel
  src/org/zaproxy/zap/utils/ZapLabel.java
Labels: Type-Task

#5015 Plugin ID reservation - Reserve 10070 for new 'Use of SAML' passive scanner
  docs/scanners.md
Labels: Type-Task
