Repository zaproxy/zaproxy, pull requests merged in 2018-11, with the labels that each got.

#5097 Catch credentials exception when authenticating
  src/org/zaproxy/zap/users/User.java
Labels: Type-Task

#5098 Use varargs on registrations in EventBus
  src/org/parosproxy/paros/extension/history/ProxyListenerLogEventPublisher.java
  src/org/parosproxy/paros/model/HistoryReferenceEventPublisher.java
  src/org/parosproxy/paros/model/SiteMapEventPublisher.java
  src/org/zaproxy/zap/eventBus/EventBus.java
  src/org/zaproxy/zap/eventBus/SimpleEventBus.java
  src/org/zaproxy/zap/extension/alert/AlertEventPublisher.java
  src/org/zaproxy/zap/extension/ascan/ActiveScanEventPublisher.java
  src/org/zaproxy/zap/extension/brk/BreakEventPublisher.java
  src/org/zaproxy/zap/extension/spider/SpiderEventPublisher.java
  src/org/zaproxy/zap/model/ScanEventPublisher.java
Labels: Type-Task

#5089 Include Alert API when generating API clients
  src/org/zaproxy/zap/extension/api/ApiGeneratorUtils.java
Labels: Type-Task

#5105 Register HUD tutorial examples
  docs/scanners.md
Labels: Type-Task

#5109 Prefer latest built add-on
  src/org/zaproxy/zap/control/AddOn.java
  test/org/zaproxy/zap/control/AddOnUnitTest.java
Labels: Type-Task

#5110 Tweak JVM related messages in start script
  src/zap.sh
Labels: Type-Task

#5112 Keep all entries when decoding a user
  src/org/zaproxy/zap/users/User.java
Labels: bug, minor

#5116 Passive scan max alerts option
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/pscan/PassiveScanParam.java
  src/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  src/org/zaproxy/zap/extension/pscan/PassiveScannerList.java
  src/org/zaproxy/zap/extension/pscan/PassiveScannerOptionsPanel.java
Labels: enhancement

#5120 Add Accept header
  src/org/parosproxy/paros/network/HttpRequestHeader.java
Labels: Type-Task

#5117 Log alert count when host process completes
  src/org/parosproxy/paros/core/scanner/HostProcess.java
Labels: Type-Task

#5128 Reinstate the one year warn
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: bug, minor

#5127 Do not remove users when changing auth method
  src/lang/Messages.properties
  src/org/zaproxy/zap/authentication/AuthenticationMethodType.java
  src/org/zaproxy/zap/authentication/HttpAuthenticationMethodType.java
  src/org/zaproxy/zap/authentication/ManualAuthenticationMethodType.java
  src/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  src/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
  src/org/zaproxy/zap/extension/authentication/AuthenticationAPI.java
  src/org/zaproxy/zap/extension/authentication/ContextAuthenticationPanel.java
Labels: Type-Task
