Repository zaproxy/zaproxy, pull requests merged in 2018-10, with the labels that each got.

#5023 Let fields in StandardFieldsDialog get all space
  src/org/zaproxy/zap/view/StandardFieldsDialog.java
Labels: Component-UI, Usability, enhancement

#5022 Reduce code duplication in ProxyListenerScript
  src/org/zaproxy/zap/extension/script/ProxyListenerScript.java
Labels: Type-Task

#5029 Discard edits of new field in StandardFieldsDialog
  src/org/zaproxy/zap/view/StandardFieldsDialog.java
Labels: Component-UI, Usability, enhancement

#5033 Do not add auth context menus in daemon mode
  src/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
Labels: bug

#5035 Lazily initialise ExtensionHook[Menu|View]
  src/org/parosproxy/paros/extension/ExtensionHook.java
  src/org/parosproxy/paros/extension/ExtensionHookMenu.java
  src/org/parosproxy/paros/extension/ExtensionHookView.java
  src/org/parosproxy/paros/extension/ExtensionLoader.java
Labels: Type-Task

#5034 Add button to install all add-ons from marketplace
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/autoupdate/ManageAddOnsDialog.java
  src/org/zaproxy/zap/extension/autoupdate/UninstalledAddOnsTableModel.java
Labels: Type-Task

#5039 Improve callback logging
  src/org/zaproxy/zap/extension/api/API.java
Labels: Type-Task

#5042 Use managed ExtensionHook when removing Extension
  src/org/parosproxy/paros/extension/Extension.java
  src/org/parosproxy/paros/extension/ExtensionAdaptor.java
  src/org/parosproxy/paros/extension/ExtensionLoader.java
  src/org/zaproxy/zap/control/AddOnInstaller.java
Labels: Type-Task

#5046 Update docker images to use more recent ubuntu
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Docker, Type-Task

#5048 Allow to set main pop up menu to fields
  src/org/zaproxy/zap/view/StandardFieldsDialog.java
Labels: Type-Task

#5053 Update API generator
  build/build.xml
  src/org/zaproxy/zap/extension/api/AbstractAPIGenerator.java
Labels: Type-Task

#5052 Include stack trace on unexpected field class
  src/org/zaproxy/zap/view/StandardFieldsDialog.java
Labels: Type-Task

#5056 Validate status declared in add-on manifest
  src/org/zaproxy/zap/control/BaseZapAddOnXmlData.java
  test/org/zaproxy/zap/control/ZapAddOnXmlFileUnitTest.java
Labels: Type-Task

#5054 Deprecate HttpSender#getClient()
  src/org/parosproxy/paros/network/HttpSender.java
Labels: Type-Task

#5066 Correct request rewrite when following redirection
  src/org/parosproxy/paros/network/HttpSender.java
Labels: bug

#5068 Fix typo in sql script adding the tag column
  src/db/hsqldb.properties
Labels: bug

#5067 Return HistoryIds from HistoryTable starting at a specific historyId
  src/db/hsqldb.properties
  src/org/parosproxy/paros/db/TableHistory.java
  src/org/parosproxy/paros/db/paros/ParosTableHistory.java
  src/org/zaproxy/zap/db/sql/SqlTableHistory.java
Labels: Type-Task

#5079 Fix JavaDoc reference in HttpSender
  src/org/parosproxy/paros/network/HttpSender.java
Labels: Type-Task

#5078 Set a name to shutdown threads
  src/org/parosproxy/paros/control/Control.java
  src/org/zaproxy/zap/extension/api/CoreAPI.java
Labels: Type-Task

#5092 Fix misaligned custom vectors indices
  src/org/parosproxy/paros/core/scanner/AbstractPlugin.java
Labels: Type-Task

#5088 Node api generation
  src/org/zaproxy/zap/extension/api/NodeJSAPIGenerator.java
Labels: Type-Task

#5096 Removed superfluous old node api files
  nodejs/api/zapv2/.jshintrc
  nodejs/api/zapv2/LICENSE
  nodejs/api/zapv2/README.md
  nodejs/api/zapv2/acsrf.js
  nodejs/api/zapv2/ajaxSpider.js
  nodejs/api/zapv2/ascan.js
  nodejs/api/zapv2/authentication.js
  nodejs/api/zapv2/authorization.js
  nodejs/api/zapv2/autoupdate.js
  nodejs/api/zapv2/brk.js
  nodejs/api/zapv2/context.js
  nodejs/api/zapv2/core.js
  nodejs/api/zapv2/forcedUser.js
  nodejs/api/zapv2/httpSessions.js
  nodejs/api/zapv2/importLogFiles.js
  nodejs/api/zapv2/index.js
  nodejs/api/zapv2/package.json
  nodejs/api/zapv2/params.js
  nodejs/api/zapv2/pnh.js
  nodejs/api/zapv2/pscan.js
  nodejs/api/zapv2/reveal.js
  nodejs/api/zapv2/script.js
  nodejs/api/zapv2/search.js
  nodejs/api/zapv2/selenium.js
  nodejs/api/zapv2/sessionManagement.js
  nodejs/api/zapv2/spider.js
  nodejs/api/zapv2/stats.js
  nodejs/api/zapv2/users.js
Labels: Type-Task
