Repository zaproxy/zaproxy, pull requests merged in 2018-08, with the labels that each got.

#4896 Tweak log on missing file with user agents
  src/org/zaproxy/zap/model/CommonUserAgents.java
Labels: Type-Task

#4895 Add JavaDoc to new HttpSender method
  src/org/parosproxy/paros/network/HttpSender.java
Labels: Type-Task

#4900 Validate index/state when setting custom tab panel
  src/org/zaproxy/zap/view/StandardFieldsDialog.java
Labels: Type-Task

#4888 Address some JavaDoc warns
  src/org/apache/commons/httpclient/HttpConnection.java
  src/org/apache/commons/httpclient/HttpMethodBase.java
  src/org/apache/commons/httpclient/URI.java
  src/org/parosproxy/paros/core/scanner/VariantDdnPath.java
  src/org/parosproxy/paros/core/scanner/VariantODataIdQuery.java
  src/org/parosproxy/paros/core/scanner/VariantURLPath.java
  src/org/parosproxy/paros/extension/option/DatabaseParam.java
  src/org/parosproxy/paros/network/HttpStatusCode.java
  src/org/parosproxy/paros/network/SSLConnector.java
Labels: Type-Task

#4898 core changes required for authentication helper add on v1.1.0
  src/org/parosproxy/paros/network/HttpSender.java
  src/org/zaproxy/zap/authentication/HttpAuthenticationMethodType.java
  src/org/zaproxy/zap/authentication/UsernamePasswordAuthenticationCredentials.java
  src/org/zaproxy/zap/view/StandardFieldsDialog.java
Labels: Type-Task

#4907 Reduce code duplication in StandardFieldsDialog
  src/org/zaproxy/zap/view/StandardFieldsDialog.java
Labels: Type-Task

#4909 Verify script templates can be parsed
  build/build.xml
  test/org/zaproxy/zap/VerifyScriptTemplates.java
Labels: Type-Task

#4910 Use new utility methods for db execute(update)
  src/org/parosproxy/paros/db/DbUtils.java
  src/org/parosproxy/paros/db/paros/ParosTableAlert.java
  src/org/parosproxy/paros/db/paros/ParosTableContext.java
  src/org/parosproxy/paros/db/paros/ParosTableHistory.java
  src/org/parosproxy/paros/db/paros/ParosTableParam.java
  src/org/parosproxy/paros/db/paros/ParosTableSessionUrl.java
  src/org/parosproxy/paros/db/paros/ParosTableStructure.java
  src/org/parosproxy/paros/db/paros/ParosTableTag.java
  src/org/zaproxy/zap/db/sql/SqlTableAlert.java
  src/org/zaproxy/zap/db/sql/SqlTableContext.java
  src/org/zaproxy/zap/db/sql/SqlTableHistory.java
  src/org/zaproxy/zap/db/sql/SqlTableParam.java
  src/org/zaproxy/zap/db/sql/SqlTableSessionUrl.java
  src/org/zaproxy/zap/db/sql/SqlTableStructure.java
  src/org/zaproxy/zap/db/sql/SqlTableTag.java
Labels: Type-Task

#4920 Use default user agent in all default messages
  src/org/parosproxy/paros/extension/manualrequest/http/impl/ManualHttpRequestEditorDialog.java
  src/org/parosproxy/paros/network/ConnectionParam.java
  src/org/parosproxy/paros/network/HttpMessage.java
  src/org/parosproxy/paros/network/HttpRequestHeader.java
  src/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  src/org/zaproxy/zap/extension/api/CoreAPI.java
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  src/org/zaproxy/zap/spider/Spider.java
  src/org/zaproxy/zap/spider/SpiderTask.java
Labels: Type-Task

#4915 Address minor template script issues
  src/scripts/templates/variant/Input Vector default template.js
Labels: Type-Task

#4919 Assert the script engine exists when testing
  test/org/zaproxy/zap/VerifyScriptTemplates.java
Labels: Type-Task

#4921 Fix CME in passive scanner
  src/org/zaproxy/zap/extension/pscan/PassiveScannerList.java
  test/org/zaproxy/zap/extension/pscan/PassiveScannerListUnitTest.java
Labels: Type-Task

#4923 Correct char escaping for XML report
  src/org/parosproxy/paros/extension/report/ReportGenerator.java
  test/org/parosproxy/paros/extension/report/ReportGeneratorUnitTest.java
Labels: Type-Task

#4928 Move AntiCsrfParam to its extension
  src/org/parosproxy/paros/model/OptionsParam.java
  src/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  src/org/zaproxy/zap/extension/anticsrf/OptionsAntiCsrfPanel.java
Labels: Type-Task

#4929 Add Server header
  src/org/parosproxy/paros/network/HttpResponseHeader.java
Labels: Type-Task

#4927 Fix issues reported by LGTM
  src/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  src/org/parosproxy/paros/extension/history/PopupMenuExportResponse.java
  src/org/parosproxy/paros/model/Model.java
  src/org/zaproxy/zap/control/AddOn.java
  src/org/zaproxy/zap/extension/api/API.java
  src/org/zaproxy/zap/extension/api/CoreAPI.java
  src/org/zaproxy/zap/extension/ascan/CategoryTableModel.java
  src/org/zaproxy/zap/view/JCheckBoxTree.java
Labels: Type-Task

#4938 Show message in Find dialogue if string not found
  src/lang/Messages.properties
  src/org/parosproxy/paros/view/FindDialog.java
Labels: Type-Task

#4936 Global Excludes Additions and Updates
  src/org/zaproxy/zap/extension/globalexcludeurl/GlobalExcludeURLParam.java
Labels: Type-Task

#4941 Remove reference usage in cookie session mgmt
  src/org/zaproxy/zap/session/CookieBasedSessionManagementMethodType.java
Labels: Type-Task

#4943 Global Excludes No Longer Beta
  src/lang/Messages.properties
Labels: enhancement

#4945 Don't use HTTP session for manual auth if not set
  src/org/zaproxy/zap/authentication/ManualAuthenticationMethodType.java
Labels: bug

#4946 added _csrf to default ACSRF token names
  src/org/zaproxy/zap/extension/anticsrf/AntiCsrfParam.java
Labels: enhancement

#4952 Correct AuthenticationMethod's equals method
  src/org/zaproxy/zap/authentication/AuthenticationMethod.java
  test/org/zaproxy/zap/authentication/AuthenticationMethodUnitTest.java
Labels: Type-Task

#4957 Add LGTM.com badge to README
  README.md
Labels: Type-Task

#4937 Feature - Added a hook system into the baseline scripts & scans #4925
  docker/.gitignore
  docker/docs/scan-hooks.md
  docker/tests/README.md
  docker/tests/suite.py
  docker/tests/test_zap_common.py
  docker/tests/test_zap_hooks.py
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
  docker/zap_common.py
Labels: Type-Task

#4964 Allow to react to selection change in Scripts tree
  src/org/zaproxy/zap/extension/script/ScriptUI.java
Labels: Type-Task

#4922 Provide ZAP as a snap
  snap/.gitignore
  snap/README.md
  snap/build-snap.sh
  snap/snapcraft.yaml
  snap/wrapper
  snap/zap256x256.png
Labels: Type-Task
