Repository zaproxy/zaproxy, pull requests merged in 2018-02, with the labels that each got.

#4371 Remove incorrect validation in active scan API
  src/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java
Labels: Component-API, bug

#4358 Set history to node before adding to sites tree
  src/org/parosproxy/paros/model/SiteMap.java
Labels: Type-Task

#4370 Address deprecation in driver/cert related classes
  src/ch/csnc/extension/ui/DriverTableModel.java
  src/ch/csnc/extension/util/DriverConfiguration.java
  src/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java
Labels: Type-Task

#4377 Added Blank link target
  src/doc/scanners.md
Labels: Type-Task

#4381 Allow to snapshot with a name through the API
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/api/CoreAPI.java
Labels: Type-Task

#4379 Remove custom vectors' highlights when cleared
  src/org/zaproxy/zap/extension/ascan/CustomScanDialog.java
Labels: Component-UI, bug

#4389 Fix session file check in saveSession endpoint
  src/org/zaproxy/zap/extension/api/CoreAPI.java
Labels: Type-Task

#4386 Normalise state of Technology tab in ascan dialog
  src/org/zaproxy/zap/extension/ascan/CustomScanDialog.java
Labels: Type-Task

#4385 Address deprecation in HighlighterManager class
  src/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/HttpPanelSyntaxHighlightTextArea.java
  src/org/zaproxy/zap/extension/httppanel/view/text/HttpPanelTextArea.java
  src/org/zaproxy/zap/view/HighlighterManager.java
Labels: Type-Task

#4400 Allow to scan from Contexts tree
  src/org/zaproxy/zap/extension/ascan/ActiveScanPanel.java
  src/org/zaproxy/zap/extension/ascan/ExtensionActiveScan.java
  src/org/zaproxy/zap/extension/ascan/PopupMenuActiveScanCustomWithContext.java
  src/org/zaproxy/zap/extension/spider/ExtensionSpider.java
  src/org/zaproxy/zap/extension/spider/PopupMenuItemSpiderDialogWithContext.java
Labels: Component-UI, Usability, enhancement

#4399 Include all URLs when exporting
  src/org/zaproxy/zap/extension/api/ContextAPI.java
  src/org/zaproxy/zap/extension/history/PopupMenuExportContextURLs.java
  src/org/zaproxy/zap/extension/history/PopupMenuExportSelectedURLs.java
  src/org/zaproxy/zap/extension/history/PopupMenuExportURLs.java
Labels: Type-Task

#4395 Improve baseline error messages
  build/docker/zap-api-scan.py
  build/docker/zap-baseline.py
  build/docker/zap-full-scan.py
Labels: Docker, enhancement

#4404 Fix typos
  src/org/parosproxy/paros/CommandLine.java
  src/org/parosproxy/paros/control/MenuToolsControl.java
  src/org/parosproxy/paros/core/scanner/Analyser.java
  src/org/parosproxy/paros/core/scanner/ScannerParamFilter.java
  src/org/parosproxy/paros/core/scanner/VariantURLPath.java
  src/org/parosproxy/paros/core/scanner/VariantURLQuery.java
  src/org/parosproxy/paros/extension/filter/FilterDetectMalciousContent.java
  src/org/parosproxy/paros/extension/history/LogPanel.java
  src/org/parosproxy/paros/extension/history/ProxyListenerLog.java
  src/org/parosproxy/paros/extension/report/ReportGenerator.java
  src/org/parosproxy/paros/network/HttpHeader.java
  src/org/parosproxy/paros/network/HttpResponseHeader.java
  src/org/parosproxy/paros/network/HttpSender.java
  src/org/parosproxy/paros/view/View.java
  src/org/zaproxy/zap/GuiBootstrap.java
  src/org/zaproxy/zap/control/AddOn.java
  src/org/zaproxy/zap/control/AddOnCollection.java
  src/org/zaproxy/zap/extension/api/ApiImplementor.java
  src/org/zaproxy/zap/extension/api/CoreAPI.java
  src/org/zaproxy/zap/extension/ascan/ActiveScanController.java
  src/org/zaproxy/zap/extension/ascan/ChallengeCallbackAPI.java
  src/org/zaproxy/zap/extension/ascan/CustomScanDialog.java
  src/org/zaproxy/zap/extension/ascan/ExtensionActiveScan.java
  src/org/zaproxy/zap/extension/authentication/AuthenticationAPI.java
  src/org/zaproxy/zap/extension/autoupdate/Downloader.java
  src/org/zaproxy/zap/extension/autoupdate/ManageAddOnsDialog.java
  src/org/zaproxy/zap/extension/autoupdate/OptionsCheckForUpdatesPanel.java
  src/org/zaproxy/zap/extension/callback/CallbackParam.java
  src/org/zaproxy/zap/extension/callback/OptionsCallbackPanel.java
  src/org/zaproxy/zap/extension/encoder2/ExtensionEncoder2.java
  src/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  src/org/zaproxy/zap/extension/search/SearchThread.java
  src/org/zaproxy/zap/extension/sessions/SessionManagementAPI.java
  src/org/zaproxy/zap/extension/spider/SpiderDialog.java
  src/org/zaproxy/zap/extension/spider/SpiderScanController.java
  src/org/zaproxy/zap/extension/stdmenus/PopupContextMenuItemHolder.java
  src/org/zaproxy/zap/extension/stdmenus/PopupUserMenuItemHolder.java
  src/org/zaproxy/zap/extension/uiutils/ExtensionUiUtils.java
  src/org/zaproxy/zap/extension/users/UsersAPI.java
  src/org/zaproxy/zap/spider/SpiderController.java
  src/org/zaproxy/zap/utils/DisplayUtils.java
  src/org/zaproxy/zap/utils/FontUtils.java
  src/org/zaproxy/zap/utils/I18N.java
  src/org/zaproxy/zap/view/ContextCreateDialog.java
  src/org/zaproxy/zap/view/HighlightSearchEntry.java
  src/org/zaproxy/zap/view/JCheckBoxTree.java
  src/org/zaproxy/zap/view/OptionsConnectionPanel.java
  src/org/zaproxy/zap/view/PersistSessionDialog.java
  src/org/zaproxy/zap/view/ScanPanel.java
  src/org/zaproxy/zap/view/ScanPanel2.java
  src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java
  src/org/zaproxy/zap/view/StandardFieldsDialog.java
  src/org/zaproxy/zap/view/TabbedPanel2.java
  src/org/zaproxy/zap/view/popup/PopupMenuItemContextDataDrivenNode.java
Labels: Type-Task

#4410 Added XSLT Injection Scanner ID
  src/doc/scanners.md
Labels: Type-Task

#4414 Added WEB_SOCKET_INITIATOR
  src/org/parosproxy/paros/network/HttpSender.java
Labels: Type-Task

#4415 Added the ID for the NoSQL add-on and a new constructor for the VariantAbstractRPCQuery class
  src/doc/scanners.md
  src/org/parosproxy/paros/core/scanner/NameValuePair.java
  src/org/parosproxy/paros/core/scanner/VariantAbstractRPCQuery.java
  src/org/parosproxy/paros/core/scanner/VariantJSONQuery.java
Labels: Type-Task

#4421 Log ZAP args when executed from Docker container
  build/docker/zap_common.py
Labels: Type-Task

#4418 Expand parameters double-quoted in zap-x.sh
  build/docker/zap-x.sh
Labels: Type-Task

#4420 Map old language codes when loading resources
  src/org/zaproxy/zap/control/ExtensionFactory.java
  src/org/zaproxy/zap/extension/help/ExtensionHelp.java
  src/org/zaproxy/zap/model/VulnerabilitiesLoader.java
  src/org/zaproxy/zap/utils/I18N.java
  src/org/zaproxy/zap/utils/LocaleUtils.java
  src/org/zaproxy/zap/utils/ZapResourceBundleControl.java
  test/org/zaproxy/zap/utils/LocaleUtilsUnitTest.java
  test/org/zaproxy/zap/utils/MessagesLocaleUnitTest.java
Labels: Type-Task

#4349 Warn if a # is specified in a break point URL(Issue #4277)
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/brk/impl/http/BreakAddEditDialog.java
Labels: Type-Task

#4424 Add message to status code check in CFU requests
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Type-Task

#4423 Fail sooner if searching with invalid pattern
  src/org/zaproxy/zap/extension/search/SearchThread.java
Labels: Type-Task

#4431 Focus the tab of ancestor AbstractPanel
  src/org/parosproxy/paros/extension/AbstractPanel.java
Labels: Type-Task

#4432 Allow to get the current parameter in IV scripts
  src/org/parosproxy/paros/core/scanner/VariantCustom.java
  src/scripts/templates/variant/Input Vector default template.js
Labels: Type-Task

#4430 Allow to add AbstractPanel tabs with custom index
  src/org/zaproxy/zap/view/TabbedPanel2.java
Labels: Type-Task

#4397 Fix Issue 4391 - Include MultipartFormPost Params on Params Tab
  src/lang/Messages.properties
  src/org/parosproxy/paros/network/HtmlParameter.java
  src/org/zaproxy/zap/extension/params/ExtensionParams.java
  src/org/zaproxy/zap/extension/params/SiteParameters.java
Labels: Type-Task

#4445 Prevent use of "other" format with views/actions
  src/org/zaproxy/zap/extension/api/API.java
Labels: Type-Task

#4434 Make sure SpiderTask notifies, always, when done
  src/org/zaproxy/zap/spider/SpiderTask.java
Labels: Type-Task

#4318 Enhancement - Allow addons to "opt-in" for passive scanning
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/pscan/PassiveScanParam.java
  src/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  src/org/zaproxy/zap/extension/pscan/PassiveScannerOptionsPanel.java
Labels: enhancement

#4446 Reduce code duplication in API
  src/org/zaproxy/zap/extension/api/API.java
Labels: Type-Task
