Repository zaproxy/zaproxy, pull requests merged in 2019-06, with the labels that each got.

#5391 Release related tweaks
  .github/main.workflow
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
Labels: Type-Task

#5392 Update LEGALNOTICE
  LEGALNOTICE.md
Labels: Type-Task

#5396 Remove unnecessary class
  zap/src/main/java/ch/csnc/extension/httpclient/SSLContextManager.java
  zap/src/main/java/ch/csnc/extension/util/Encoding.java
  zap/src/test/java/ch/csnc/extension/util/EncodingUnitTest.java
Labels: Type-Task

#5398 Remove wrong whitespace char in CONTRIBUTING
  CONTRIBUTING.md
Labels: Type-Task

#5395 Add rule configuration for DOM XSS' browser
  zap/src/main/java/org/zaproxy/zap/extension/ruleconfig/RuleConfigParam.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5400 Update bundled macOS JRE
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  zap/src/main/macOS/OWASP ZAP.app/Contents/Info.plist
Labels: Type-Task

#5405 Fix Travis-CI Badge
  README.md
Labels: minor

#5406 Updated getting started guide link
  README.md
Labels: Type-Task

#5407 Prepare next dev iteration
  zap/src/main/add-ons.txt
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/zap.gradle.kts
Labels: Type-Task

#5408 Updated snapcraft file for 2.8.0
  snap/snapcraft.yaml
Labels: Type-Task

#5410 Fix Docker live image
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  docker/Dockerfile-live
Labels: Docker, Type-Task

#5413 Update JavaDoc link
  README.md
Labels: Type-Task

#5414 Fix weekly distribution
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
Labels: Type-Task

#5416 Update snap's README and Docker image
  snap/.gitignore
  snap/README.md
  snap/build-snap.sh
Labels: Type-Task

#5420 Create weekly's GitHub release as pre-release
  buildSrc/src/main/java/org/zaproxy/zap/tasks/CreateGitHubRelease.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
Labels: Type-Task

#5421 Rust API generation formating fixes
  zap/src/main/java/org/zaproxy/zap/extension/api/RustAPIGenerator.java
Labels: Type-Task

#5422 Install alpha/beta ascan rules in full scan
  docker/zap-full-scan.py
Labels: Docker, enhancement

#5424 Docker: add changelog and fix perms
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Docker

#5426 Do not run add-ons' tests for live Docker image
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  docker/Dockerfile-live
Labels: Type-Task

#5430 Include file checksums in GitHub releases
  buildSrc/src/main/java/org/zaproxy/zap/tasks/CreateGitHubRelease.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
Labels: Type-Task

#5431 Remove JxBrowser add-ons from the weekly.
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#5427 Update HTTP Protocol Version in Manual Request Editor
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/ManualHttpRequestEditorDialog.java
Labels: bug

#5436 Add new languages to context tech
  zap/src/main/java/org/zaproxy/zap/model/Tech.java
Labels: enhancement

#5446 Added rule id for Modern Web Application (info)
  docs/scanners.md
Labels: Type-Task

#5438 Address LGTM Items
  zap/src/main/java/org/parosproxy/paros/extension/encoder/Base64.java
  zap/src/main/java/org/parosproxy/paros/network/HttpInputStream.java
  zap/src/main/java/org/parosproxy/paros/network/HttpOutputStream.java
  zap/src/main/java/org/zaproxy/zap/extension/api/API.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScanProgressDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/DynamicSSLPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuExportURLs.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderPanelTableModel.java
  zap/src/main/java/org/zaproxy/zap/model/Tech.java
  zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderSVNEntriesParser.java
Labels: Type-Task
