Repository zaproxy/zaproxy, pull requests merged in 2019-03, with the labels that each got.

#5236 Expose the local add-ons through the ZAP API
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/autoupdate/AutoUpdateAPI.java
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Component-API, enhancement

#5238 Fix NPE in ExtensionLog4j in non dev mode
  src/org/zaproxy/zap/extension/log4j/ExtensionLog4j.java
Labels: bug, weekly

#5239 Provide add-on file path in API/GUI
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/autoupdate/AutoUpdateAPI.java
  src/org/zaproxy/zap/extension/autoupdate/ManageAddOnsDialog.java
Labels: Component-API, Component-UI, enhancement

#5242 Log or include malformed data in exception message
  src/org/parosproxy/paros/network/HttpRequestHeader.java
Labels: Type-Task

#5241 Copy the add-on installed through the API
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Type-Task

#5243 Spider : String Tweaks
  src/lang/Messages.properties
Labels: Type-Task

#5171 Remove help add-on related build tasks
  build/build.xml
  build/lib/java-help-0.0.1-SNAPSHOT.jar
  build/lib/jhall.jar
  build/lib/remark-1.0.0-SNAPSHOT.jar
  docker/Dockerfile-live
Labels: Type-Task

#5255 Correct update of old CFU option
  src/org/parosproxy/paros/Constant.java
  src/org/zaproxy/zap/extension/autoupdate/OptionsParamCheckForUpdates.java
  test/org/zaproxy/zap/extension/autoupdate/OptionsParamCheckForUpdatesUnitTest.java
Labels: bug, weekly

#5257 Improve error handling on shutdown
  src/org/parosproxy/paros/control/Control.java
  src/org/zaproxy/zap/extension/api/CoreAPI.java
Labels: Usability, bug

#5258 Add to scanners.md the Websocket Passive scan ID
  docs/scanners.md
Labels: Type-Task

#5264 Issue 4548 - ATTACK Mode Enablement Enhancement
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/ascan/AttackModeScanner.java
Labels: Type-Task

#5265 Correct copy task in Docker live image
  docker/Dockerfile-live
Labels: Type-Task

#5256 Added Import top-level Menu
  src/lang/Messages.properties
  src/org/parosproxy/paros/extension/ExtensionHookMenu.java
  src/org/parosproxy/paros/extension/ExtensionLoader.java
  src/org/parosproxy/paros/view/MainMenuBar.java
Labels: Component-UI, enhancement

#5270 Fix copy of default file from source with new home
  src/org/parosproxy/paros/Constant.java
Labels: Type-Task

#5269 Log exception when validating/saving panels
  src/org/parosproxy/paros/view/AbstractParamDialog.java
Labels: Type-Task

#5284 Added Hidden File Scanner ID
  docs/scanners.md
Labels: Type-Task

#5288 Remove un-used method and address LGTM finding
  src/org/parosproxy/paros/network/HttpSender.java
Labels: Type-Task

#5283 Allow active/passive scripts to provide references
  src/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  src/org/zaproxy/zap/extension/ascan/ScriptsActiveScanner.java
  src/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScanner.java
  src/scripts/templates/active/Active default template.js
  src/scripts/templates/passive/Passive default template.js
Labels: Type-Task

#5282 Provide more details on ascan API URL errors
  src/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java
Labels: Type-Task

#5266 Parsing only the authority when the request is a CONNECT. #5252
  src/org/parosproxy/paros/network/HttpRequestHeader.java
Labels: Type-Task

#5261 Request Plugin Id for Feature Policy Scanner.
  docs/scanners.md
Labels: Type-Task
