Repository zaproxy/zaproxy, pull requests merged in 2019-04, with the labels that each got.

#5276 Fixes frozen GUI when updating alert tree in non EDT
  src/org/zaproxy/zap/extension/alert/ExtensionAlert.java
Labels: Type-Task

#5293 Updates for zap-extensions' restructuring
  build/build.xml
  docker/Dockerfile-live
Labels: Type-Task

#5306 Log NPE as error when validating/saving panels
  src/org/parosproxy/paros/view/AbstractParamDialog.java
Labels: Type-Task

#5305 Use correct name for required fields
  src/org/zaproxy/zap/view/DynamicFieldsPanel.java
Labels: bug, weekly

#5300 Ignore "javax.faces.ViewState" parameter in active scans
  src/org/parosproxy/paros/core/scanner/ScannerParam.java
Labels: enhancement

#5299 refactored to reduce code-duplication
  .gitignore
  src/org/parosproxy/paros/Constant.java
Labels: Type-Task

#5319 Remove zapr from Docker images
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Docker

#5322 Deprecate Extension#getVersion()
  src/org/parosproxy/paros/extension/Extension.java
  src/org/parosproxy/paros/extension/ExtensionAdaptor.java
Labels: Type-Task

#5315 Mention DCO requirement in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Type-Task

#5329 Copy scripts also for stable/weekly Docker images
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Docker
