Repository zaproxy/zaproxy, pull requests merged in 2019-12, with the labels that each got.

#5697 Update Session Management default template.js
  zap/src/main/dist/scripts/templates/session/Session Management default template.js
Labels: Type-Task

#5724 Set default API element's description key
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiElement.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiImplementor.java
  zap/src/main/java/org/zaproxy/zap/extension/api/DotNetAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/GoAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/JavaAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/NodeJSAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/PhpAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/PythonAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/RustAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/WebUI.java
  zap/src/main/java/org/zaproxy/zap/extension/api/WikiAPIGenerator.java
  zap/src/test/java/org/zaproxy/zap/extension/api/VerifyApiImplementors.java
Labels: Type-Task

#5723 AntiCSRF Tokens Add New Defaults
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/AntiCsrfParam.java
Labels: enhancement

#5742 Do not show outdated add-ons in marketplace
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/UninstalledAddOnsTableModel.java
Labels: bug, weekly

#5747 Search: Group Search, Next, and Previous
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionHookMenu.java
  zap/src/main/java/org/zaproxy/zap/extension/search/ExtensionSearch.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5741 Handle API parameters uniformly
  zap/src/main/java/org/zaproxy/zap/extension/api/API.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiDynamicActionImplementor.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiElement.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiImplementor.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiParameter.java
  zap/src/main/java/org/zaproxy/zap/extension/api/DotNetAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/GoAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/JavaAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/NodeJSAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/PhpAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/PythonAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/RustAPIGenerator.java
  zap/src/main/java/org/zaproxy/zap/extension/api/WebUI.java
  zap/src/main/java/org/zaproxy/zap/extension/api/WikiAPIGenerator.java
  zap/src/test/java/org/zaproxy/zap/extension/api/VerifyApiImplementors.java
Labels: Type-Task

#5652 Scan filters UI changes.
  zap/src/main/java/org/zaproxy/zap/extension/ascan/CustomScanDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/FilterPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/filters/FilterCriteria.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/filters/GenericFilterUtility.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/filters/impl/AbstractGenericScanFilter.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/filters/impl/HttpStatusCodeScanFilter.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/filters/impl/MethodScanFilter.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/filters/impl/TagScanFilter.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/filters/impl/UrlPatternScanFilter.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/ascan/filters/impl/GenericFilterUtilityTest.java
Labels: Type-Task

#5729 spelling: minutes; 0 is unlimited
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5716 Spelling localization
  zap/src/main/dist/db/hsqldb.properties
  zap/src/main/dist/db/mysql.properties
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyServer.java
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableSessionUrl.java
  zap/src/main/java/org/zaproxy/zap/extension/authorization/ExtensionAuthorization.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/AddOnDependencyChecker.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/UninstallationProgressDialogue.java
  zap/src/main/java/org/zaproxy/zap/extension/params/PopupMenuAddAntiCSRF.java
  zap/src/main/java/org/zaproxy/zap/extension/params/PopupMenuRemoveAntiCSRF.java
  zap/src/main/java/org/zaproxy/zap/extension/search/OptionsSearchPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5749 Switch cancel button to end
  zap/src/main/java/org/zaproxy/zap/view/StandardFieldsDialog.java
Labels: Type-Task

#5752 spelling: breakpoint
  zap/src/main/dist/scripts/templates/proxy/Proxy default template.js
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanelToolbarFactory.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakpointMessageHandler.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakpointMessageHandler2.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakpointsPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5728 spelling: e.g.
  README.md
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
  python/scripts/generic-pytest/test_zap.config
  python/scripts/generic-pytest/test_zap.py
  python/scripts/wavsep/wavsep.py
  zap/src/main/dist/scripts/templates/httpsender/AddZapHeader.js
  zap/src/main/dist/scripts/templates/targeted/Find HTML comments.js
  zap/src/main/dist/scripts/templates/targeted/Targeted default template.js
  zap/src/main/java/org/parosproxy/paros/CommandLine.java
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/parosproxy/paros/control/MenuFileControl.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Analyser.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Plugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantDirectWebRemotingQuery.java
  zap/src/main/java/org/parosproxy/paros/db/Database.java
  zap/src/main/java/org/parosproxy/paros/extension/Extension.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java
  zap/src/main/java/org/parosproxy/paros/model/SiteNode.java
  zap/src/main/java/org/parosproxy/paros/network/HttpHeader.java
  zap/src/main/java/org/parosproxy/paros/network/HttpInputStream.java
  zap/src/main/java/org/parosproxy/paros/network/HttpMessage.java
  zap/src/main/java/org/parosproxy/paros/network/HttpRequestHeader.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/parosproxy/paros/network/SSLConnector.java
  zap/src/main/java/org/zaproxy/zap/control/ZapReleaseComparitor.java
  zap/src/main/java/org/zaproxy/zap/extension/api/API.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/AttackModeScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/CustomScanDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ExtensionActiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/GlobalExcludeURLParam.java
  zap/src/main/java/org/zaproxy/zap/extension/log4j/ExtensionLog4j.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderThread.java
  zap/src/main/java/org/zaproxy/zap/model/SessionStructure.java
  zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderParserListener.java
  zap/src/main/java/org/zaproxy/zap/utils/TableColumnManager.java
  zap/src/main/java/org/zaproxy/zap/view/NodeSelectDialog.java
  zap/src/main/java/org/zaproxy/zap/view/TabbedPanel2.java
  zap/src/main/java/org/zaproxy/zap/view/TabbedPanelTab.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/resources/resource/generate_images.pl
Labels: Type-Task

#5756 HttpHeader provide List variant for getHeaders(String)
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantCookie.java
  zap/src/main/java/org/parosproxy/paros/network/HttpHeader.java
  zap/src/main/java/org/parosproxy/paros/network/HttpMessage.java
  zap/src/main/java/org/parosproxy/paros/network/HttpRequestHeader.java
  zap/src/main/java/org/parosproxy/paros/network/HttpResponseHeader.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantCookieUnitTest.java
  zap/src/test/java/org/parosproxy/paros/network/HttpRequestHeaderUnitTest.java
Labels: enhancement

#5693 ScanFilter Panel for Filtered Nodes
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Scanner.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/ScannerListener.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScanPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/FilterMessageTableModel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/zap.gradle.kts
Labels: Type-Task

#4141 Allow to search for a String in AbstractParamContainerPanels
  zap/src/main/java/org/parosproxy/paros/view/AbstractParamContainerPanel.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/ComponentHighlighterProvider.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/ComponentSearchProvider.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/ComponentWithBackground.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/ComponentWithTitle.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/FoundComponent.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/Generic.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/HighlightedComponent.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/Highlighter.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/HighlighterResult.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/HighlighterUtils.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/InStringSearchQuery.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/JComponentWithBackground.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/Search.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/SearchAndHighlight.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/SearchQuery.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/AbstractComponentSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/ButtonSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/ComboBoxElement.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/ComboBoxElementSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/ComboBoxSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/ComponentHighlighter.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/ComponentSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/ContainerSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/JComponentSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/JxLabelSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/LabelSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/SpinnerSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TabbedPaneElement.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TabbedPaneElementSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TabbedPaneSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TableCellElement.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TableCellElementSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TableSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TextFieldSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TitledBorderSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TreeNodeElement.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TreeNodeElementSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TreeSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TreeUtils.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/view/panelsearch/SearchUnitTest.java
Labels: Type-Task

#5762 Switch to freenode
  README.md
Labels: Type-Task

#5768 Log path of new session
  zap/src/main/java/org/parosproxy/paros/control/Control.java
Labels: Type-Task

#5766 CleanCode: AboutDialog
  zap/src/main/java/org/zaproxy/zap/view/AboutDialog.java
Labels: minor

#5764 Issue 2016: Handle proxy conflict
  zap/src/main/java/org/parosproxy/paros/control/Control.java
  zap/src/main/java/org/parosproxy/paros/control/Proxy.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyPortRetryPanel.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyServer.java
  zap/src/main/java/org/parosproxy/paros/view/MainFooterPanel.java
  zap/src/main/java/org/parosproxy/paros/view/MainFrame.java
  zap/src/main/java/org/parosproxy/paros/view/View.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5769 Wait for add-ons to be installed before starting proxy
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Type-Task

#5774 Enhancement: add basic pscan tags API
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanAPI.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Component-API, enhancement

#5775 Fix button alignment in Find dialogue
  zap/src/main/java/org/parosproxy/paros/view/FindDialog.java
Labels: Type-Task
