Repository zaproxy/zaproxy, pull requests merged in 2019-05, with the labels that each got.

#5342 Uninstall before copying the local add-on
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Type-Task

#5340 Header'ify various subsections of the README
  README.md
Labels: Type-Task

#5343 Show UI name of dependent extensions
  src/org/zaproxy/zap/extension/autoupdate/AddOnDependencyChecker.java
Labels: Component-UI, Usability, enhancement

#5344 Add Search Feedback Progress Indicator
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/search/SearchListenner.java
  src/org/zaproxy/zap/extension/search/SearchPanel.java
  src/org/zaproxy/zap/extension/search/SearchThread.java
Labels: Type-Task

#5324 Enhancement: Spider handle Hyperlink Auditing Functionality
  src/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java
  test/org/zaproxy/zap/spider/parser/SpiderHtmlParserUnitTest.java
  test/resources/org/zaproxy/zap/spider/parser/html/AElementsWithPingSpiderHtmlParser.html
  test/resources/org/zaproxy/zap/spider/parser/html/AreaElementsWithPingSpiderHtmlParser.html
Labels: enhancement

#5350 Enable custom (script) input vectors by default.
  src/org/parosproxy/paros/core/scanner/ScannerParam.java
Labels: Usability, enhancement

#5351 Apply installer CFU options on update
  src/org/parosproxy/paros/Constant.java
Labels: Usability, enhancement

#5352 Fix exceptions during config update
  src/org/parosproxy/paros/Constant.java
Labels: bug

#5355 Remove macOS install configs
  build/installer/resources/Messages.properties
  build/installer/zap.install4j
Labels: Type-Task

#5356 Add -silent command line option
  src/lang/Messages.properties
  src/org/parosproxy/paros/CommandLine.java
  src/org/parosproxy/paros/Constant.java
  src/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Type-Task

#5345 Add cmdline options for loading and dumping root cert
  src/lang/Messages.properties
  src/org/zaproxy/zap/extension/dynssl/ExtensionDynSSL.java
Labels: enhancement

#5363 Update cert option on config update
  src/org/parosproxy/paros/Constant.java
Labels: Type-Task

#5362 Address JavaDoc warns with Java 11
  src/org/parosproxy/paros/db/TableHistory.java
  src/org/zaproxy/zap/extension/api/AbstractAPIGenerator.java
Labels: Type-Task

#5366 Fallback to bundled Messages file
  src/org/zaproxy/zap/utils/I18N.java
Labels: Usability, enhancement

#5370 Test Downloader validation
  test/org/zaproxy/zap/extension/autoupdate/DownloaderUnitTest.java
Labels: Type-Task

#5374 Remove usage of JDOM library
  zap/src/main/java/ch/csnc/extension/util/DriverConfiguration.java
  zap/src/main/java/org/zaproxy/zap/utils/ContentMatcher.java
  zap/src/main/resources/org/zaproxy/zap/resources/drivers.xml
  zap/src/test/java/ch/csnc/extension/util/DriverConfigurationUnitTest.java
  zap/src/test/java/org/zaproxy/zap/utils/ContentMatcherUnitTest.java
  zap/src/test/resources/ch/csnc/extension/util/drivers.xml
  zap/src/test/resources/org/zaproxy/zap/utils/content-matcher-patterns.xml
  zap/zap.gradle.kts
Labels: Type-Task

#5378 Change to use 2.8.0 cfu url
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Type-Task

#5373 First version of Rust API generator
  zap/src/main/java/org/zaproxy/zap/extension/api/RustAPIGenerator.java
  zap/zap.gradle.kts
Labels: Type-Task

#5380 Set Diff Utils as a runtime only dependency
  zap/zap.gradle.kts
Labels: Type-Task

#5381 Update dependencies
  zap/src/main/java/ch/csnc/extension/httpclient/SSLContextManager.java
  zap/src/test/java/org/parosproxy/paros/model/FileCopierUnitTest.java
  zap/src/test/java/org/zaproxy/zap/VersionUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/ZapAddOnXmlFileUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/autoupdate/DownloaderUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#5382 Update Jericho HTML Parser
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/zaproxy/zap/ZAP.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  zap/src/main/resources/org/zaproxy/zap/resources/log4j.properties
  zap/src/test/java/org/zaproxy/zap/testutils/TestUtils.java
  zap/zap.gradle.kts
Labels: Type-Task

#5385 Add task to build the weekly release
  BUILDING.md
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/internal/BuildData.kt
  zap/src/main/weekly-add-ons.json
  zap/zap.gradle.kts
Labels: Type-Task

#5386 Create releases on tag
  .github/main.workflow
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/zaproxy/zap/tasks/CreateGitHubRelease.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/installers.gradle.kts
  zap/zap.gradle.kts
Labels: Type-Task

#5387 Keep env vars for Gradle build
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
Labels: Type-Task
