Repository zaproxy/zaproxy, pull requests merged in 2019-07, with the labels that each got.

#5451 Fix removal of expired API nonces
  zap/src/main/java/org/zaproxy/zap/extension/api/API.java
  zap/src/test/java/org/zaproxy/zap/extension/api/APIUnitTest.java
Labels: Type-Task

#5452 Do not remove resource bundle of other extensions
  zap/src/main/java/org/zaproxy/zap/control/ExtensionFactory.java
Labels: bug

#5454 Remove misplaced quote in messages
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5453 Fix typo in method name
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: Type-Task

#5466 Add utility methods to Alert class
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
Labels: enhancement

#5471 Add WebSocket Passive Scan scripts in scanners.md
  docs/scanners.md
Labels: Type-Task

#5472 Add XML Suspicious Comments Disclosure ws-pscan in scanners.md
  docs/scanners.md
Labels: Type-Task

#5464 Deprecate Context.getIndex and implement Context.getId
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/parosproxy/paros/view/SessionDialog.java
  zap/src/main/java/org/parosproxy/paros/view/SiteMapPanel.java
  zap/src/main/java/org/parosproxy/paros/view/View.java
  zap/src/main/java/org/zaproxy/zap/authentication/GenericAuthenticationCredentials.java
  zap/src/main/java/org/zaproxy/zap/authentication/HttpAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/ManualAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/UsernamePasswordAuthenticationCredentials.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ContextAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/CustomScanDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/AuthenticationAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/ContextAuthenticationPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/ExtensionAuthentication.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/PopupFlagLoggedInIndicatorMenu.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/PopupFlagLoggedOutIndicatorMenu.java
  zap/src/main/java/org/zaproxy/zap/extension/authorization/ContextAuthorizationPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/authorization/ExtensionAuthorization.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ContextForcedUserPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ExtensionForcedUser.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ForcedUserAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/httpsessions/PopupMenuFactoryAddUserFromSession.java
  zap/src/main/java/org/zaproxy/zap/extension/sessions/ContextSessionManagementPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/sessions/ExtensionSessionManagement.java
  zap/src/main/java/org/zaproxy/zap/extension/sessions/SessionManagementAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupContextTreeMenu.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupUserMenuItemHolder.java
  zap/src/main/java/org/zaproxy/zap/extension/users/ContextUsersPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/users/DialogAddUser.java
  zap/src/main/java/org/zaproxy/zap/extension/users/ExtensionUserManagement.java
  zap/src/main/java/org/zaproxy/zap/extension/users/UsersAPI.java
  zap/src/main/java/org/zaproxy/zap/model/Context.java
  zap/src/main/java/org/zaproxy/zap/session/CookieBasedSessionManagementMethodType.java
  zap/src/main/java/org/zaproxy/zap/session/HttpAuthSessionManagementMethodType.java
  zap/src/main/java/org/zaproxy/zap/view/AbstractContextPropertiesPanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextExcludePanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextGeneralPanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextIncludePanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextListPanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextStructurePanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextTechnologyPanel.java
  zap/src/main/java/org/zaproxy/zap/view/panels/AbstractScanToolbarStatusPanel.java
  zap/src/main/java/org/zaproxy/zap/view/popup/PopupMenuItemContextDataDrivenNode.java
  zap/src/main/java/org/zaproxy/zap/view/popup/PopupMenuItemExcludeFromContext.java
  zap/src/main/java/org/zaproxy/zap/view/popup/PopupMenuItemIncludeInContext.java
Labels: enhancement

#5477 Fix Coverity scan
  .travis.yml
Labels: Type-Task

#5470 Coverity Fixes
  zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlFormParser.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderHtmlFormParserUnitTest.java
  zap/src/test/resources/org/zaproxy/zap/spider/parser/htmlform/FormNoDefaultValues.html
Labels: Type-Task

#5478 Update coverity_scan from develop
  .travis.yml
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/parosproxy/paros/view/SessionDialog.java
  zap/src/main/java/org/parosproxy/paros/view/SiteMapPanel.java
  zap/src/main/java/org/parosproxy/paros/view/View.java
  zap/src/main/java/org/zaproxy/zap/authentication/GenericAuthenticationCredentials.java
  zap/src/main/java/org/zaproxy/zap/authentication/HttpAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/ManualAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/UsernamePasswordAuthenticationCredentials.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ContextAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/CustomScanDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/AuthenticationAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/ContextAuthenticationPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/ExtensionAuthentication.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/PopupFlagLoggedInIndicatorMenu.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/PopupFlagLoggedOutIndicatorMenu.java
  zap/src/main/java/org/zaproxy/zap/extension/authorization/ContextAuthorizationPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/authorization/ExtensionAuthorization.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ContextForcedUserPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ExtensionForcedUser.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ForcedUserAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/httpsessions/PopupMenuFactoryAddUserFromSession.java
  zap/src/main/java/org/zaproxy/zap/extension/sessions/ContextSessionManagementPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/sessions/ExtensionSessionManagement.java
  zap/src/main/java/org/zaproxy/zap/extension/sessions/SessionManagementAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupContextTreeMenu.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupUserMenuItemHolder.java
  zap/src/main/java/org/zaproxy/zap/extension/users/ContextUsersPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/users/DialogAddUser.java
  zap/src/main/java/org/zaproxy/zap/extension/users/ExtensionUserManagement.java
  zap/src/main/java/org/zaproxy/zap/extension/users/UsersAPI.java
  zap/src/main/java/org/zaproxy/zap/model/Context.java
  zap/src/main/java/org/zaproxy/zap/session/CookieBasedSessionManagementMethodType.java
  zap/src/main/java/org/zaproxy/zap/session/HttpAuthSessionManagementMethodType.java
  zap/src/main/java/org/zaproxy/zap/view/AbstractContextPropertiesPanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextExcludePanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextGeneralPanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextIncludePanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextListPanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextStructurePanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextTechnologyPanel.java
  zap/src/main/java/org/zaproxy/zap/view/panels/AbstractScanToolbarStatusPanel.java
  zap/src/main/java/org/zaproxy/zap/view/popup/PopupMenuItemContextDataDrivenNode.java
  zap/src/main/java/org/zaproxy/zap/view/popup/PopupMenuItemExcludeFromContext.java
  zap/src/main/java/org/zaproxy/zap/view/popup/PopupMenuItemIncludeInContext.java
Labels: Type-Task

#5480 Updates to Travis CI config
  .travis.yml
Labels: Type-Task

#5484 Add JaCoCo plugin
  zap/zap.gradle.kts
Labels: Type-Task

#5489 Requesting ID for JSO
  docs/scanners.md
Labels: Type-Task

#5488 Remove unnecessary notes related to Xvfb
  zap/src/main/dist/README
  zap/src/main/dist/README.weekly
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5486 Fix counting error in Statistics
  zap/src/main/java/org/zaproxy/zap/utils/Statistics.java
  zap/src/test/java/org/zaproxy/zap/utils/StatisticsUnitTest.java
Labels: bug

#5487 Add saved scripts of registered script type
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: Component-Scripts, bug

#5492 Improve error handling when creating scan policies
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScanPolicy.java
  zap/src/test/java/org/zaproxy/zap/WithConfigsTest.java
  zap/src/test/java/org/zaproxy/zap/extension/ascan/ScanPolicyUnitTest.java
Labels: Usability, bug

#5501 More LGTM Fixes
  zap/src/main/java/org/parosproxy/paros/core/scanner/Analyser.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/impl/http/HttpBreakpointMessage.java
  zap/src/main/java/org/zaproxy/zap/view/StatusUI.java
Labels: Type-Task

#5503 Don't use msg from auth script if URI is missing
  zap/src/main/java/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: Type-Task

#5506 Add missing core APIs to generator
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiGeneratorUtils.java
Labels: Type-Task
