Repository zaproxy/zaproxy, pull requests merged in 2019-08, with the labels that each got.

#5509 Fix typo in API endpoint description
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5508 Remove null body checks
  zap/src/main/java/org/zaproxy/zap/authentication/AuthenticationMethod.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ExtensionForcedUser.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/image/ResponseImageView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largeresponse/LargeResponseUtil.java
Labels: Type-Task

#5502 Encode anti-CSRF tokens in auth requests
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
Labels: Type-Task

#4207 Improve low memory mode
  zap/src/main/dist/db/mysql.properties
  zap/src/main/dist/db/mysql.schema
  zap/src/main/java/org/parosproxy/paros/extension/history/ProxyListenerLog.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/ExtensionAlert.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
Labels: Type-Task

#5429 Add tests for org.zaproxy.zap.utils.ByteBuilder
  zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderUnitTest.java
Labels: Type-Task

#5512 Allow to add description to API parameters
  zap/src/main/java/org/zaproxy/zap/extension/api/WebUI.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#2556 Add PAC file function evaluation
  LEGALNOTICE.md
  zap/src/main/java/org/zaproxy/zap/extension/script/PacScript.java
  zap/src/test/java/org/zaproxy/zap/extension/script/PacScriptUnitTest.java
  zap/src/test/resources/org/zaproxy/zap/extension/script/dateRange.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/dnsDomainIs.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/dnsDomainLevels.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/dnsResolve.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/isInNet.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/isPlainHostName.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/isResolvable.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/localHostOrDomainIs.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/myIpAddress.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/shExpMatch.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/timeRange.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/weekdayRange.pac
  zap/zap.gradle.kts
Labels: Type-Task

#5517 Fix ByteBuilder.toString()
  zap/src/main/java/org/zaproxy/zap/utils/ByteBuilder.java
  zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderUnitTest.java
Labels: Type-Task

#5516 Genericize WritableFileChooser i18n Strings
  zap/src/main/java/org/zaproxy/zap/view/widgets/WritableFileChooser.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5515 Correct RecordStructure loading
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableStructure.java
Labels: Type-Task

#5513 Fix links to source files
  CONTRIBUTING.md
  zap/src/main/dist/scripts/templates/httpsender/AddZapHeader.js
  zap/src/main/dist/scripts/templates/httpsender/HttpSender default template.js
  zap/src/main/dist/scripts/templates/variant/Input Vector default template.js
Labels: Type-Task

#5520 Verify that APIs have corresponding resource keys
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/api/VerifyApiImplementors.java
Labels: Type-Task

#5524 Check binary compatibility of zap.jar
  zap/zap.gradle.kts
Labels: Type-Task

#5522 Removed unused Model params
  zap/src/main/java/org/parosproxy/paros/extension/report/ExtensionReport.java
  zap/src/main/java/org/parosproxy/paros/extension/report/ReportLastScan.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
Labels: Type-Task

#5528 Ensure proxy auth credentials are set
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/test/java/org/parosproxy/paros/network/HttpSenderUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#5531 Validate menu and main frame in EDT
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
Labels: Type-Task

#5525 Check that core APIs are added to generator
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiImplementor.java
  zap/src/test/java/org/zaproxy/zap/extension/api/ApiGeneratorUtilsTest.java
Labels: Type-Task

#5534 Update API wiki generator
  zap/src/main/java/org/zaproxy/zap/extension/api/WikiAPIGenerator.java
  zap/zap.gradle.kts
Labels: Type-Task

#5536 Parse result of PAC script evaluation
  zap/src/main/java/org/zaproxy/zap/extension/script/PacScript.java
  zap/src/test/java/org/zaproxy/zap/extension/script/PacScriptUnitTest.java
Labels: Type-Task

#5540 Fix failing tests on Windows
  zap/src/main/java/org/zaproxy/zap/utils/ByteBuilder.java
  zap/src/test/java/org/parosproxy/paros/extension/report/ReportGeneratorUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnUnitTest.java
  zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderUnitTest.java
Labels: Type-Task

#5544 Release 2.8.0.1
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/zap.gradle.kts
Labels: Type-Task

#5545 Fix deadlocks on check for updates
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ManageAddOnsDialog.java
Labels: Type-Task

#5547 Release 2.8.1 (for Kali)
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ManageAddOnsDialog.java
  zap/zap.gradle.kts
Labels: Type-Task

#5549 Accept abstract to default method changes
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/japicmp/AcceptMethodAbstractNowDefaultRule.kt
  zap/zap.gradle.kts
Labels: Type-Task

#5551 Remove JxBrowser add-ons from main release
  zap/src/main/add-ons.txt
Labels: Type-Task

#5546 PassiveScanner Default Methods
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/StatsPassiveScanner.java
Labels: minor

#5550 Load additional local proxies with defaults
  zap/src/main/java/org/zaproxy/zap/extension/proxies/ProxiesParam.java
Labels: Usability, enhancement

#5552 Relocate the button to install all add-ons
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ManageAddOnsDialog.java
Labels: Type-Task
