Repository zaproxy/zaproxy, pull requests merged in 2019-09, with the labels that each got.

#5555 Migrate GitHub Actions to new syntax
  .github/main.workflow
  .github/workflows/release-main-version.yml
  .github/workflows/release-weekly.yml
Labels: Type-Task

#5557 Request Plugin Id for SRI missing integrity attribute Scanner
  docs/scanners.md
Labels: Type-Task

#5558 Fix Title Caps for Active Scan Tools Options
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5554 Replace for loops with foreach and Streams
  zap/src/main/java/org/zaproxy/zap/control/AddOnLoader.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/PopupMenuItemAlert.java
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/AntiCsrfParam.java
  zap/src/main/java/org/zaproxy/zap/extension/ext/ExtensionParam.java
  zap/src/main/java/org/zaproxy/zap/extension/help/ZapBasicSearchNavigatorUI.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/HttpPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/posttable/RequestPostTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScannerList.java
  zap/src/main/java/org/zaproxy/zap/model/StandardParameterParser.java
  zap/src/main/java/org/zaproxy/zap/utils/HashUtils.java
  zap/src/main/java/org/zaproxy/zap/utils/ZapNumberSpinner.java
  zap/src/main/java/org/zaproxy/zap/view/AbstractMultipleOptionsTableModel.java
  zap/src/main/java/org/zaproxy/zap/view/table/DefaultHistoryReferencesTableEntry.java
Labels: Type-Task

#5561 Ignore ascan example rules
  docker/CHANGELOG.md
  docker/zap-full-scan.py
Labels: Docker

#5563 Include Import/Online menus in Options > Keyboard
  zap/src/main/java/org/zaproxy/zap/extension/keyboard/ExtensionKeyboard.java
Labels: Component-UI, Usability, enhancement

#5569 Issue 5334 Suppress Stack Trace - Corrupt Addon(s)
  zap/src/main/java/org/zaproxy/zap/control/AddOn.java
Labels: Type-Task

#5567 #3491 Adds support for selecting multiple contexts in the Sites tab
  zap/src/main/java/org/parosproxy/paros/view/SiteMapPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/PopupMenuActiveScanCustomWithContext.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuExportContextURLs.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/PopupMenuItemSpiderDialogWithContext.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/ExtensionStdMenus.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupContextTreeMenu.java
  zap/src/main/java/org/zaproxy/zap/view/DeleteContextAction.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5583 Simplify Proxy.stopServer()
  zap/src/main/java/org/parosproxy/paros/control/Proxy.java
Labels: minor

#5584 HttpSender use remove() instead of set(null) on IN_LISTENER.
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
Labels: minor

#5598 Revise site certificate validity period to 825d
  zap/src/main/java/org/parosproxy/paros/security/SslCertificateServiceImpl.java
Labels: Usability, enhancement

#5594 Fix deadlock when adding HTTP views
  zap/src/main/java/org/zaproxy/zap/utils/ThreadUtils.java
  zap/src/main/java/org/zaproxy/zap/view/HttpPanelManager.java
Labels: Type-Task

#5603 Prefer instance view usage
  zap/src/main/java/org/parosproxy/paros/control/Control.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionAdaptor.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/main/java/org/parosproxy/paros/extension/history/ExtensionHistory.java
  zap/src/main/java/org/parosproxy/paros/extension/history/ProxyListenerLog.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/ExtensionAlert.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ExtensionAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ExtensionActiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/ExtensionBreak.java
  zap/src/main/java/org/zaproxy/zap/extension/callback/ExtensionCallback.java
  zap/src/main/java/org/zaproxy/zap/extension/compare/ExtensionCompare.java
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/ExtensionDynSSL.java
  zap/src/main/java/org/zaproxy/zap/extension/keyboard/ExtensionKeyboard.java
  zap/src/main/java/org/zaproxy/zap/extension/log4j/ExtensionLog4j.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/ExtensionSpider.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/ExtensionStdMenus.java
  zap/src/main/java/org/zaproxy/zap/extension/uiutils/ExtensionUiUtils.java
Labels: Type-Task
