Repository zaproxy/zaproxy, pull requests merged in 2019-10, with the labels that each got.

#5586 install zap python3 version of the library in containers
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Docker

#4963 Allow to specify the URI of the login page
  zap/src/main/java/org/parosproxy/paros/view/SessionDialog.java
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Usability, enhancement

#5613 Cope with missing token in auth POST data
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
Labels: bug

#5612 Restore error counter
  zap/src/main/java/org/zaproxy/zap/extension/log4j/ExtensionLog4j.java
Labels: bug, weekly

#5615 Exclude methods moved to interface
  zap/zap.gradle.kts
Labels: Type-Task

#5614 Manual Request Editor Icon
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ExtensionManualRequestEditor.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ManualRequestEditorDialog.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/ManualHttpRequestEditorDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/ExtensionStdMenus.java
  zap/src/main/resources/resource/icon/16/hand.png
Labels: Component-UI, enhancement

#5617 Tidy up tests
  zap/src/test/java/ch/csnc/extension/util/DriverConfigurationUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantCookieUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantHeaderUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnCollectionUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/ZapReleaseComparitorUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/ZapReleaseUnitTest.java
  zap/src/test/java/org/zaproxy/zap/eventBus/SimpleEventBusUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/ApiResponseElementUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/ApiResponseListUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/ApiResponseSetUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/ruleconfig/RuleConfigParamUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/StandardParameterParserUnitTest.java
  zap/src/test/java/org/zaproxy/zap/network/HttpBodyTestUtils.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderHtmlFormParserUnitTest.java
Labels: Type-Task

#5618 Update Mockito to 3.1.0
  zap/src/test/java/ch/csnc/extension/httpclient/AliasCertificateUnitTest.java
  zap/src/test/java/ch/csnc/extension/httpclient/AliasKeyManagerUnitTest.java
  zap/src/test/java/org/parosproxy/paros/CommandLineUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/PluginFactoryUnitTest.java
  zap/src/test/java/org/parosproxy/paros/model/FileCopierUnitTest.java
  zap/src/test/java/org/zaproxy/zap/WithConfigsTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/AuthenticationMethodIndicatorsUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/APIUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/ApiResponseConversionUtilsUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/authorization/BasicAuthorizationDetectionMethodUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/ContextUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/filters/DefaultFetchFilterUnitTest.java
  zap/src/test/java/org/zaproxy/zap/users/UserUnitTest.java
  zap/src/test/java/org/zaproxy/zap/users/UsersTableModelUnitTest.java
  zap/src/test/java/org/zaproxy/zap/utils/LocaleUtilsUnitTest.java
  zap/src/test/java/org/zaproxy/zap/view/widgets/UsersListModelUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#5620 Ensure -configfile maintains key order
  zap/src/main/java/org/parosproxy/paros/CommandLine.java
  zap/src/test/java/org/parosproxy/paros/CommandLineUnitTest.java
Labels: Type-Task

#5622 Consistent SessionTracking Button Sync
  zap/src/main/java/org/parosproxy/paros/extension/history/ExtensionHistory.java
Labels: Component-UI, Usability, bug

#5599 Adds option to disable/enable cookies on manual resend
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/HttpPanelSender.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/resources/resource/icon/fugue/globe-green.png
Labels: Type-Task

#5580 Remove homepage URL from ZAP extensions
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/ExtensionAlert.java
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ExtensionAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ExtensionActiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/ExtensionAuthentication.java
  zap/src/main/java/org/zaproxy/zap/extension/authorization/ExtensionAuthorization.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/ExtensionBreak.java
  zap/src/main/java/org/zaproxy/zap/extension/compare/ExtensionCompare.java
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/ExtensionDynSSL.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/ExtensionEncoder2.java
  zap/src/main/java/org/zaproxy/zap/extension/ext/ExtensionExtension.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ExtensionForcedUser.java
  zap/src/main/java/org/zaproxy/zap/extension/help/ExtensionHelp.java
  zap/src/main/java/org/zaproxy/zap/extension/httpsessions/ExtensionHttpSessions.java
  zap/src/main/java/org/zaproxy/zap/extension/keyboard/ExtensionKeyboard.java
  zap/src/main/java/org/zaproxy/zap/extension/log4j/ExtensionLog4j.java
  zap/src/main/java/org/zaproxy/zap/extension/params/ExtensionParams.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/ExtensionProxies.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/ruleconfig/ExtensionRuleConfig.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
  zap/src/main/java/org/zaproxy/zap/extension/search/ExtensionSearch.java
  zap/src/main/java/org/zaproxy/zap/extension/sessions/ExtensionSessionManagement.java
  zap/src/main/java/org/zaproxy/zap/extension/siterefresh/ExtensionSitesRefresh.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/ExtensionSpider.java
  zap/src/main/java/org/zaproxy/zap/extension/stats/ExtensionStats.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/ExtensionStdMenus.java
  zap/src/main/java/org/zaproxy/zap/extension/uiutils/ExtensionUiUtils.java
  zap/src/main/java/org/zaproxy/zap/extension/users/ExtensionUserManagement.java
Labels: Type-Task

#5625 Remove old alert update
  zap/src/main/java/org/parosproxy/paros/db/RecordAlert.java
Labels: Type-Task

#5626 Add SSTI scanners ID
  docs/scanners.md
Labels: Type-Task

#5627 Update GitHub Action workflows
  .github/workflows/release-main-version.yml
  .github/workflows/release-weekly.yml
Labels: Type-Task

#5628 Typos `Modfiying` => `Modifying`
  docker/docs/scan-hooks.md
Labels: Type-Task

#5631 Remove Dialog Icon on Manual Request Editor
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ManualRequestEditorDialog.java
Labels: Type-Task

#5634 Docker: include response code in scan output
  docker/CHANGELOG.md
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
  docker/zap_common.py
Labels: Docker, enhancement

#5641 Update dependencies
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#5640 Increase DB cache size
  zap/src/main/resources/org/zaproxy/zap/resources/zapdb.script
Labels: Type-Task

#5642 Address NPE in spider scan
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderScan.java
Labels: bug, minor

#5645 Test AbstractPlugin#bingo methods
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AbstractPluginUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/PluginTestUtils.java
Labels: Type-Task

#5649 Handle shortcut only if API request
  zap/src/main/java/org/zaproxy/zap/extension/api/API.java
  zap/src/test/java/org/zaproxy/zap/extension/api/APIUnitTest.java
Labels: Type-Task

#5654 Allow to add description to API implementors
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiImplementor.java
  zap/src/main/java/org/zaproxy/zap/extension/api/WebUI.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/api/VerifyApiImplementors.java
Labels: Type-Task

#5655 Tweak description of add-on command line args
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5657 Allow to raise alerts more easily
  zap/src/main/dist/scripts/templates/active/Active default template.js
  zap/src/main/dist/scripts/templates/passive/Passive default template.js
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScriptsActiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScanner.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AbstractPluginUnitTest.java
Labels: Type-Task

#5660 Changed to use new github issue links
  .github/ISSUE_TEMPLATE/Z_Ask_a_question.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: Type-Task

#5662 Add config for lockbot
  .github/lock.yml
Labels: minor
