Repository zaproxy/zaproxy, pull requests merged in 2020-09, with the labels that each got.

#6157 Fix JUnit build
  zap/zap.gradle.kts
Labels: Type-Task

#6160 Properly decode gzip in UI and decode request
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/HttpPanelViewModelUtils.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestBodyByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestBodyStringHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestStringHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseBodyByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseBodyStringHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseStringHttpPanelViewModel.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/BodyByteHttpPanelViewModelTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/BodyStringHttpPanelViewModelTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/HttpPanelViewModelUtilsUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/StringHttpPanelViewModelTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestBodyByteHttpPanelViewModelUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestBodyStringHttpPanelViewModelUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestStringHttpPanelViewModelUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseBodyByteHttpPanelViewModelUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseBodyStringHttpPanelViewModelUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseStringHttpPanelViewModelUnitTest.java
Labels: Type-Task

#6146 Add support for site modifiers
  zap/src/main/dist/scripts/templates/variant/Input Vector default template.js
  zap/src/main/dist/scripts/templates/variant/Site modifying JSON example.js
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractAppParamPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/NameValuePair.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Variant.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantCustom.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantScript.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionHook.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/main/java/org/parosproxy/paros/extension/history/ProxyListenerLog.java
  zap/src/main/java/org/parosproxy/paros/model/Model.java
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/parosproxy/paros/model/SiteMap.java
  zap/src/main/java/org/parosproxy/paros/network/HtmlParameter.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/VariantFactory.java
  zap/src/main/java/org/zaproxy/zap/model/SessionStructure.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/parosproxy/paros/core/scanner/NameValuePairUnitTest.java
  zap/src/test/java/org/parosproxy/paros/model/SessionUnitTest.java
  zap/src/test/java/org/parosproxy/paros/network/HtmlParameterUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/ascan/VariantFactoryUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#6177 Update Scanners.md for adding new id 40037
  docs/scanners.md
Labels: Type-Task

#5719 Spelling needs upgradefrom
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/HttpPanelSyntaxHighlightTextArea.java
  zap/src/test/java/org/parosproxy/paros/ConstantUnitTest.java
Labels: Type-Task

#6182 Improve error message when starting packaged scans
  docker/CHANGELOG.md
  docker/tests/suite.py
  docker/tests/test_zap_common.py
  docker/tests/test_zap_hooks.py
  docker/zap_common.py
Labels: Docker

#6186 Request Id for Cross-Origin Resource Policy Scan rule
  docs/scanners.md
Labels: Type-Task

#6181 Fix typo in extension name
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/component/all/ExtensionHttpPanelComponentAll.java
Labels: Type-Task

#6187 Wire in site mod changes
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantCustom.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantScript.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantCustomUnitTest.java
Labels: Type-Task

#6188 Correct incremental delay in scheduled executor
  zap/src/main/java/org/zaproxy/zap/utils/PausableScheduledThreadPoolExecutor.java
  zap/src/test/java/org/zaproxy/zap/utils/PausableScheduledThreadPoolExecutorUnitTest.java
Labels: Type-Task

#6191 Add GraphQL Add-on to Weekly Release
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#6192 Add new NameValuePair Type for GraphQL Inline Args
  zap/src/main/java/org/parosproxy/paros/core/scanner/NameValuePair.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/ScannerParamFilter.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#3638 Initial CustomPages Implementation
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Scanner.java
  zap/src/main/java/org/zaproxy/zap/control/CoreFunctionality.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScriptsActiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/ContextCustomPagePanel.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/CustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/CustomPageMatcherLocation.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/CustomPageTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/DefaultCustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/DialogAddCustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/DialogModifyCustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/ExtensionCustomPages.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/PopupFlagCustomPageIndicatorMenu.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanData.java
  zap/src/main/java/org/zaproxy/zap/model/Context.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#6195 Upgrade SQLite to 3.32.3.2
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6197 Fix WebSwing URLs
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Docker, Type-Task

#6194 Custom Pages analyzer fallback & clean code
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/CustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanData.java
  zap/src/main/java/org/zaproxy/zap/model/Context.java
Labels: Type-Task

#6193 Add option to not fix the content length
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/HttpPanelSender.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/HttpPanelViewModelUtils.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/resources/resource/icon/fugue/application-resize.png
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/BodyByteHttpPanelViewModelTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/BodyStringHttpPanelViewModelTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/HttpPanelViewModelUtilsUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/StringHttpPanelViewModelTest.java
Labels: Type-Task
