Repository zaproxy/zaproxy, pull requests merged in 2020-06, with the labels that each got.

#6021 Minor JavaDoc Correction
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsConnectionPanel.java
Labels: Type-Task

#6019 Issue 78: Add source info/icon to HistoryTable
  zap/src/main/java/org/parosproxy/paros/extension/history/HistoryTableModel.java
  zap/src/main/java/org/zaproxy/zap/view/HrefTypeInfo.java
  zap/src/main/java/org/zaproxy/zap/view/table/AbstractHistoryReferencesTableEntry.java
  zap/src/main/java/org/zaproxy/zap/view/table/AbstractHistoryReferencesTableModel.java
  zap/src/main/java/org/zaproxy/zap/view/table/DefaultHistoryReferencesTableEntry.java
  zap/src/main/java/org/zaproxy/zap/view/table/HistoryReferencesTable.java
  zap/src/main/java/org/zaproxy/zap/view/table/HistoryReferencesTableModel.java
  zap/src/main/java/org/zaproxy/zap/view/table/decorator/HrefTypeInfoIconHighlighter.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/resources/resource/icon/16/doublearrow.png
Labels: Type-Task

#6006 Fix "_XSERVTransmkdir: ERROR"
  docker/zap-x.sh
Labels: Docker

#6028 Fix allow/deny list terminology
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
  docker/zap_common.py
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyThread.java
  zap/src/main/java/org/parosproxy/paros/network/HttpRequestHeader.java
  zap/src/main/resources/org/zaproxy/zap/resources/vulnerabilities.xml
Labels: Type-Task

#6026 JavaDoc Fixes
  zap/src/main/java/org/parosproxy/paros/extension/edit/ExtensionEdit.java
  zap/src/main/java/org/parosproxy/paros/view/MainMenuBar.java
Labels: minor

#6033 Update FlatLaf
  zap/zap.gradle.kts
Labels: Type-Task

#6044 Call default filter after custom filters
  zap/src/main/java/org/zaproxy/zap/spider/Spider.java
  zap/src/main/java/org/zaproxy/zap/spider/SpiderController.java
  zap/src/main/java/org/zaproxy/zap/spider/SpiderTask.java
  zap/src/main/java/org/zaproxy/zap/spider/filters/ParseFilter.java
Labels: Type-Task

#6046 Just warn if ECMAScript engine is not found
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: Type-Task

#6050 Remove Coverity setup from Travis CI config
  .travis.yml
Labels: Type-Task

#6051 Remove Coverity Badge
  README.md
Labels: Type-Task

#6052 Remove Coverity Badge (Take 2)
  README.md
Labels: Type-Task
