Repository zaproxy/zaproxy, pull requests merged in 2020-02, with the labels that each got.

#5844 Add context menu item to mark false positives
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/ExtensionAlert.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/PopupMenuAlertSetFalsePositive.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Component-UI, Usability, enhancement

#5739 Reword autoupdate message about having current version to make it l10n friendly
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ManageAddOnsDialog.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5848 Update Python docker scripts to be Python 3 compatible
  docker/CHANGELOG.md
  docker/zap-api-scan.py
  docker/zap-full-scan.py
  docker/zap_common.py
Labels: Docker

#5850 Scan Rule Deprecations
  docs/scanners.md
Labels: Type-Task

#5854 Update scanners.md
  docs/scanners.md
Labels: Type-Task

#5828 Add a button on the resend screen to inject a CSRF token
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/HttpPanelSender.java
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/HttpMessageSender.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/resources/resource/icon/csrf-button.png
Labels: Type-Task

#5870 Adding missing check for markdown file in baseline scan
  docker/CHANGELOG.md
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
Labels: Docker

#5873 Add FlatLaf L&F
  LEGALNOTICE.md
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsParamView.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsViewPanel.java
  zap/src/main/java/org/zaproxy/zap/GuiBootstrap.java
  zap/src/main/java/org/zaproxy/zap/extension/uiutils/ExtensionUiUtils.java
  zap/zap.gradle.kts
Labels: Component-UI, enhancement

#5874 Revise Site Certificates to Max 398d
  zap/src/main/java/org/parosproxy/paros/security/SslCertificateServiceImpl.java
Labels: enhancement

#5878 Set RSyntaxTextArea dark mode if dark LookAndFeel used
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/HttpPanelSyntaxHighlightTextArea.java
  zap/src/main/java/org/zaproxy/zap/utils/DisplayUtils.java
Labels: Type-Task
