Repository zaproxy/zaproxy, pull requests merged in 2020-11, with the labels that each got.

#6276 Check if Log4j legacy conf backup already exists
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/test/java/org/parosproxy/paros/ConstantUnitTest.java
Labels: Type-Task

#6275 Fix exception while loading session
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/parosproxy/paros/model/SiteMap.java
  zap/src/test/java/org/parosproxy/paros/model/SessionUnitTest.java
  zap/src/test/java/org/parosproxy/paros/model/SiteMapUnitTest.java
Labels: Type-Task

#6277 Add OneTouchExapandable control to Sites Tree/Request&Response panels
  zap/src/main/java/org/parosproxy/paros/view/WorkbenchPanel.java
Labels: Component-UI, Usability, enhancement

#6279 Warn when unable to save malformed HTTP message
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ManualRequestEditorDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanelToolbarFactory.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/HttpPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/HttpPanelRequest.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/InvalidMessageDataException.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/component/HttpPanelComponentInterface.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/component/HttpPanelComponentViewsManager.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/HttpPanelView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestHeaderByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestHeaderStringHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestStringHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseHeaderByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseHeaderStringHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseStringHttpPanelViewModel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/StringHttpPanelViewModelTest.java
Labels: Type-Task

#6278 Add Alert reference field
  zap/src/main/dist/db/hsqldb.properties
  zap/src/main/dist/db/mysql.properties
  zap/src/main/dist/db/mysql.schema
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Plugin.java
  zap/src/main/java/org/parosproxy/paros/db/RecordAlert.java
  zap/src/main/java/org/parosproxy/paros/db/TableAlert.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableAlert.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableAlert.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/ExampleAlertProvider.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/ExtensionAlert.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AlertUnitTest.java
  zap/zap.gradle.kts
Labels: enhancement

#6282 Allow to instantiate AbstractFrame
  zap/src/main/java/org/parosproxy/paros/view/AbstractFrame.java
Labels: Type-Task

#6245 PassiveScanData add unit tests & active scan status code fallbacks
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanData.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AbstractPluginUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScanDataUnitTest.java
Labels: Type-Task

#6285 Use the whole message to get the leaf name
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantCustom.java
  zap/src/main/java/org/parosproxy/paros/model/Session.java
Labels: Type-Task

#6284 Address exceptions related to parameter parsing
  zap/src/main/java/org/zaproxy/zap/model/ParameterParser.java
  zap/src/main/java/org/zaproxy/zap/model/StandardParameterParser.java
  zap/src/test/java/org/zaproxy/zap/model/StandardParameterParserUnitTest.java
  zap/zap.gradle.kts
Labels: bug, weekly

#6286 Add Custom Page unit tests for HostProcess
  zap/src/test/java/org/parosproxy/paros/core/scanner/HostProcessUnitTest.java
Labels: Type-Task

#6163 Support authentication polling
  zap/src/main/java/org/parosproxy/paros/db/RecordContext.java
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/zaproxy/zap/authentication/AuthenticationHelper.java
  zap/src/main/java/org/zaproxy/zap/authentication/AuthenticationMethod.java
  zap/src/main/java/org/zaproxy/zap/authentication/AuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/HttpAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/JsonBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/ManualAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ContextAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/ContextAuthenticationPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/ExtensionAuthentication.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ExtensionForcedUser.java
  zap/src/main/java/org/zaproxy/zap/extension/httpsessions/ExtensionHttpSessions.java
  zap/src/main/java/org/zaproxy/zap/users/User.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/parosproxy/paros/model/SessionUnitTest.java
  zap/src/test/java/org/zaproxy/zap/WithConfigsTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/AuthenticationMethodIndicatorsUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/AuthenticationMethodPollUrlUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/AuthenticationMethodUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/JsonBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/authentication/ExtensionAuthenticationUnitTest.java
  zap/src/test/java/org/zaproxy/zap/testutils/HTTPDTestServer.java
  zap/src/test/java/org/zaproxy/zap/testutils/NanoServerHandler.java
  zap/src/test/java/org/zaproxy/zap/testutils/TestUtils.java
  zap/zap.gradle.kts
Labels: enhancement

#6289 Add convenience methods for identifying CSS related messages
  zap/src/main/java/org/parosproxy/paros/network/HttpRequestHeader.java
  zap/src/main/java/org/parosproxy/paros/network/HttpResponseHeader.java
  zap/src/test/java/org/parosproxy/paros/network/HttpRequestHeaderUnitTest.java
  zap/src/test/java/org/parosproxy/paros/network/HttpResponseHeaderUnitTest.java
Labels: Type-Task

#6057 Fix bug that makes zap test same request twice
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/HostProcessUnitTest.java
Labels: Type-Task

#6296 Add auth header define in envvars
  zap/src/main/java/org/zaproxy/zap/extension/authentication/ExtensionAuthentication.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/HttpSenderAuthHeaderListener.java
  zap/src/test/java/org/zaproxy/zap/extension/authentication/HttpSenderAuthHeaderListenerUnitTest.java
Labels: enhancement

#6244 Add GraphQL to Docker Packaged API Scan
  docker/CHANGELOG.md
  docker/zap-api-scan.py
Labels: Docker

#6300 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6303 Add graaljs to weekly
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#6307 Fix NPE importing context with no poll data
  zap/src/main/java/org/zaproxy/zap/extension/authentication/ExtensionAuthentication.java
  zap/src/test/java/org/zaproxy/zap/extension/authentication/ExtensionAuthenticationUnitTest.java
Labels: bug, weekly

#6310 CustomPages: Add core isSuccess Method(s)
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanData.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AbstractPluginUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScanDataUnitTest.java
Labels: Type-Task

#6311 Docker: add zap_tune function and zap_tuned hook
  docker/CHANGELOG.md
  docker/tests/test_zap_common.py
  docker/tests/test_zap_hooks.py
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
  docker/zap_common.py
Labels: Docker, enhancement

#6315 Guard against invalid message views
  buildSrc/src/main/kotlin/org/zaproxy/zap/test.gradle.kts
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/component/HttpPanelComponentViewsManager.java
  zap/src/testGui/java/org/zaproxy/testutils/AbstractGuiTest.java
  zap/src/testGui/java/org/zaproxy/testutils/GuiCondition.java
  zap/src/testGui/java/org/zaproxy/zap/extension/httppanel/component/HttpPanelComponentViewsManagerGuiTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#6313 Manual Request response send
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ManualRequestEditorDialog.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/HttpPanelSender.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/ManualHttpRequestEditorDialog.java
Labels: Component-UI, Usability, enhancement

#6318 Support packaged authenticated scans
  docker/CHANGELOG.md
  docker/tests/test_zap_common.py
  docker/tests/test_zap_hooks.py
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
  docker/zap_common.py
Labels: Docker, enhancement

#6317 Do not recompile the scripts if not changed
  zap/src/main/java/org/parosproxy/paros/control/Control.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantCustom.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScriptsActiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/VariantFactory.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
  zap/src/main/java/org/zaproxy/zap/extension/script/HttpSenderScriptListener.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ProxyListenerScript.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptWrapper.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptsCache.java
  zap/src/test/java/org/parosproxy/paros/model/SessionUnitTest.java
  zap/src/test/java/org/zaproxy/zap/WithConfigsTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/JsonBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/ApiGeneratorUtilsTest.java
  zap/src/test/java/org/zaproxy/zap/extension/ascan/ScriptsActiveScannerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/ascan/VariantFactoryUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/forceduser/ExtensionForcedUserUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScannerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/script/ExtensionScriptUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/script/HttpSenderScriptListenerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/script/ProxyListenerScriptUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/script/ScriptWrapperUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/script/ScriptsCacheUnitTest.java
Labels: Type-Task

#6322 Log params at Debug Level
  docker/CHANGELOG.md
  docker/zap_common.py
Labels: Docker

#6329 Fix Req/Resp highlighting in dark mode
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/HttpPanelSyntaxHighlightTextArea.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/components/all/request/HttpRequestAllPanelSyntaxHighlightTextView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/components/split/request/HttpRequestBodyPanelSyntaxHighlightTextView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/components/split/request/HttpRequestHeaderPanelSyntaxHighlightTextView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/text/HttpPanelTextArea.java
  zap/src/main/java/org/zaproxy/zap/utils/DisplayUtils.java
Labels: Type-Task

#6331 Remove PacScript
  LEGALNOTICE.md
  zap/src/main/java/org/zaproxy/zap/extension/script/PacScript.java
  zap/src/test/java/org/zaproxy/zap/extension/script/PacScriptUnitTest.java
  zap/src/test/resources/org/zaproxy/zap/extension/script/dateRange.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/dnsDomainIs.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/dnsDomainLevels.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/dnsResolve.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/isInNet.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/isPlainHostName.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/isResolvable.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/localHostOrDomainIs.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/myIpAddress.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/shExpMatch.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/timeRange.pac
  zap/src/test/resources/org/zaproxy/zap/extension/script/weekdayRange.pac
  zap/zap.gradle.kts
Labels: Type-Task

#6328 Tweak panel search and find dialog to be friendly w/ dark LaFs
  zap/src/main/java/org/parosproxy/paros/view/FindDialog.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/HighlighterUtils.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/ButtonSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/ComboBoxElementSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/ComboBoxSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/JxLabelSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/LabelSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/SpinnerSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TabbedPaneSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TableCellElementSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TableSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TextFieldSearch.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TreeNodeElementSearch.java
Labels: Type-Task
