Repository zaproxy/zaproxy, pull requests merged in 2020-12, with the labels that each got.

#6335 Update dependencies
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6293 Auth multi-user fix and new API endpoints
  zap/src/main/java/org/zaproxy/zap/authentication/AuthenticationMethod.java
  zap/src/main/java/org/zaproxy/zap/authentication/HttpAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiImplementor.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiResponseSet.java
  zap/src/main/java/org/zaproxy/zap/extension/users/UsersAPI.java
  zap/src/main/java/org/zaproxy/zap/users/AuthenticationState.java
  zap/src/main/java/org/zaproxy/zap/users/User.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/authentication/AuthenticationMethodIndicatorsUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/AuthenticationMethodPollUrlUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/users/UserUnitTest.java
Labels: Type-Task

#6334 Correct anti-csrf form generation
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  zap/src/test/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRFUnitTest.java
Labels: Type-Task

#6337 fix/Dockerfile: Use ARG directive instead of ENV
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Docker

#6333 Refactor SessionStructure and Session
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantCustom.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantDdnPath.java
  zap/src/main/java/org/parosproxy/paros/extension/history/ProxyListenerLog.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/HttpPanelSender.java
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/parosproxy/paros/model/SiteMap.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/ExtensionAlert.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderThread.java
  zap/src/main/java/org/zaproxy/zap/model/SessionStructure.java
  zap/src/test/java/org/parosproxy/paros/model/SessionUnitTest.java
  zap/src/test/java/org/parosproxy/paros/model/SiteMapUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/SessionStructureUnitTest.java
Labels: Maintainability, enhancement

#6348 Do not update Content-Length in byte models
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/HttpPanelViewModelUtils.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseByteHttpPanelViewModel.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/ByteHttpPanelViewModelTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/HttpPanelViewModelUtilsUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestByteHttpPanelViewModelUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseByteHttpPanelViewModelUnitTest.java
Labels: Type-Task

#6349 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6347 Reserve ID for active scan rule
  docs/scanners.md
Labels: Type-Task

#5864 Add buttons to select the file types ignored on Break
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsViewPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanelToolbarFactory.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakpointMessageHandler2.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakpointsOptionsPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakpointsParam.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/ExtensionBreak.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/resources/resource/icon/breakTypes/cssAndFonts.png
  zap/src/main/resources/resource/icon/breakTypes/cssAndFontsNotBreaking.png
  zap/src/main/resources/resource/icon/breakTypes/javascript.png
  zap/src/main/resources/resource/icon/breakTypes/javascriptNotBreaking.png
  zap/src/main/resources/resource/icon/breakTypes/multimedia.png
  zap/src/main/resources/resource/icon/breakTypes/multimediaNotBreaking.png
  zap/src/main/resources/resource/icon/breakTypes/sources.txt
  zap/src/test/java/org/zaproxy/zap/extension/brk/BreakpointMessageHandler2UnitTest.java
Labels: Component-UI, enhancement

#6353 Update default and common user agents
  zap/src/main/dist/xml/common-user-agents.txt
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/parosproxy/paros/network/ConnectionParam.java
Labels: enhancement

#6350 Add node for URLs ending with a slash
  zap/src/main/java/org/parosproxy/paros/model/SiteNode.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/model/StandardParameterParser.java
  zap/src/main/java/org/zaproxy/zap/view/StandardFieldsDialog.java
  zap/src/test/java/org/parosproxy/paros/model/SiteMapUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/SessionStructureUnitTest.java
Labels: Type-Task

#6354 Update email used in certs
  zap/src/main/java/org/parosproxy/paros/security/SslCertificateServiceImpl.java
Labels: Type-Task

#6355 Common user agents: Fix tabs and spaces
  zap/src/main/dist/xml/common-user-agents.txt
Labels: Type-Task

#6356 Add target to ajaxSpider.scan_as_user call
  docker/CHANGELOG.md
  docker/tests/test_zap_common.py
  docker/zap_common.py
Labels: Docker

#6358 Avoid NPE when checking for AuthenticationScriptV2
  zap/src/main/java/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
Labels: Type-Task

#6357 Custom Pages: Add Help Index
  zap/src/main/java/org/zaproxy/zap/extension/custompages/ContextCustomPagePanel.java
Labels: Type-Task

#6295 Added support for dynamic technologies
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Scanner.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ContextAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/CustomScanDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanData.java
  zap/src/main/java/org/zaproxy/zap/model/Context.java
  zap/src/main/java/org/zaproxy/zap/model/Tech.java
  zap/src/main/java/org/zaproxy/zap/model/TechSet.java
  zap/src/main/java/org/zaproxy/zap/view/ContextTechnologyPanel.java
  zap/src/main/java/org/zaproxy/zap/view/TechnologyTreePanel.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AbstractPluginUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/HostProcessUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScanDataUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/TechSetUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/TechUnitTest.java
Labels: Type-Task

#6361 Update Webswing and Java in stable
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
  docker/webswing.config
  docker/webswing.properties
  docker/zap-webswing.sh
Labels: Type-Task

#6360 Update for 2.10 add-ons
  zap/src/main/add-ons.txt
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#6365 Update version post 2.10.0 release
  zap/zap.gradle.kts
Labels: Type-Task

#6366 Update resources to use new branch name
  README.md
  docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js
  docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
  python/scripts/wavsep/wavsep-1.5-ZAP-weekly-RB-H-M.html
  python/scripts/wavsep/wavsep-1.5-ZAP-weekly-RB-I-M.html
  python/scripts/wavsep/wavsep-1.5-ZAP-weekly-RB-M-M.html
  python/scripts/wavsep/wavsep.py
  zap/src/main/dist/scripts/templates/httpsender/AddZapHeader.js
  zap/src/main/dist/scripts/templates/httpsender/HttpSender default template.js
  zap/src/main/dist/scripts/templates/variant/Input Vector default template.js
Labels: Type-Task

#6369 Update javadoc badge for 2.10.0
  README.md
Labels: Type-Task

#6370 Fix exception when checking for breakpoints
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakpointMessageHandler2.java
  zap/src/test/java/org/zaproxy/zap/extension/brk/BreakpointMessageHandler2UnitTest.java
Labels: bug

#6373 Include prod version of webswing if the req token is supplied
  .github/workflows/release-weekly-docker.yml
  docker/CHANGELOG.md
  docker/Dockerfile-weekly
Labels: Docker
