Repository zaproxy/zaproxy, pull requests merged in 2020-01, with the labels that each got.

#5779 MacOS DMG - switch back to HFS+
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
Labels: enhancement

#5782 Update default user agent
  zap/src/main/dist/xml/common-user-agents.txt
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/parosproxy/paros/network/ConnectionParam.java
Labels: enhancement

#5783 Disable JAR caching by default
  zap/src/main/java/org/zaproxy/zap/ZAP.java
Labels: Usability, bug

#5780 Don't display messages when deleting them
  zap/src/main/java/org/parosproxy/paros/extension/history/ExtensionHistory.java
  zap/src/main/java/org/parosproxy/paros/extension/history/HistoryTable.java
  zap/src/main/java/org/parosproxy/paros/extension/history/LogPanel.java
  zap/src/main/java/org/zaproxy/zap/view/table/HistoryReferencesTable.java
Labels: Component-UI, Usability, bug

#5785 Add tooltip listing all proxies to the footer Primary Proxy label
  zap/src/main/java/org/parosproxy/paros/view/MainFooterPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/ExtensionProxies.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/ProxiesParamProxy.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Component-UI, enhancement

#5787 Set latest version to default config
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/resources/org/zaproxy/zap/resources/config.xml
  zap/src/test/java/org/parosproxy/paros/ConstantUnitTest.java
Labels: Type-Task

#5793 Update version
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/parosproxy/paros/control/Proxy.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyServer.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/parosproxy/paros/extension/Extension.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionAdaptor.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionHookMenu.java
  zap/src/main/java/org/parosproxy/paros/network/HttpHeader.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/parosproxy/paros/view/MainFooterPanel.java
  zap/src/main/java/org/parosproxy/paros/view/SiteMapPanel.java
  zap/src/main/java/org/zaproxy/zap/control/AddOn.java
  zap/src/main/java/org/zaproxy/zap/control/AddOnRunIssuesUtils.java
  zap/src/main/java/org/zaproxy/zap/control/BaseZapAddOnXmlData.java
  zap/src/main/java/org/zaproxy/zap/control/ZapAddOnXmlFile.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiElement.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiImplementor.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiParameter.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/FilterMessageTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/FilterPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScriptsActiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/filters/FilterResult.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanData.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptVars.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupContextTreeMenu.java
  zap/src/main/java/org/zaproxy/zap/model/Context.java
  zap/src/main/java/org/zaproxy/zap/session/ScriptBasedSessionManagementMethodType.java
  zap/src/main/java/org/zaproxy/zap/utils/ThreadUtils.java
  zap/src/main/java/org/zaproxy/zap/view/AbstractContextPropertiesPanel.java
  zap/src/main/java/org/zaproxy/zap/view/table/HistoryReferencesTable.java
  zap/zap.gradle.kts
Labels: Type-Task

#5795 Handle quoted URL in meta refresh
  zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderHtmlParserUnitTest.java
  zap/src/test/resources/org/zaproxy/zap/spider/parser/html/MetaElementsSpiderHtmlParser.html
Labels: enhancement

#5794 Correct MailTo pattern for RegexAutoTagScanner
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/resources/org/zaproxy/zap/resources/config.xml
Labels: bug

#5797 Remove local code of conduct
  CODE_OF_CONDUCT.md
Labels: Type-Task

#5801 Changed to use zaproxy.org
  .github/ISSUE_TEMPLATE/Bug_report.md
  CONTRIBUTING.md
  README.md
  buildSrc/src/main/kotlin/org/zaproxy/zap/publish.gradle.kts
  php/api/zapv2/README.md
  php/api/zapv2/composer.json
  python/scripts/watcher/watcher.py
  python/scripts/wavsep/wavsep.py
  zap/src/main/dist/README
  zap/src/main/dist/README.weekly
  zap/src/main/dist/lang/Messages_ar_SA.properties
  zap/src/main/dist/lang/Messages_az_AZ.properties
  zap/src/main/dist/lang/Messages_bn_BD.properties
  zap/src/main/dist/lang/Messages_bs_BA.properties
  zap/src/main/dist/lang/Messages_ceb_PH.properties
  zap/src/main/dist/lang/Messages_da_DK.properties
  zap/src/main/dist/lang/Messages_de_DE.properties
  zap/src/main/dist/lang/Messages_el_GR.properties
  zap/src/main/dist/lang/Messages_es_ES.properties
  zap/src/main/dist/lang/Messages_fa_IR.properties
  zap/src/main/dist/lang/Messages_fil_PH.properties
  zap/src/main/dist/lang/Messages_fr_FR.properties
  zap/src/main/dist/lang/Messages_ha_HG.properties
  zap/src/main/dist/lang/Messages_he_IL.properties
  zap/src/main/dist/lang/Messages_hi_IN.properties
  zap/src/main/dist/lang/Messages_hr_HR.properties
  zap/src/main/dist/lang/Messages_hu_HU.properties
  zap/src/main/dist/lang/Messages_id_ID.properties
  zap/src/main/dist/lang/Messages_it_IT.properties
  zap/src/main/dist/lang/Messages_ja_JP.properties
  zap/src/main/dist/lang/Messages_ko_KR.properties
  zap/src/main/dist/lang/Messages_mk_MK.properties
  zap/src/main/dist/lang/Messages_ms_MY.properties
  zap/src/main/dist/lang/Messages_nb_NO.properties
  zap/src/main/dist/lang/Messages_nl_NL.properties
  zap/src/main/dist/lang/Messages_pcm_NG.properties
  zap/src/main/dist/lang/Messages_pl_PL.properties
  zap/src/main/dist/lang/Messages_pt_BR.properties
  zap/src/main/dist/lang/Messages_pt_PT.properties
  zap/src/main/dist/lang/Messages_ro_RO.properties
  zap/src/main/dist/lang/Messages_ru_RU.properties
  zap/src/main/dist/lang/Messages_si_LK.properties
  zap/src/main/dist/lang/Messages_sk_SK.properties
  zap/src/main/dist/lang/Messages_sl_SI.properties
  zap/src/main/dist/lang/Messages_sq_AL.properties
  zap/src/main/dist/lang/Messages_sr_CS.properties
  zap/src/main/dist/lang/Messages_sr_SP.properties
  zap/src/main/dist/lang/Messages_tr_TR.properties
  zap/src/main/dist/lang/Messages_uk_UA.properties
  zap/src/main/dist/lang/Messages_ur_PK.properties
  zap/src/main/dist/lang/Messages_vi_VN.properties
  zap/src/main/dist/lang/Messages_yo_NG.properties
  zap/src/main/dist/lang/Messages_zh_CN.properties
  zap/src/main/installer/zap.install4j
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
  zap/src/main/java/org/zaproxy/zap/view/AboutPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5803 Do not require the user password through the API
  zap/src/main/java/org/zaproxy/zap/authentication/UsernamePasswordAuthenticationCredentials.java
Labels: Component-API, bug

#5805 Update add-ons for 2.9.0
  zap/src/main/add-ons.txt
Labels: Type-Task

#5810 Fix broken image
  README.md
Labels: Type-Task

#5811 Update snap for 2.9.0
  snap/snapcraft.yaml
Labels: Type-Task

#5812 Update Mac JRE
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
Labels: Type-Task

#5817 Updated javadoc badge
  README.md
Labels: Type-Task

#5820 Set locale/lang to use UTF-8 in Docker images
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task

#5822 Define community script passive scan ids
  docs/scanners.md
Labels: Type-Task

#5823 Create release_tracker.md
  docs/templates/release_tracker.md
Labels: Type-Task

#5827 More hints about not raising issues for questions
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: Type-Task

#5814 Offer a table based on kind of alert
  zap/src/main/resources/org/zaproxy/zap/resources/xml/report.html.xsl
  zap/src/main/resources/org/zaproxy/zap/resources/xml/report.md.xsl
Labels: Type-Task
