Repository zaproxy/zaproxy, pull requests merged in 2020-05, with the labels that each got.

#5956 Typo Correction
  README.md
Labels: Type-Task

#5973 added known csrf token for pfsense
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/AntiCsrfParam.java
Labels: enhancement

#5965 Add host, path and query columns to the history table
  zap/src/main/java/org/parosproxy/paros/extension/history/HistoryTable.java
  zap/src/main/java/org/parosproxy/paros/extension/history/HistoryTableModel.java
  zap/src/main/java/org/zaproxy/zap/view/table/AbstractHistoryReferencesTableEntry.java
  zap/src/main/java/org/zaproxy/zap/view/table/AbstractHistoryReferencesTableModel.java
  zap/src/main/java/org/zaproxy/zap/view/table/DefaultHistoryReferencesTableEntry.java
  zap/src/main/java/org/zaproxy/zap/view/table/HistoryReferencesTableModel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5974 Update scanners.md for JWT Scanner addon
  docs/scanners.md
Labels: Type-Task

#5977 Remove python2 pip from docker images
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task

#5975 Alert API: Bulk Change Confidence or Risk - Fixes 5845
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertAPI.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#5980 Add test for WwwFormTokenMaker
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMakerUnitTest.java
Labels: Type-Task

#5979 Make python command use Python 3 in Docker images
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task

#5983 Correct command in Docker files
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task

#5984 Relocate WwwFormTokenMaker lexer file
  zap/src/main/flex/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.flex
Labels: Type-Task

#5986 Add tasks to generate JFlex TokenMakers
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/zaproxy/zap/tasks/BuildException.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/JFlexGenerator.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/JFlexToRstaTokenMaker.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/jflex.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/spotless.gradle.kts
  zap/src/main/flex/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.flex
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.java
  zap/zap.gradle.kts
Labels: Type-Task

#5989 Reserve ID for Retire JS add-on
  docs/scanners.md
Labels: Type-Task

#5991 Hook HttpSenderListener when installing add-ons
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
Labels: bug

#5992 Change WwwFormTokenMaker to continue highlighting
  zap/src/main/flex/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.flex
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.java
  zap/src/test/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMakerUnitTest.java
Labels: Type-Task

#5993 Correct extraction of the add-on ID
  zap/src/main/java/org/zaproxy/zap/control/AddOn.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnUnitTest.java
Labels: Type-Task

#5994 Include Common Library add-on in weekly releases
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#5998 Do not delete add-on data dir if not empty
  zap/src/main/java/org/zaproxy/zap/control/AddOnInstaller.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnInstallerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnTestUtils.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnUnitTest.java
Labels: Type-Task

#5997 Reduce code duplication in Scanner
  zap/src/main/java/org/parosproxy/paros/core/scanner/Scanner.java
Labels: Type-Task

#5995 Add "retire" and "encoder" addons to weekly
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/ExtensionEncoder2.java
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#5999 Update docker stable to Ubuntu 20.04
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task

#6004 Expose add-on's release date
  zap/src/main/java/org/zaproxy/zap/control/AddOn.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnCollectionUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnUnitTest.java
Labels: Type-Task

#6009 Ensure scripts loaded from config have engine
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptAPI.java
Labels: Type-Task

#6011 encoder2: Deprecate and address dependence
  zap/src/main/java/org/parosproxy/paros/extension/encoder/Base64.java
  zap/src/main/java/org/parosproxy/paros/extension/encoder/Encoder.java
  zap/src/main/java/org/zaproxy/zap/control/CoreFunctionality.java
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/AddOnsTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/EncodeDecodeDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/EncodeDecodeParam.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/EncodeDecodeParamPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/ExtensionEncoder2.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/PopupEncoder2Menu.java
  zap/src/main/java/org/zaproxy/zap/utils/HarUtils.java
  zap/src/main/java/org/zaproxy/zap/utils/ViewState.java
Labels: Type-Task
