Repository zaproxy/zaproxy, pull requests merged in 2020-10, with the labels that each got.

#6207 Add option to delete site nodes from Search tab
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuPurgeSites.java
  zap/src/main/java/org/zaproxy/zap/extension/search/SearchResultsTableModel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#6215 Fix title caps and typo
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#6209 Add gradle dependency check task & upgrade dependencies
  LEGALNOTICE.md
  build.gradle.kts
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScanProgressDialog.java
  zap/zap.gradle.kts
Labels: Type-Task

#6210 Test extraction of anti-csrf tokens from response
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  zap/src/test/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRFUnitTest.java
Labels: Type-Task

#6225 Use icon for authentication requests
  zap/src/main/java/org/zaproxy/zap/view/HrefTypeInfo.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#6224 Use user's context during authentication
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  zap/src/test/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodTypeUnitTest.java
Labels: Type-Task

#6221 Cope with session mgmt type not present
  zap/src/main/java/org/zaproxy/zap/extension/sessions/ExtensionSessionManagement.java
  zap/src/test/java/org/zaproxy/zap/extension/sessions/ExtensionSessionManagementUnitTest.java
Labels: Type-Task

#6228 Update Log4j to 2.x
  LEGALNOTICE.md
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/zaproxy/zap/CommandLineBootstrap.java
  zap/src/main/java/org/zaproxy/zap/DaemonBootstrap.java
  zap/src/main/java/org/zaproxy/zap/GuiBootstrap.java
  zap/src/main/java/org/zaproxy/zap/ZAP.java
  zap/src/main/java/org/zaproxy/zap/ZapBootstrap.java
  zap/src/main/java/org/zaproxy/zap/extension/log4j/ExtensionLog4j.java
  zap/src/main/java/org/zaproxy/zap/extension/log4j/ZapOutputWriter.java
  zap/src/main/java/org/zaproxy/zap/view/SplashScreen.java
  zap/src/main/resources/log4j2.properties
  zap/src/main/resources/log4j2.system.properties
  zap/src/main/resources/org/zaproxy/zap/resources/log4j.properties
  zap/src/main/resources/org/zaproxy/zap/resources/log4j2-home.properties
  zap/src/test/java/org/parosproxy/paros/ConstantUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/PluginTestUtils.java
  zap/src/test/java/org/zaproxy/zap/WithConfigsTest.java
  zap/src/test/java/org/zaproxy/zap/ZAPUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/ExtensionFactoryUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRFUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/APIUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/ext/ExtensionParamUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/log4j/ExtensionLog4jUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/RegexAutoTagScannerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/StatsPassiveScannerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/ValidateTranslatedVulnerabilitiesFilesUnitTest.java
  zap/src/test/java/org/zaproxy/zap/network/HttpBodyTestUtils.java
  zap/src/test/java/org/zaproxy/zap/network/HttpResponseBodyUnitTest.java
  zap/src/test/java/org/zaproxy/zap/resources/Log4jBootstrapConfigurationTest.java
  zap/src/test/java/org/zaproxy/zap/resources/Log4jHomeConfigurationTest.java
  zap/src/test/java/org/zaproxy/zap/spider/URLCanonicalizerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/filters/DefaultFetchFilterUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/filters/DefaultParseFilterUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/filters/HttpPrefixFetchFilterUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderHtmlFormParserUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderHtmlParserUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderRedirectParserUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderRobotstxtParserUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderSitemapXMLParserUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderTextParserUnitTest.java
  zap/src/test/java/org/zaproxy/zap/testutils/Log4jTestAppender.java
  zap/src/test/java/org/zaproxy/zap/testutils/TestUtils.java
  zap/src/test/java/org/zaproxy/zap/utils/MessagesLocaleUnitTest.java
  zap/src/test/java/org/zaproxy/zap/view/SplashScreenUnitTest.java
  zap/src/test/resources/log4j2-test.properties
  zap/zap.gradle.kts
Labels: Type-Task

#6233 fixed capitalization and typo
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#6235 workflows: Address set-env deprecation
  .github/workflows/release-main-docker.yml
  .github/workflows/release-weekly-docker.yml
Labels: Type-Task

#6232 Custom Pages add initial unittests
  zap/src/main/java/org/zaproxy/zap/extension/custompages/CustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/CustomPageMatcherLocation.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/DefaultCustomPage.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AbstractPluginUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/custompages/CustomPageMatcherLocationUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/custompages/CustomPageUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/custompages/DefaultCustomPageUnitTest.java
Labels: Type-Task

#6239 #2000 : Fixed Capitalization
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#6237 Added Content-Type application/health+json to list of expected.
  docker/CHANGELOG.md
  docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
Labels: Docker

#6226 Allow to define the maximum body size to passive scan
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanParam.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScannerOptionsPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: enhancement

#6242 Be more lenient when importing a context
  zap/src/main/java/org/parosproxy/paros/model/Model.java
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/zaproxy/zap/extension/authentication/ExtensionAuthentication.java
  zap/src/main/java/org/zaproxy/zap/extension/authorization/ExtensionAuthorization.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ExtensionForcedUser.java
  zap/src/main/java/org/zaproxy/zap/model/StandardParameterParser.java
  zap/src/test/java/org/parosproxy/paros/model/SessionUnitTest.java
  zap/src/test/java/org/zaproxy/zap/WithConfigsTest.java
  zap/src/test/java/org/zaproxy/zap/extension/authentication/ExtensionAuthenticationUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/authorization/ExtensionAuthorizationUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/forceduser/ExtensionForcedUserUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/StandardParameterParserUnitTest.java
Labels: Type-Task

#6243 Restore active scanning everything in scope
  zap/src/main/java/org/zaproxy/zap/model/StructuralSiteNode.java
  zap/src/main/java/org/zaproxy/zap/model/Target.java
  zap/src/test/java/org/zaproxy/zap/model/StructuralSiteNodeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/TargetUnitTest.java
Labels: Type-Task

#6088 Add partial CSRF token search
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/AntiCsrfParam.java
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/OptionsAntiCsrfPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRFUnitTest.java
Labels: Type-Task

#6251 Address random test failures
  zap/src/main/java/org/zaproxy/zap/session/ScriptBasedSessionManagementMethodType.java
  zap/src/test/java/org/zaproxy/zap/extension/sessions/ExtensionSessionManagementUnitTest.java
  zap/src/test/java/org/zaproxy/zap/utils/PausableScheduledThreadPoolExecutorUnitTest.java
Labels: Type-Task

#6249 Add tests for HostProcess
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/HostProcessUnitTest.java
Labels: Type-Task

#6250 Restore and hardcode error messages in Base64
  zap/src/main/java/org/parosproxy/paros/extension/encoder/Base64.java
Labels: Type-Task

#6253 Add tests for BreakpointMessageHandler2
  zap/src/test/java/org/zaproxy/zap/extension/brk/BreakpointMessageHandler2UnitTest.java
Labels: Type-Task

#6202 Add support for dynamic Look and Feel switching
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsParamView.java
  zap/src/main/java/org/parosproxy/paros/view/MainFrame.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/HttpPanelSyntaxHighlightTextArea.java
  zap/src/main/java/org/zaproxy/zap/utils/ZapLabel.java
  zap/src/main/java/org/zaproxy/zap/view/TabbedPanel2.java
  zap/src/main/java/org/zaproxy/zap/view/widgets/PopupButton.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/resources/resource/icon/fugue/ui-color-picker-switch.png
Labels: Type-Task

#6257 Upgrade to FlatLaf 0.43
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6259 Add domxss add-on to weekly release
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#6258 Address some glitches when changing look and feel
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsParamView.java
  zap/src/main/java/org/parosproxy/paros/view/AbstractParamContainerPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/help/ExtensionHelp.java
  zap/src/main/java/org/zaproxy/zap/view/MainToolbarPanel.java
Labels: Type-Task

#6260 Release actions - stop using docker
  .github/workflows/release-main-version.yml
  .github/workflows/release-weekly.yml
Labels: Type-Task

#6261 Test FilterResult
  zap/src/test/java/org/zaproxy/zap/extension/ascan/filters/FilterResultUnitTest.java
Labels: Type-Task

#6236 #5898 added import from file button to regular expression panels
  zap/src/main/java/org/zaproxy/zap/view/MultipleRegexesOptionsPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#6262 ScanProgressDialog - Set fewer elements with hardcoded colors/attributes
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScanProgressDialog.java
Labels: Type-Task

#6268 Fix Report Write Failure When Path Contained '#'
  zap/src/main/java/org/parosproxy/paros/extension/report/ReportGenerator.java
  zap/src/test/java/org/parosproxy/paros/extension/report/ReportGeneratorUnitTest.java
Labels: Type-Task
