Repository zaproxy/zaproxy, pull requests merged in 2021-08, with the labels that each got.

#6718 Adding FileUpload Scan Rule
  docs/scanners.md
Labels: Type-Task

#6720 Encode parameters when replacing in form auth data
  zap/src/main/java/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodType.java
Labels: Component-UI, bug

#6705 Remove Paros Reports
  zap/src/main/java/org/parosproxy/paros/extension/report/ExtensionReport.java
  zap/src/main/java/org/parosproxy/paros/extension/report/ReportGenerator.java
  zap/src/main/java/org/parosproxy/paros/extension/report/ReportLastScan.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/parosproxy/paros/extension/report/ReportGeneratorUnitTest.java
  zap/zap.gradle.kts
Labels: enhancement

#6724 Add action to build live docker release
  .github/workflows/release-live-docker.yml
Labels: Docker

#6702 Set X-ZAP-Scan-ID header in the right HttpMessage instance.
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AbstractPluginUnitTest.java
Labels: Type-Task

#6743 Action for integration tests
  .github/workflows/run-integration-tests.yml
  docker/CHANGELOG.md
  docker/integration_tests/baseline_tests.sh
  docker/zap-baseline.py
Labels: Docker

#6744 Added security policy
  SECURITY.md
Labels: Type-Task

#6745 Baseline - use AF for * OUTOFSCOPE config settings
  docker/CHANGELOG.md
  docker/integration_tests/baseline_tests.sh
  docker/integration_tests/configs/baseline3.conf
  docker/integration_tests/results/baseline3.out
  docker/zap-baseline.py
  docker/zap_common.py
Labels: enhancement, Docker

#6748 Add translatable elements for vulnerabilities.xml
  zap/gradle/crowdin.yml
Labels: Type-Task

#6750 Normalise line endings of bat file
  gradlew.bat
Labels: Type-Task

#6753 Update Host header in place
  zap/src/main/java/org/apache/commons/httpclient/HttpMethodBase.java
  zap/src/test/java/org/apache/commons/httpclient/HttpMethodBaseUnitTest.java
Labels: bug

#6759 Guard against extensions' errors
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  zap/src/test/java/org/parosproxy/paros/extension/ExtensionLoaderUnitTest.java
Labels: Type-Task

#6760 Add OAST Add-on to Weekly Release
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#6763 Register IDs for Community Scripts active scan rules
  docs/scanners.md
Labels: Type-Task

#6766 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6768 Add install add-ons integration test
  .github/workflows/run-integration-tests.yml
  docker/integration_tests/install_tests.sh
Labels: Type-Task

#6771 Rely on default JaCoCo version
  zap/zap.gradle.kts
Labels: Type-Task

#6772 Remove unnecessary code comments
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosDatabase.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableAlert.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableContext.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableParam.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableScan.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableSession.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableSessionUrl.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableStructure.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableTag.java
  zap/src/main/java/org/zaproxy/zap/db/sql/HsqldbDatabase.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlDatabase.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableAlert.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableContext.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableHistory.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableParam.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableScan.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableSession.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableSessionUrl.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableStructure.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableTag.java
  zap/src/main/java/org/zaproxy/zap/users/User.java
Labels: Type-Task

#6774 Docker: Do not carry over any config settings
  docker/integration_tests/baseline_tests.sh
Labels: Type-Task, Docker

#6776 Use only zapbot credentials in release workflows
  .github/workflows/handle-release.yml
  .github/workflows/prepare-release-main-version.yml
  .github/workflows/release-main-version.yml
  .github/workflows/release-weekly.yml
  buildSrc/src/main/java/org/zaproxy/zap/tasks/CreateGitHubRelease.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/CreateTagAndGitHubRelease.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
Labels: Type-Task

#6778 Reserving a scanner ID for Spring Actuator Scanner
  docs/scanners.md
Labels: Type-Task

#6782 Add missing dependency for japicmp
  buildSrc/build.gradle.kts
Labels: Type-Task
