Repository zaproxy/zaproxy, pull requests merged in 2021-10, with the labels that each got.

#6843 Do not init extension's view if there's none
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/test/java/org/parosproxy/paros/extension/ExtensionLoaderUnitTest.java
Labels: bug

#6835 Active Scan stats
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/PluginStats.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Scanner.java
Labels: enhancement

#6841 Use assertThrows in ApiUtilsUnitTest
  zap/src/test/java/org/zaproxy/zap/utils/ApiUtilsUnitTest.java
Labels: Type-Task

#6836 Passive Scan stats
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
Labels: enhancement

#6840 Break stats
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanelToolbarFactory.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakpointMessageHandler2.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/ExtensionBreak.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/impl/http/HttpBreakpointManagementDaemonImpl.java
Labels: enhancement

#6837 API stats
  zap/src/main/java/org/zaproxy/zap/extension/api/API.java
Labels: enhancement

#6844 Detect if running in WebSwing
  zap/src/main/java/org/parosproxy/paros/Constant.java
Labels: enhancement

#6838 Scripts stats
  zap/src/main/java/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptsCache.java
  zap/src/main/java/org/zaproxy/zap/session/ScriptBasedSessionManagementMethodType.java
Labels: enhancement

#6846 Update README.md - Make javadoc badge dynamic
  README.md
Labels: Type-Task

#6848 Fix NPE when starting ZAP with add-on issues
  zap/src/main/java/org/zaproxy/zap/control/AddOnLoader.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnLoaderUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnTestUtils.java
Labels: bug, weekly

#6849 Update JRE bundled in macOS package
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
Labels: Type-Task

#6852 Fix baseline failure if a RO mapped dir used
  docker/CHANGELOG.md
  docker/zap-baseline.py
Labels: Type-Task

#6854 Update user agents
  zap/src/main/dist/xml/common-user-agents.txt
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/parosproxy/paros/network/ConnectionParam.java
Labels: enhancement
