Repository zaproxy/zaproxy, pull requests merged in 2021-04, with the labels that each got.

#6507 Fix unit tests failing randomly due to files not closed by Files.list()
  zap/src/test/java/org/parosproxy/paros/ConstantUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnInstallerUnitTest.java
Labels: Type-Task

#6513 Removed hardcoded sizes of components of Manage Tags dialog
  zap/src/main/java/org/zaproxy/zap/extension/history/ManageTagsDialog.java
Labels: Type-Task

#6514 Dependency Updates
  LEGALNOTICE.md
  build.gradle.kts
  zap/zap.gradle.kts
Labels: Type-Task

#6508 Detect WebSocket upgrade messages having multiple Connection directives
  zap/src/main/java/org/parosproxy/paros/network/HttpMessage.java
  zap/src/test/java/org/parosproxy/paros/network/HttpMessageUnitTest.java
Labels: bug

#6525 ContentMatcher Remove Unused Private Constants
  zap/src/main/java/org/zaproxy/zap/utils/ContentMatcher.java
Labels: Type-Task

#6527 Find Dialog javaDoc Tweaks
  zap/src/main/java/org/parosproxy/paros/view/FindDialog.java
Labels: Type-Task

#6531 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6526 Export Menu Tweaks
  zap/src/main/java/org/parosproxy/paros/extension/history/PopupMenuExportMessage.java
  zap/src/main/java/org/parosproxy/paros/extension/history/PopupMenuExportResponse.java
Labels: Type-Task

#6535 Ignore JVM crash logs
  .gitignore
Labels: Type-Task

#6534 Remove Spotless exclusion no longer needed
  buildSrc/src/main/kotlin/org/zaproxy/zap/spotless.gradle.kts
Labels: Type-Task

#6529 PolicyPassiveScanPanel - Clean Code Tweaks
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PolicyPassiveScanPanel.java
Labels: Type-Task

#6530 Variant Tweaks - Clean Code
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantAbstractRPCQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantCookie.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantDirectWebRemotingQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantHeader.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantJSONQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantODataFilterQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantODataIdQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantURLPath.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantURLQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantUserDefined.java
Labels: Type-Task

#6528 MainMenuBar JavaDoc Tweaks
  zap/src/main/java/org/parosproxy/paros/view/MainMenuBar.java
Labels: Type-Task

#6541 Show CONNECT request again in History tab
  zap/src/main/java/org/zaproxy/zap/view/table/DefaultHistoryReferencesTableEntry.java
  zap/src/test/java/org/zaproxy/zap/view/table/DefaultHistoryReferencesTableEntryUnitTest.java
Labels: Type-Task

#6540 Stop and destroy extensions on add-on uninstall
  zap/src/main/java/org/parosproxy/paros/extension/Extension.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/test/java/org/parosproxy/paros/extension/ExtensionLoaderUnitTest.java
Labels: Type-Task

#6539 Allow to scan null JSON values
  zap/src/main/java/org/parosproxy/paros/core/scanner/ScannerParam.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantJSONQuery.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/OptionsVariantPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/VariantFactory.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/parosproxy/paros/core/scanner/ScannerParamUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantJSONQueryUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/ascan/VariantFactoryUnitTest.java
Labels: Type-Task

#6542 Update HSQLDB
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6545 Remove library from LEGALNOTICE
  LEGALNOTICE.md
Labels: Type-Task

#6544 Address deprecation with Java 16
  zap/src/main/java/ch/csnc/extension/httpclient/SSLContextManager.java
Labels: Type-Task

#6546 Address test failures in newer Java versions
  LEGALNOTICE.md
  zap/src/test/java/org/zaproxy/zap/VerifyScriptTemplates.java
  zap/zap.gradle.kts
Labels: Type-Task

#6557 fix: HTTP Panels Font setting for dark LaFs (Theme)
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/HttpPanelSyntaxHighlightTextArea.java
Labels: Component-UI, bug

#6553 Use try-with-resources for a better code
  zap/src/main/java/org/parosproxy/paros/extension/report/ReportGenerator.java
  zap/src/main/java/org/zaproxy/zap/db/sql/HsqldbDatabaseServer.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/Downloader.java
  zap/src/main/java/org/zaproxy/zap/extension/script/DefaultEngineWrapper.java
  zap/src/main/java/org/zaproxy/zap/utils/ViewState.java
Labels: Type-Task

#6564 Fix scrolling in Sites tab with FlatLaf L&F
  zap/src/main/java/org/zaproxy/zap/view/ContextsSitesPanel.java
Labels: Type-Task

#6559 Added menu item to directly add base URL to context
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/ExtensionStdMenus.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupMenuItemContextSiteInclude.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupMenuItemIncludeSiteInContext.java
  zap/src/main/java/org/zaproxy/zap/view/popup/PopupMenuItemIncludeInContext.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/stdmenu/PopupMenuItemIncludeSiteInContextUnitTest.java
Labels: Type-Task

#6565 improvement: HTTP Panels Font setting for dark LaFs (Theme)
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/HttpPanelSyntaxHighlightTextArea.java
Labels: Type-Task

#6566 fix: Test package name for PopupMenuItemIncludeSiteInContext
  zap/src/test/java/org/zaproxy/zap/extension/stdmenus/PopupMenuItemIncludeSiteInContextUnitTest.java
Labels: Type-Task

#6567 Do not check for null engine in visibility check
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptEngineWrapper.java
Labels: Type-Task

#6568 Allow to use more memory for weekly builds
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
Labels: Type-Task

#6570 fix: Disable FlatLaf native decorations on windows
  zap/src/main/java/org/zaproxy/zap/GuiBootstrap.java
Labels: Type-Task

#6571 Remove unnecessary todo
  zap/src/main/java/org/zaproxy/zap/extension/option/OptionsLocalePanel.java
Labels: Type-Task

#6560 Update Gradle to 7.0
  .github/workflows/release-main-version.yml
  .github/workflows/release-weekly.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/installers.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/spotless.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/test.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  zap/zap.gradle.kts
Labels: Type-Task

#6575 Add exceptions used by URI
  zap/src/main/java/org/apache/commons/httpclient/HttpException.java
  zap/src/main/java/org/apache/commons/httpclient/URIException.java
Labels: Type-Task
