Repository zaproxy/zaproxy, pull requests merged in 2021-12, with the labels that each got.

#6866 Breakpoints Option String Tweaks
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task, waiting-for:pr-author

#6950 Use Network add-on to manage server certificates
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyThread.java
  zap/src/main/java/org/parosproxy/paros/network/SSLConnector.java
  zap/src/main/java/org/parosproxy/paros/security/CachedSslCertifificateServiceImpl.java
  zap/src/main/java/org/parosproxy/paros/security/CertData.java
  zap/src/main/java/org/parosproxy/paros/security/MissingRootCertificateException.java
  zap/src/main/java/org/parosproxy/paros/security/SslCertificateService.java
  zap/src/main/java/org/parosproxy/paros/security/SslCertificateServiceImpl.java
  zap/src/main/java/org/zaproxy/zap/control/CoreFunctionality.java
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/DynSSLParam.java
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/DynamicSSLPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/DynamicSSLWelcomeDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/ExtensionDynSSL.java
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/SslCertificateUtils.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/dynssl/SslCertificateUtilsUnitTest.java
  zap/zap.gradle.kts
Labels: enhancement

#6956 chore: Update scanners.md with XFO changes
  docs/scanners.md
Labels: Type-Task

#6962 Update RSyntaxTextArea and FlatLaf
  LEGALNOTICE.md
  buildSrc/src/main/java/org/zaproxy/zap/tasks/JFlexToRstaTokenMaker.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.java
  zap/zap.gradle.kts
Labels: Type-Task

#6965 Update dependency
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6966 Prepare 2.11.1 release
  LEGALNOTICE.md
  zap/src/main/add-ons.txt
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/zap.gradle.kts
Labels: Type-Task

#6967 Update add-ons for 2.11.1
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  zap/src/main/add-ons.txt
Labels: Type-Task

#6968 Fix typo in add-ons file
  zap/src/main/add-ons.txt
Labels: Type-Task

#6969 Update help add-on
  zap/src/main/add-ons.txt
Labels: Type-Task

#6970 Correct copy of add-ons in stable Docker image
  docker/Dockerfile-stable
Labels: Type-Task

#6971 Correct copy of add-ons in bare Docker image
  docker/Dockerfile-bare
Labels: Type-Task

#6972 Merge release 2.11.1 into main
  zap/src/main/add-ons.txt
  zap/src/main/java/org/parosproxy/paros/Constant.java
Labels: Type-Task

#6973 Update Docker integration test results
  docker/integration_tests/results/baseline1.out
  docker/integration_tests/results/baseline1b.out
  docker/integration_tests/results/baseline2.out
  docker/integration_tests/results/baseline2b.out
  docker/integration_tests/results/baseline3.out
  docker/integration_tests/results/baseline4.out
Labels: Type-Task

#6974 Update ZAP version in snap
  snap/snapcraft.yaml
Labels: Type-Task

#6975 Reserve ID for Log4Shell Scan Rule
  docs/scanners.md
Labels: Type-Task

#6979 chore: Upgrade Log4j to 2.16.0
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6983 Docker: Upgrade to WebSwing 21.2.4
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Docker

#6988 chore: Upgrade Log4j to 2.17.0
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6995 Update Webswing
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task

#7001 Replace Travis Badge
  README.md
Labels: Type-Task
