Repository zaproxy/zaproxy, pull requests merged in 2021-11, with the labels that each got.

#6902 Docker: Automation Framework plan tests
  .github/workflows/run-integration-tests.yml
  docker/integration_tests/af_context_tests.sh
  docker/integration_tests/af_plan_tests.sh
  docker/integration_tests/configs/plans/jigsaw-basic-user.yaml
Labels: Type-Task, Docker

#6904 Docker: fixed issue with automation updates
  docker/CHANGELOG.md
  docker/zap-baseline.py
  docker/zap_common.py
Labels: Docker

#6888 chore: Update gradle to 7.2
  buildSrc/src/main/java/org/zaproxy/zap/tasks/JFlexGenerator.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/installers.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/test.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: Type-Task

#6913 Docker: Fix integration tests
  docker/integration_tests/af_context_tests.sh
  docker/integration_tests/af_plan_tests.sh
  docker/integration_tests/baseline_tests.sh
  docker/integration_tests/results/baseline1.out
  docker/integration_tests/results/baseline1b.out
  docker/integration_tests/results/baseline2.out
  docker/integration_tests/results/baseline2b.out
  docker/integration_tests/results/baseline3.out
  docker/integration_tests/results/baseline4.out
Labels: Docker

#6920 Add Sonarcloud badge
  README.md
Labels: Type-Task

#6925 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6924 Address build deprecations
  zap/zap.gradle.kts
Labels: Type-Task

#6927 Correct CFU log messages
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Type-Task

#6932 Use new callhome add-on for CFU requests
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/zaproxy/zap/control/ControlOverrides.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  zap/src/main/weekly-add-ons.json
Labels: enhancement

#6933 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6940 Report size for installed add-ons
  zap/src/main/java/org/zaproxy/zap/control/AddOn.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnUnitTest.java
Labels: enhancement

#6941 Expose add-on mandatory state in GUI/API
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/AutoUpdateAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ManageAddOnsDialog.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#6942 Remove parent nodes in param container panel
  zap/src/main/java/org/parosproxy/paros/view/AbstractParamContainerPanel.java
Labels: enhancement, Component-UI, Usability

#6946 Allow to set a certificates service
  zap/src/main/java/org/parosproxy/paros/network/SSLConnector.java
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/ExtensionDynSSL.java
Labels: Type-Task

#6947 Fix webswing detection
  zap/src/main/java/org/parosproxy/paros/Constant.java
Labels: bug

#6949 Deprecate core endpoints related to root CA cert
  zap/src/main/java/org/zaproxy/zap/control/ControlOverrides.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/weekly-add-ons.json
  zap/src/test/java/org/zaproxy/zap/extension/api/CoreAPIUnitTest.java
Labels: enhancement, Component-API

#6954 Ensure certificates service is set always
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/ExtensionDynSSL.java
Labels: Type-Task
