Repository zaproxy/zaproxy, pull requests merged in 2021-07, with the labels that each got.

#6668 Baseline - use AF by default if supported
  docker/CHANGELOG.md
  docker/zap-baseline.py
Labels: Docker

#6675 HistoryReference: Add TYPE_OAST
  zap/src/main/java/org/parosproxy/paros/model/HistoryReference.java
Labels: Type-Task

#6676 Fix typo in ZAP class comment
  zap/src/main/java/org/zaproxy/zap/ZAP.java
Labels: Type-Task

#6679 Docker - user users dir for AF files
  docker/CHANGELOG.md
  docker/zap-baseline.py
Labels: Type-Task

#6681 fix: re-implement lockbot
  .github/lock.yml
  .github/workflows/lock.yml
Labels: Type-Task

#6678 Make EventBus publishers easier to discover
  zap/src/main/java/org/zaproxy/zap/control/CoreFunctionality.java
  zap/src/main/java/org/zaproxy/zap/eventBus/EventBus.java
  zap/src/main/java/org/zaproxy/zap/eventBus/SimpleEventBus.java
  zap/src/test/java/org/zaproxy/zap/eventBus/SimpleEventBusUnitTest.java
Labels: enhancement

#6684 Update lock.yml - Daily Run
  .github/workflows/lock.yml
Labels: Type-Task

#6687 update: scanners.md deprecate Apache Range Header DoS
  docs/scanners.md
Labels: Type-Task

#6690 Reorder multipart injection points
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantMultipartFormParameters.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantMultipartFormParametersUnitTest.java
Labels: Type-Task

#6371 Adding support for handling manipulation of multiple NameValuePairs
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractAppParamPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Variant.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantMultipartFormParameters.java
  zap/src/main/java/org/zaproxy/zap/core/scanner/InputVector.java
  zap/src/main/java/org/zaproxy/zap/core/scanner/InputVectorBuilder.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantMultipartFormParametersUnitTest.java
  zap/zap.gradle.kts
Labels: enhancement

#6698 improve: HttpRequestHeader: now includes svg in isImage()
  zap/src/main/java/org/parosproxy/paros/network/HttpRequestHeader.java
  zap/src/test/java/org/parosproxy/paros/network/HttpRequestHeaderUnitTest.java
Labels: Type-Task

#6692 Avoid setting Request Header Content-length:0 in GET requests
  zap/src/main/java/org/parosproxy/paros/network/HttpRequestHeader.java
  zap/src/test/java/org/parosproxy/paros/network/HttpRequestHeaderUnitTest.java
Labels: Type-Task

#6708 Upload files to Crowdin on release and manually
  .github/workflows/crowdin-upload-files.yml
  .github/workflows/handle-release.yml
  RELEASING.md
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
  zap/gradle/crowdin.yml
  zap/zap.gradle.kts
Labels: Type-Task

#6711 Update webswing to 21.1.3
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Docker, enhancement

#6716 Request ID for CVE-2021-22214 Scanner Script
  docs/scanners.md
Labels: Type-Task
