Repository zaproxy/zaproxy, pull requests merged in 2021-05, with the labels that each got.

#6574 Add text/yaml to expected media-types
  docker/CHANGELOG.md
  docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
Labels: Type-Task

#6576 Set env var when building add-ons for releases
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
Labels: Type-Task

#6580 Update PHP Client API Generator
  php/api/zapv2/.gitignore
  php/api/zapv2/LICENSE
  php/api/zapv2/README.md
  php/api/zapv2/composer.json
  php/api/zapv2/src/Zap/Acsrf.php
  php/api/zapv2/src/Zap/AjaxSpider.php
  php/api/zapv2/src/Zap/Ascan.php
  php/api/zapv2/src/Zap/Authentication.php
  php/api/zapv2/src/Zap/Authorization.php
  php/api/zapv2/src/Zap/Autoupdate.php
  php/api/zapv2/src/Zap/Brk.php
  php/api/zapv2/src/Zap/Context.php
  php/api/zapv2/src/Zap/Core.php
  php/api/zapv2/src/Zap/ForcedUser.php
  php/api/zapv2/src/Zap/HttpSessions.php
  php/api/zapv2/src/Zap/ImportLogFiles.php
  php/api/zapv2/src/Zap/Params.php
  php/api/zapv2/src/Zap/Pnh.php
  php/api/zapv2/src/Zap/Pscan.php
  php/api/zapv2/src/Zap/Reveal.php
  php/api/zapv2/src/Zap/Script.php
  php/api/zapv2/src/Zap/Search.php
  php/api/zapv2/src/Zap/Selenium.php
  php/api/zapv2/src/Zap/SessionManagement.php
  php/api/zapv2/src/Zap/Spider.php
  php/api/zapv2/src/Zap/Stats.php
  php/api/zapv2/src/Zap/Users.php
  php/api/zapv2/src/Zap/Zapv2.php
  zap/src/main/java/org/zaproxy/zap/extension/api/PhpAPIGenerator.java
Labels: Type-Task

#6581 improve: ci workflow add concurrency grouping
  .github/workflows/ci.yml
Labels: Type-Task

#6583 Update PHP Client API Generator
  zap/src/main/java/org/zaproxy/zap/extension/api/PhpAPIGenerator.java
Labels: Type-Task

#6584 Update webswing
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task

#6587 revert: ci workflow concurrency grouping
  .github/workflows/ci.yml
Labels: Type-Task

#6592 Use authority form for CONNECT requests
  zap/src/main/java/org/apache/commons/httpclient/URI.java
  zap/src/main/java/org/parosproxy/paros/network/HttpRequestHeader.java
  zap/src/main/java/org/zaproxy/zap/view/table/DefaultHistoryReferencesTableEntry.java
  zap/src/test/java/org/apache/commons/httpclient/URIUnitTest.java
  zap/src/test/java/org/parosproxy/paros/network/HttpRequestHeaderUnitTest.java
  zap/src/test/java/org/zaproxy/zap/view/table/DefaultHistoryReferencesTableEntryUnitTest.java
Labels: Type-Task

#6464 Fixed parsing of URI upon changing Request method to/from CONNECT in Manual Request Editor
  zap/src/main/java/org/parosproxy/paros/network/HttpMessage.java
  zap/src/test/java/org/parosproxy/paros/network/HttpMessageUnitTest.java
Labels: Type-Task

#6597 Ignore macOS file
  .gitignore
Labels: Type-Task

#6598 Do not require scan rules to implement setParent
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/AntiCsrfDetectScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanData.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/RegexAutoTagScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScanner.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScanTestHelper.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PluginPassiveScannerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScannerUnitTest.java
Labels: enhancement

#6601 Update com.github.tomakehurst:wiremock-jre8 to v2.28.0
  zap/zap.gradle.kts
Labels: Type-Task

#6586 improve: custompages: Address SAST (sonar) findings
  zap/src/main/java/org/zaproxy/zap/extension/custompages/ContextCustomPagePanel.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/CustomPageTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/DefaultCustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/DialogAddCustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/DialogModifyCustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/PopupFlagCustomPageIndicatorMenu.java
  zap/zap.gradle.kts
Labels: Type-Task

#6613 Update PHP Client API Generator
  zap/src/main/java/org/zaproxy/zap/extension/api/PhpAPIGenerator.java
Labels: Type-Task

#6614 Add AWP Identity manager PKCS11 cards (IDEMIA)
  zap/src/main/resources/org/zaproxy/zap/resources/drivers.xml
Labels: enhancement

#6621 Add workflow to update marketplace with weekly
  .github/workflows/handle-release.yml
  buildSrc/src/main/java/org/zaproxy/zap/tasks/HandleWeeklyRelease.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/SendRepositoryDispatch.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/GitHubRepo.kt
  buildSrc/src/main/kotlin/org/zaproxy/zap/GitHubUser.kt
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
Labels: Type-Task

#6623 Create weekly release on workflow dispatch
  .github/workflows/release-weekly.yml
  buildSrc/src/main/java/org/zaproxy/zap/tasks/CreateTagAndGitHubRelease.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
Labels: Type-Task

#6618 chore: Update FLatLaf to 1.2
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6612 Parameterize test in HttpMethodBaseUnitTest
  zap/src/test/java/org/apache/commons/httpclient/HttpMethodBaseUnitTest.java
Labels: Type-Task

#6625 Deprecate core/view/homeDirectory API endpoint
  zap/src/main/java/org/parosproxy/paros/model/OptionsParam.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
Labels: Component-API, Component-UI, enhancement

#6630 Update marketplace with main release
  buildSrc/src/main/java/org/zaproxy/zap/tasks/HandleMainRelease.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
Labels: Type-Task

#6631 Prepare next dev iter on release
  .github/workflows/handle-release.yml
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/zaproxy/zap/tasks/CreatePullRequest.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/PrepareNextDevIter.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
Labels: Type-Task

#6632 Create main release on workflow dispatch
  .github/workflows/release-main-version.yml
  .github/workflows/release-weekly.yml
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
Labels: Type-Task

#6636 Make zapbot auth token available to release tasks
  .github/workflows/release-main-version.yml
  .github/workflows/release-weekly.yml
Labels: Type-Task
