Repository zaproxy/zaproxy, pull requests merged in 2021-02, with the labels that each got.

#6432 WebSwing - add more flexible ZAP options
  docker/CHANGELOG.md
  docker/webswing.config
  docker/zap-webswing.sh
Labels: Docker

#6428 Root Cert Download from Main API Page
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/api/WebUI.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Component-API, enhancement

#6434 Reserving unique ID for CORS active scan rule
  docs/scanners.md
Labels: Type-Task

#6436 encoder: Remove deprecated classes
  zap/src/main/java/org/parosproxy/paros/extension/encoder/Base64.java
  zap/src/main/java/org/parosproxy/paros/extension/encoder/Encoder.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/EncodeDecodeDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/EncodeDecodeParam.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/EncodeDecodeParamPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/ExtensionEncoder2.java
  zap/src/main/java/org/zaproxy/zap/extension/encoder2/PopupEncoder2Menu.java
  zap/zap.gradle.kts
Labels: Type-Task

#6438 Keep state of only break on scope when resetting
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanelToolbarFactory.java
Labels: Type-Task

#6447 Check globally excluded URLs in API scan scripts
  docker/CHANGELOG.md
  docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js
  docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
Labels: Type-Task

#6452 Request Editor: Add shortcut key
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ManualRequestEditorDialog.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/ManualHttpRequestEditorDialog.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#6466 Use Maven Central only
  buildSrc/build.gradle.kts
Labels: Type-Task
