Repository zaproxy/zaproxy, pull requests merged in 2021-01, with the labels that each got.

#6377 Correct build_args
  .github/workflows/release-weekly-docker.yml
Labels: Docker

#6378 Log more details on unknown value in JSON variant
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantJSONQuery.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantJSONQueryUnitTest.java
  zap/src/test/java/org/zaproxy/zap/testutils/Log4jTestAppender.java
Labels: Type-Task

#6383 Fix Docker weekly build
  .github/workflows/release-weekly-docker.yml
Labels: Docker

#6385 Actually push the weekly docker image
  .github/workflows/release-weekly-docker.yml
Labels: Docker

#6386 Try fixing weekly docker image again
  .github/workflows/release-weekly-docker.yml
Labels: Docker

#6387 Use WebSwing prod in stable and live docker images
  .github/workflows/release-main-docker.yml
  .github/workflows/release-weekly-docker.yml
  docker/Dockerfile-live
  docker/Dockerfile-stable
Labels: Docker

#6392 Update docs section in CONTRIBUTING
  CONTRIBUTING.md
Labels: Type-Task

#6393 Remove unnecessary null checks and casts
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderAPI.java
Labels: Type-Task

#6395 Rely on default branches for weekly add-ons
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/internal/BuildData.kt
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#6399 Run CI checks with GitHub workflow
  .github/workflows/ci.yml
  .travis.yml
  build.gradle.kts
  gradle/ci.gradle.kts
Labels: Type-Task

#6411 Update dependencies
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#6408 Remove deprecated Python 3.5 from CI tests
  .github/workflows/test-packaged-scans.yml
  docker/CHANGELOG.md
Labels: Type-Task

#6413 Allow to export regular expressions
  zap/src/main/java/org/zaproxy/zap/view/MultipleRegexesOptionsPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Component-UI, enhancement

#6414 Correct proxy scripts' return value evaluation
  zap/src/main/java/org/zaproxy/zap/extension/script/ProxyListenerScript.java
  zap/src/test/java/org/zaproxy/zap/extension/script/ProxyListenerScriptUnitTest.java
Labels: Type-Task

#6415 Spelling fixes
  zap/src/main/java/ch/csnc/extension/httpclient/SSLContextManager.java
  zap/src/main/java/ch/csnc/extension/ui/DriversView.java
  zap/src/main/java/ch/csnc/extension/util/OptionsParamExperimentalSliSupport.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantAbstractRPCQuery.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java
  zap/src/main/java/org/parosproxy/paros/network/HttpStatusCode.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScanProgressItem.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScanProgressTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptWrapper.java
  zap/src/test/java/ch/csnc/extension/httpclient/SSLContextManagerUnitTest.java
Labels: Type-Task

#6417 Increase test coverage of JSON variant
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantJSONQueryUnitTest.java
Labels: Type-Task

#5566 Refactor SimpleEventBus
  zap/src/main/java/org/zaproxy/zap/eventBus/SimpleEventBus.java
Labels: Type-Task

#6425 Tidy up tests' setup
  zap/src/test/java/org/parosproxy/paros/model/SessionUnitTest.java
  zap/src/test/java/org/parosproxy/paros/model/SiteMapUnitTest.java
  zap/src/test/java/org/zaproxy/zap/WithConfigsTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/JsonBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/script/ExtensionScriptUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/SessionStructureUnitTest.java
Labels: Type-Task

#6423 Fix JavaScript function JSON encoding issue
  zap/src/main/java/org/zaproxy/zap/utils/JsonUtil.java
  zap/src/test/java/org/zaproxy/zap/utils/JsonUtilUnitTest.java
Labels: Type-Task
