Repository zaproxy/zaproxy, pull requests merged in 2022-02, with the labels that each got.

#7059 Fix Stats Concurrent access bug
  zap/src/main/java/org/zaproxy/zap/utils/Statistics.java
Labels: bug

#7062 Adds ID for Server Side Template Injection Script
  docs/scanners.md
Labels: Type-Task

#7063 Add OpenAPI integration test
  docker/integration_tests/configs/plans/petstore-openapi.yaml
Labels: Type-Task

#7064 Remove some deprecated classes
  zap/src/main/java/org/parosproxy/paros/common/FileXML.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/SenderThread.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/SenderThreadListener.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/StreamForwarder.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractDefaultFilePlugin.java
  zap/src/main/java/org/parosproxy/paros/extension/history/BrowserDialog.java
  zap/src/main/java/org/parosproxy/paros/extension/history/PopupMenuResend.java
  zap/src/main/java/org/parosproxy/paros/extension/history/PopupMenuResendSites.java
  zap/src/main/java/org/parosproxy/paros/model/HistoryList.java
  zap/src/main/java/org/parosproxy/paros/model/HttpMessageList.java
  zap/src/main/java/org/parosproxy/paros/network/ByteVector.java
  zap/src/main/java/org/parosproxy/paros/network/ProxyExcludedDomainMatcher.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakpointMessageHandler.java
  zap/src/main/java/org/zaproxy/zap/httputils/RequestUtils.java
  zap/src/main/java/org/zaproxy/zap/view/HistoryReferenceTableModel.java
  zap/zap.gradle.kts
Labels: Type-Task

#7066 Remove unused resource message
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7067 Remove 2.2.0 / 2.3.0 deprecations
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableHistory.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionPopupMenuItem.java
  zap/src/main/java/org/parosproxy/paros/network/ConnectionParam.java
  zap/src/main/java/org/parosproxy/paros/view/MainPopupMenu.java
  zap/src/main/java/org/zaproxy/zap/extension/ExtensionPopupMenu.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScanPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/search/SearchPanel.java
  zap/src/main/java/org/zaproxy/zap/spider/SpiderParam.java
  zap/src/main/java/org/zaproxy/zap/view/ContextExcludePanel.java
  zap/src/main/java/org/zaproxy/zap/view/ContextIncludePanel.java
  zap/src/main/java/org/zaproxy/zap/view/PopupMenuHistoryReference.java
  zap/src/main/java/org/zaproxy/zap/view/PopupMenuHttpMessage.java
  zap/src/main/java/org/zaproxy/zap/view/PopupMenuSiteNode.java
  zap/zap.gradle.kts
Labels: Type-Task

#7068 Remove 2.4.x deprecations
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/PluginFactory.java
  zap/src/main/java/org/parosproxy/paros/db/RecordAlert.java
  zap/src/main/java/org/parosproxy/paros/view/AbstractFrame.java
  zap/src/main/java/org/zaproxy/zap/control/AddOn.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/zap.gradle.kts
Labels: Type-Task

#7076 Set parent of warning messages in param dialogue
  zap/src/main/java/org/parosproxy/paros/view/AbstractParamDialog.java
Labels: Type-Task

#7077 chore: Leverage isEmpty vs size equality zero checks
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyParam.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Kb.java
  zap/src/main/java/org/parosproxy/paros/extension/history/HistoryFilter.java
  zap/src/main/java/org/parosproxy/paros/extension/history/PopupMenuExportMessage.java
  zap/src/main/java/org/parosproxy/paros/extension/history/PopupMenuExportResponse.java
  zap/src/main/java/org/parosproxy/paros/model/SiteMap.java
  zap/src/main/java/org/parosproxy/paros/network/ConnectionParam.java
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiResponseList.java
  zap/src/main/java/org/zaproxy/zap/extension/api/OptionsParamApi.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScanController.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/AttackModeScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/PolicyManager.java
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/GlobalExcludeURLParam.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/HttpPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/httpsessions/HttpSessionsParam.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderScanController.java
  zap/src/main/java/org/zaproxy/zap/scan/BaseScannerThreadManager.java
  zap/src/main/java/org/zaproxy/zap/view/ScanPanel.java
  zap/src/main/java/org/zaproxy/zap/view/StandardFieldsDialog.java
  zap/src/main/java/org/zaproxy/zap/view/messagecontainer/http/DefaultSelectableHttpMessagesContainer.java
  zap/src/main/java/org/zaproxy/zap/view/table/DefaultHistoryReferencesTableEntry.java
Labels: Type-Task

#7080 Deprecate and disable proxy related code
  zap/src/main/java/org/parosproxy/paros/CommandLine.java
  zap/src/main/java/org/parosproxy/paros/control/Control.java
  zap/src/main/java/org/parosproxy/paros/control/MenuToolsControl.java
  zap/src/main/java/org/parosproxy/paros/control/Proxy.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/CacheProcessingItem.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/CustomStreamsSocket.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyParam.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyServer.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyThread.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/main/java/org/parosproxy/paros/extension/history/ExtensionHistory.java
  zap/src/main/java/org/parosproxy/paros/model/OptionsParam.java
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/parosproxy/paros/view/MainFooterPanel.java
  zap/src/main/java/org/parosproxy/paros/view/MainFrame.java
  zap/src/main/java/org/parosproxy/paros/view/View.java
  zap/src/main/java/org/zaproxy/zap/DaemonBootstrap.java
  zap/src/main/java/org/zaproxy/zap/HeadlessBootstrap.java
  zap/src/main/java/org/zaproxy/zap/ZapBootstrap.java
  zap/src/main/java/org/zaproxy/zap/control/CoreFunctionality.java
  zap/src/main/java/org/zaproxy/zap/extension/api/API.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiGeneratorUtils.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanelToolbarFactory.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/ExtensionBreak.java
  zap/src/main/java/org/zaproxy/zap/extension/callback/ExtensionCallback.java
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/GlobalExcludeURLParam.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/DialogAddProxy.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/DialogModifyProxy.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/ExtensionProxies.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/OptionsLocalProxyPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/OptionsProxiesPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/OptionsProxiesTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/ProxiesAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/ProxiesParam.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/ProxiesParamProxy.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/parosproxy/paros/CommandLineUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/proxy/ProxyThreadUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/APIUnitTest.java
Labels: Type-Task

#7086 Show child panel if parent node has none
  zap/src/main/java/org/parosproxy/paros/view/AbstractParamContainerPanel.java
Labels: Type-Task

#7088 Correct parent of user related dialogues
  zap/src/main/java/org/zaproxy/zap/extension/users/ContextUsersPanel.java
Labels: Type-Task

#7085 API - Do not require Authentication Realm and use default value
  zap/src/main/java/org/zaproxy/zap/authentication/HttpAuthenticationMethodType.java
Labels: bug, Component-API

#6871 added python3 support for `python/scripts`
  python/scripts/generic-pytest/test_zap.py
  python/scripts/watcher/watcher.py
  python/scripts/wavsep/wavsep.py
Labels: Type-Task

#7090 feat: Support Info dialog user friendliness improvements (copy button)
  zap/src/main/java/org/zaproxy/zap/view/ZapSupportDialog.java
  zap/src/main/java/org/zaproxy/zap/view/ZapSupportPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: enhancement, Component-UI

#7089 feat: Upgrade from issue templates to issue forms
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Third_party_addon.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/third-party-addon.yml
Labels: Type-Task

#7097 Integration tests - disable AF context tests
  .github/workflows/run-integration-tests.yml
Labels: Type-Task

#7098 Integration tests - re-enable AF context tests
  .github/workflows/run-integration-tests.yml
  docker/integration_tests/af_context_tests.sh
  docker/integration_tests/configs/scripts/af_context_tests.js
Labels: Type-Task

#7099 Integration Tests: Fix session-script test
  docker/integration_tests/configs/plans/contexts/session-script.context
Labels: Type-Task

#7101 Workaround issues when displaying big messages
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsParamView.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsViewPanel.java
  zap/src/main/java/org/zaproxy/zap/control/CoreFunctionality.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largerequest/ExtensionHttpPanelLargeRequestView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largerequest/LargeRequestStringHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largerequest/LargeRequestUtil.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largerequest/RequestLargeRequestAllView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largerequest/RequestLargeRequestSplitView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largeresponse/ExtensionHttpPanelLargeResponseView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largeresponse/LargeResponseStringHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largeresponse/LargeResponseUtil.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largeresponse/ResponseLargeResponseAllView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/largeresponse/ResponseLargeResponseSplitView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/ContentSplitter.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/HttpPanelSyntaxHighlightTextArea.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/HttpPanelSyntaxHighlightTextView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/components/all/request/HttpRequestAllPanelSyntaxHighlightTextView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/components/all/response/HttpResponseAllPanelSyntaxHighlightTextView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/components/split/request/HttpRequestBodyPanelSyntaxHighlightTextView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/components/split/response/HttpResponseBodyPanelSyntaxHighlightTextView.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/menus/ViewMenu.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7102 Remove code deprecated in 2.5.0
  zap/src/main/java/org/parosproxy/paros/control/Control.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantAbstractQuery.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableHistory.java
  zap/src/main/java/org/parosproxy/paros/extension/history/LogPanel.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsParamView.java
  zap/src/main/java/org/parosproxy/paros/view/MainFrame.java
  zap/src/main/java/org/parosproxy/paros/view/View.java
  zap/src/main/java/org/parosproxy/paros/view/WorkbenchPanel.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableHistory.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/AddOnsTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuPurgeSites.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuShowInHistory.java
  zap/src/main/java/org/zaproxy/zap/extension/search/SearchPanel.java
  zap/src/main/java/org/zaproxy/zap/view/MainToolbarPanel.java
  zap/src/main/java/org/zaproxy/zap/view/MessagePanelsPositionController.java
  zap/src/main/java/org/zaproxy/zap/view/TabbedPanel2.java
  zap/zap.gradle.kts
Labels: Type-Task
