Repository zaproxy/zaproxy, pull requests merged in 2022-10, with the labels that each got.

#7498 Update HSQLDB
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#7501 Add CodeQL workflow
  .github/workflows/codeql.yml
  README.md
Labels: Type-Task

#7500 Exclude browser/OS updates by default
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/GlobalExcludeURLParam.java
Labels: enhancement

#7459 Disable/deprecate the Manual Request Editor
  zap/src/main/java/org/parosproxy/paros/extension/history/ExtensionHistory.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ExtensionManualRequestEditor.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ManualRequestEditorDialog.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/MessageSender.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/HttpPanelSender.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/ManualHttpRequestEditorDialog.java
  zap/src/main/java/org/zaproxy/zap/control/CoreFunctionality.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuResendMessage.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupMenuResendMessage.java
Labels: enhancement, Component-UI

#7295 Scan Policy Manager Policy multiplies while modifying the name
  zap/src/main/java/org/zaproxy/zap/extension/ascan/PolicyAllCategoryPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/PolicyManager.java
  zap/src/test/java/org/zaproxy/zap/extension/ascan/PolicyManagerUnitTest.java
Labels: Type-Task

#7511 Docker: Stable/live to debian, remove zapcli, update webswing
  docker/CHANGELOG.md
  docker/Dockerfile-bare
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Docker

#7512 add entry to unexpected content type
  docker/CHANGELOG.md
  docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
Labels: Type-Task

#7515 Update HAR API deprecation message
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7516 Restore Session title and Persist Session's state
  zap/src/main/java/org/parosproxy/paros/view/MainMenuBar.java
  zap/src/main/java/org/zaproxy/zap/extension/uiutils/ExtensionUiUtils.java
  zap/src/test/java/org/zaproxy/zap/extension/uiutils/ExtensionUiUtilsUnitTest.java
Labels: Type-Task

#7141 Add open recent menu
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsParamView.java
  zap/src/main/java/org/parosproxy/paros/view/MainMenuBar.java
  zap/src/main/java/org/zaproxy/zap/extension/uiutils/ExtensionUiUtils.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7517 Reserve ID for SSRF Scan Rule
  docs/scanners.md
Labels: Type-Task

#7520 Update version for 2.12.0
  zap/src/main/java/org/parosproxy/paros/Constant.java
Labels: Type-Task

#7519 Update apache-commons and rsyntaxtextarea
  LEGALNOTICE.md
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.java
  zap/zap.gradle.kts
Labels: Type-Task

#7521 Reduce HTML usage and use localised strings
  zap/src/main/java/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/session/ScriptBasedSessionManagementMethodType.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#6578 Add input vector to alerts
  zap/src/main/dist/db/hsqldb.properties
  zap/src/main/dist/db/mysql.properties
  zap/src/main/dist/db/mysql.schema
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractAppParamPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Variant.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantCookie.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantCustom.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantDdnPath.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantDirectWebRemotingQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantFormQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantGWTQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantHeader.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantJSONQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantMultipartFormParameters.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantODataFilterQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantODataIdQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantURLPath.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantURLQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantUserDefined.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantXMLQuery.java
  zap/src/main/java/org/parosproxy/paros/db/RecordAlert.java
  zap/src/main/java/org/parosproxy/paros/db/TableAlert.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableAlert.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableAlert.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertViewPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/ExtensionAlert.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/resources/org/zaproxy/zap/resources/zapdb.script
  zap/zap.gradle.kts
Labels: Type-Task

#7522 Remove test class of legacy HttpSender
  zap/src/test/java/org/parosproxy/paros/network/HttpSenderUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/AuthenticationMethodPollUrlUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/JsonBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/autoupdate/DownloadManagerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/autoupdate/DownloaderUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#7524 Address exceptions in AbstractAppParamPlugin
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractAppParamPlugin.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AbstractAppParamPluginUnitTest.java
Labels: bug, weekly

#7525 Do not rely on HttpSender implementation in tests
  zap/src/test/java/org/zaproxy/zap/authentication/AuthenticationMethodPollUrlUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/JsonBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodTypeUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/autoupdate/DownloadManagerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/autoupdate/DownloaderUnitTest.java
  zap/src/test/java/org/zaproxy/zap/testutils/HTTPDTestServer.java
  zap/src/test/java/org/zaproxy/zap/testutils/NanoServerHandler.java
  zap/src/test/java/org/zaproxy/zap/testutils/TestHttpSender.java
  zap/src/test/java/org/zaproxy/zap/testutils/TestUtils.java
  zap/zap.gradle.kts
Labels: Type-Task

#7528 Make it easier to update main add-ons
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/zaproxy/zap/tasks/DownloadMainAddOns.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/UpdateMainAddOns.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/internal/MainAddOn.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/internal/MainAddOnsData.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/internal/MarketplaceAddOn.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/internal/Utils.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/internal/ZapXmlConfiguration.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  zap/src/main/add-ons.txt
  zap/src/main/main-add-ons.yml
Labels: Type-Task

#7529 Remove Apache Commons XPath dependency
  LEGALNOTICE.md
  zap/src/main/java/org/zaproxy/zap/control/AddOn.java
  zap/src/main/java/org/zaproxy/zap/control/AddOnCollection.java
  zap/src/main/java/org/zaproxy/zap/control/BaseZapAddOnXmlData.java
  zap/src/main/java/org/zaproxy/zap/control/ZapAddOnXmlFile.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#7530 Address JavaDoc errors
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Variant.java
  zap/src/main/java/org/parosproxy/paros/extension/option/SecurityProtocolsPanel.java
  zap/src/main/java/org/parosproxy/paros/model/HistoryReference.java
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/parosproxy/paros/network/GenericMethod.java
  zap/src/main/java/org/parosproxy/paros/network/SSLConnector.java
  zap/src/main/java/org/zaproxy/zap/ZapHttpConnection.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/filters/GenericFilterUtility.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/filters/ScanFilter.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanData.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanParam.java
  zap/src/main/java/org/zaproxy/zap/model/SessionStructure.java
  zap/src/main/java/org/zaproxy/zap/network/ZapDeleteMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapHeadMethod.java
  zap/src/main/java/org/zaproxy/zap/spider/Spider.java
  zap/src/main/java/org/zaproxy/zap/spider/SpiderListener.java
  zap/src/main/java/org/zaproxy/zap/spider/filters/DefaultParseFilter.java
  zap/src/main/java/org/zaproxy/zap/view/popup/PopupMenuHttpMessageContainer.java
Labels: Type-Task

#7531 Assign ID for Text4Shell
  docs/scanners.md
Labels: Type-Task

#7532 Fix buildWeeklyAddOns task
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/internal/RepoData.java
Labels: Type-Task

#7533 Set passive scan data to scan rules
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanData.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTask.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScanTestHelper.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PluginPassiveScannerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScannerUnitTest.java
Labels: Type-Task

#7534 Simplify integration tests
  docker/integration_tests/baseline_tests.sh
  docker/integration_tests/results/baseline1-1.out
  docker/integration_tests/results/baseline1-2.out
  docker/integration_tests/results/baseline1-3.out
  docker/integration_tests/results/baseline1-4.out
  docker/integration_tests/results/baseline1-5.out
  docker/integration_tests/results/baseline1-6.out
  docker/integration_tests/results/baseline2-1.out
  docker/integration_tests/results/baseline2-2.out
  docker/integration_tests/results/baseline2-3.out
  docker/integration_tests/results/baseline2-4.out
  docker/integration_tests/results/baseline2-5.out
  docker/integration_tests/results/baseline2-6.out
  docker/integration_tests/results/baseline3-1.out
  docker/integration_tests/results/baseline4-1.out
  docker/integration_tests/results/baseline4-2.out
Labels: Type-Task

#7537 Remove tasks from release pull request
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
Labels: Type-Task

#7538 Reduce HTML usage
  zap/src/main/java/org/zaproxy/zap/view/ScanPanel.java
Labels: Type-Task

#7505 Update release instructions
  RELEASING.md
Labels: Type-Task

#7547 Update hsqldb to 2.7.1
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#7550 Update add-ons bundled in core dist
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
Labels: Type-Task

#7551 Prepare next dev iteration
  zap/zap.gradle.kts
Labels: Type-Task

#7554 Release tweaks
  BUILDING.md
  RELEASING.md
Labels: Type-Task

#7561 Add GitHub workflow to release the snap
  .github/workflows/release-snap.yml
  RELEASING.md
  snap/README.md
  snap/build-snap.sh
  snap/snapcraft.yaml
Labels: Type-Task

#7560 Avoid tab focus on Alert selection in Full layout
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertPanel.java
Labels: Type-Task

#7562 Fallback to Maven Central when resolving plugins
  buildSrc/settings.gradle.kts
  settings.gradle.kts
Labels: Type-Task
