Repository zaproxy/zaproxy, pull requests merged in 2022-07, with the labels that each got.

#7364 pscan: Reduce logging
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTask.java
Labels: Type-Task

#7375 Fix copy of passive script scan rule
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScanner.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScannerUnitTest.java
Labels: bug, weekly

#7299 Spider: find table/td background, video src/poster, and img srcset
  zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderHtmlParserUnitTest.java
  zap/src/test/resources/org/zaproxy/zap/spider/parser/html/ImgElementsSpiderHtmlParser.html
  zap/src/test/resources/org/zaproxy/zap/spider/parser/html/TableElementsSpiderHtmlParser.html
  zap/src/test/resources/org/zaproxy/zap/spider/parser/html/VideoElementsSpiderHtmlParser.html
Labels: enhancement

#7374 PostBasedAuthenticationMethodType updates
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
  zap/src/test/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodTypeUnitTest.java
Labels: Type-Task

#7365 Consistently prompt when deleting history/sites items
  zap/src/main/java/org/parosproxy/paros/extension/history/ExtensionHistory.java
  zap/src/main/java/org/parosproxy/paros/view/SiteMapPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuPurgeSites.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7380 Correct start time of passive scan rules
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTask.java
Labels: bug, weekly

#7382 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#7388 Include architecture in support info
  zap/src/main/java/org/zaproxy/zap/utils/ZapSupportUtils.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7395 Update Webswing
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task
