Repository zaproxy/zaproxy, pull requests merged in 2022-06, with the labels that each got.

#7170 Add support for absolute file paths in all relevant scan options
  docker/CHANGELOG.md
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
Labels: Type-Task

#7315 Tidy up HttpSender
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
Labels: Type-Task

#7318 Deprecate HttpException
  zap/src/main/java/org/apache/commons/httpclient/HttpException.java
  zap/src/main/java/org/apache/commons/httpclient/HttpMethodBase.java
  zap/src/main/java/org/apache/commons/httpclient/URIException.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyThread.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Analyser.java
  zap/src/main/java/org/parosproxy/paros/network/GenericMethod.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/zaproxy/zap/ZapGetMethod.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScriptsActiveScanner.java
  zap/src/main/java/org/zaproxy/zap/network/ZapDeleteMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapHeadMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapHttpParser.java
  zap/src/main/java/org/zaproxy/zap/network/ZapOptionsMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapPostMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapPutMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapTraceMethod.java
Labels: Type-Task

#7316 Allow to replace HttpSender implementation
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSenderContextParos.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSenderParos.java
  zap/src/main/java/org/zaproxy/zap/network/HttpSenderContext.java
  zap/src/main/java/org/zaproxy/zap/network/HttpSenderImpl.java
  zap/src/test/java/org/parosproxy/paros/network/HttpSenderUnitTest.java
Labels: Type-Task

#7317 Fix NullPointerException when running Kotlin scripts without view
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: bug, weekly

#7319 Set Content-Length in POST based auth
  zap/src/main/java/org/zaproxy/zap/authentication/PostBasedAuthenticationMethodType.java
Labels: Type-Task

#7320 Update to Webswing 22.1.2
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task, Docker

#7321 Deprecate HttpSender implementation classes
  zap/src/main/java/org/apache/commons/httpclient/HttpConnection.java
  zap/src/main/java/org/apache/commons/httpclient/HttpMethodBase.java
  zap/src/main/java/org/apache/commons/httpclient/HttpMethodDirector.java
  zap/src/main/java/org/apache/commons/httpclient/protocol/SecureProtocolSocketFactory.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyParam.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyPortRetryPanel.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyServerSSL.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyThread.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/HttpPanelSender.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsParamCertificate.java
  zap/src/main/java/org/parosproxy/paros/extension/option/SecurityProtocolsPanel.java
  zap/src/main/java/org/parosproxy/paros/network/DecoratedSocketsSslSocketFactory.java
  zap/src/main/java/org/parosproxy/paros/network/GenericMethod.java
  zap/src/main/java/org/parosproxy/paros/network/HttpMethodHelper.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSenderContextParos.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSenderParos.java
  zap/src/main/java/org/parosproxy/paros/network/SSLConnector.java
  zap/src/main/java/org/zaproxy/zap/PersistentConnectionListener.java
  zap/src/main/java/org/zaproxy/zap/ZapGetMethod.java
  zap/src/main/java/org/zaproxy/zap/ZapHttpConnection.java
  zap/src/main/java/org/zaproxy/zap/ZapHttpConnectionManager.java
  zap/src/main/java/org/zaproxy/zap/extension/dynssl/ExtensionDynSSL.java
  zap/src/main/java/org/zaproxy/zap/network/ZapCookieSpec.java
  zap/src/main/java/org/zaproxy/zap/network/ZapDeleteMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapHeadMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapHttpParser.java
  zap/src/main/java/org/zaproxy/zap/network/ZapNTLMEngineImpl.java
  zap/src/main/java/org/zaproxy/zap/network/ZapNTLMScheme.java
  zap/src/main/java/org/zaproxy/zap/network/ZapOptionsMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapPostMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapPutMethod.java
  zap/src/main/java/org/zaproxy/zap/network/ZapTraceMethod.java
  zap/src/test/java/org/apache/commons/httpclient/HttpMethodBaseUnitTest.java
  zap/src/test/java/org/zaproxy/zap/network/ZapCookieSpecUnitTest.java
Labels: Type-Task

#7327 Fix class cast exception with manual requests
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/http/impl/HttpPanelSender.java
Labels: Type-Task

#7328 Fix NullPointerException when obtaining host name
  zap/src/main/java/org/zaproxy/zap/model/SessionStructure.java
  zap/src/test/java/org/zaproxy/zap/model/SessionStructureUnitTest.java
Labels: Type-Task

#7325 Fix some scaling issues
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ManualRequestEditorDialog.java
  zap/src/main/java/org/parosproxy/paros/view/AbstractParamContainerPanel.java
  zap/src/main/java/org/parosproxy/paros/view/OptionsDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/PolicyDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/PolicyManagerDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanelToolbarFactory.java
  zap/src/main/java/org/zaproxy/zap/view/AboutPanel.java
Labels: Type-Task

#7331 Set name to threads
  zap/src/main/java/org/parosproxy/paros/core/scanner/Scanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanController.java
Labels: Type-Task

#7332 Fix PatternSyntaxException in Analyser
  zap/src/main/java/org/parosproxy/paros/core/scanner/Analyser.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AnalyserUnitTest.java
Labels: bug

#7338 Include Requester add-on in weekly releases
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#7342 Allow to hook history type info
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionHook.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ExtensionManualRequestEditor.java
  zap/src/main/java/org/zaproxy/zap/view/HrefTypeInfo.java
  zap/src/main/java/org/zaproxy/zap/view/table/AbstractHistoryReferencesTableEntry.java
  zap/src/test/java/org/zaproxy/zap/view/HrefTypeInfoUnitTest.java
Labels: enhancement

#7337 Disable and deprecate resend context menu
  zap/src/main/java/org/parosproxy/paros/extension/history/ExtensionHistory.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuResendMessage.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/ExtensionStdMenus.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupMenuResendMessage.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7347 Tweak the html_mailto regular expression
  zap/src/main/resources/org/zaproxy/zap/resources/config.xml
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/DefaultRegexAutoTagScannerTest.java
Labels: Type-Task

#7351 Do not process location URL when processing links
  zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHttpHeaderParser.java
Labels: Type-Task

#7359 Deprecate Tab interface
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ManualRequestEditorDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/HttpPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/tab/Tab.java
  zap/zap.gradle.kts
Labels: Type-Task
