Repository zaproxy/zaproxy, pull requests merged in 2022-05, with the labels that each got.

#7261 Allow to request shutdown when executing args
  zap/src/main/java/org/parosproxy/paros/extension/CommandLineListener.java
  zap/src/main/java/org/zaproxy/zap/CommandLineBootstrap.java
  zap/src/main/java/org/zaproxy/zap/DaemonBootstrap.java
  zap/src/main/java/org/zaproxy/zap/ShutdownRequestedException.java
Labels: Type-Task

#7256 Deprecate HttpSender#setAllowCircularRedirects
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
Labels: Type-Task

#7259 Update commit guidance link
  CONTRIBUTING.md
Labels: Type-Task

#7267 Use latest user-agent and timeout always
  zap/src/main/java/org/apache/commons/httpclient/HttpMethodDirector.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
Labels: enhancement

#7258 chore: Standardize on the use of "status" vs "quality"
  zap/src/main/installer/resources/Messages.properties
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/CategoryTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/PolicyAllCategoryPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/UninstalledAddOnsTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PolicyPassiveScanPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PolicyPassiveScanTableModel.java
  zap/src/main/java/org/zaproxy/zap/view/StatusUI.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7275 Enable reveal password functionality
  zap/src/main/java/org/zaproxy/zap/GuiBootstrap.java
Labels: enhancement, Component-UI, Usability

#7276 Correct Enable/Disable All buttons enabled state
  zap/src/main/java/org/zaproxy/zap/view/AbstractMultipleOptionsTablePanel.java
Labels: bug, Component-UI

#7280 Fix escaping on API param desc for setContextCheckingStrategy
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: bug, Component-Docs, Component-API

#7282 Allow to select panels with the same name
  zap/src/main/java/org/parosproxy/paros/view/AbstractParamContainerPanel.java
Labels: Type-Task

#7287 Add missed connection option API endpoint
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/test/java/org/zaproxy/zap/extension/api/CoreAPIUnitTest.java
Labels: Type-Task

#7270 Support passive scan threading
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/AntiCsrfDetectScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/httpsessions/HttpSessionsSite.java
  zap/src/main/java/org/zaproxy/zap/extension/params/ExtensionParams.java
  zap/src/main/java/org/zaproxy/zap/extension/params/HtmlParameterStats.java
  zap/src/main/java/org/zaproxy/zap/extension/params/ParamScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/params/ParamsTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/params/SiteParameters.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/OptionsPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanController.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanParam.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTask.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTaskHelper.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScannerOptionsPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/RegexAutoTagScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/StatsPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/utils/ThreadUtils.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScanTestHelper.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScannerControllerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PluginPassiveScannerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScannerUnitTest.java
  zap/zap.gradle.kts
Labels: enhancement

#7285 Deprecate and remove use of URL Export menu items being moved to exim
  zap/src/main/java/org/parosproxy/paros/extension/history/ExtensionHistory.java
  zap/src/main/java/org/parosproxy/paros/extension/history/PopupMenuExportMessage.java
  zap/src/main/java/org/parosproxy/paros/extension/history/PopupMenuExportResponse.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuExportContextURLs.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuExportSelectedURLs.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuExportURLs.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/ExtensionStdMenus.java
  zap/src/main/java/org/zaproxy/zap/extension/stdmenus/PopupMenuCopyUrls.java
Labels: Type-Task

#7291 Use Network add-on to manage connection options
  zap/src/main/dist/xml/common-user-agents.txt
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyServer.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyThread.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Scanner.java
  zap/src/main/java/org/parosproxy/paros/extension/option/DialogAddProxyExcludedDomain.java
  zap/src/main/java/org/parosproxy/paros/extension/option/DialogModifyProxyExcludedDomain.java
  zap/src/main/java/org/parosproxy/paros/extension/option/ExtensionOption.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsConnectionPanel.java
  zap/src/main/java/org/parosproxy/paros/extension/option/ProxyExcludedDomainsTableModel.java
  zap/src/main/java/org/parosproxy/paros/extension/option/SecurityProtocolsPanel.java
  zap/src/main/java/org/parosproxy/paros/model/OptionsParam.java
  zap/src/main/java/org/parosproxy/paros/network/ConnectionParam.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/AttackScan.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/DownloadManager.java
  zap/src/main/java/org/zaproxy/zap/extension/option/SocksProxyPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/OptionsProxiesPanel.java
  zap/src/main/java/org/zaproxy/zap/model/CommonUserAgents.java
  zap/src/main/java/org/zaproxy/zap/network/SocksProxy.java
  zap/src/main/java/org/zaproxy/zap/network/ZapAuthenticator.java
  zap/src/main/java/org/zaproxy/zap/spider/Spider.java
  zap/src/main/java/org/zaproxy/zap/spider/SpiderParam.java
  zap/src/main/java/org/zaproxy/zap/view/OptionsConnectionPanel.java
  zap/src/main/java/org/zaproxy/zap/view/ProxyDialog.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/HostProcessUnitTest.java
  zap/src/test/java/org/parosproxy/paros/network/HttpSenderUnitTest.java
  zap/src/test/java/org/zaproxy/zap/network/SocksProxyUnitTest.java
Labels: enhancement

#7229 Allow to generate CSRF form with custom action through the API
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/AntiCsrfAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRFUnitTest.java
Labels: enhancement, Component-API

#7269 Fix get all alert tags
  zap/src/main/dist/db/hsqldb.properties
  zap/src/main/java/org/zaproxy/zap/db/paros/ParosTableAlertTag.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableAlertTag.java
Labels: bug

#7214 Enable debug option for Mac in zap.sh
  zap/src/main/dist/zap.sh
Labels: Type-Task, OpSys-OSX

#7294 Remove option allow unsafe SSL/TLS renegotiation
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsParamCertificate.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7300 Confirm the deletion with the name of the context
  zap/src/main/java/org/zaproxy/zap/view/DeleteContextAction.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: enhancement, Component-UI, Usability

#7306 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#7305 Expose OptionsDialog through ViewDelegate
  zap/src/main/java/org/parosproxy/paros/extension/ViewDelegate.java
  zap/src/main/java/org/parosproxy/paros/view/View.java
Labels: Type-Task

#7307 Use shared connection pool
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/Downloader.java
  zap/src/main/java/org/zaproxy/zap/spider/Spider.java
Labels: Type-Task

#7304 Use Network add-on to manage client certificates
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  zap/src/main/java/ch/csnc/extension/httpclient/AliasCertificate.java
  zap/src/main/java/ch/csnc/extension/httpclient/AliasKeyManager.java
  zap/src/main/java/ch/csnc/extension/httpclient/PKCS11Configuration.java
  zap/src/main/java/ch/csnc/extension/httpclient/SSLContextManager.java
  zap/src/main/java/ch/csnc/extension/ui/AliasTableModel.java
  zap/src/main/java/ch/csnc/extension/ui/CertificateView.java
  zap/src/main/java/ch/csnc/extension/ui/DriverTableModel.java
  zap/src/main/java/ch/csnc/extension/ui/DriversView.java
  zap/src/main/java/ch/csnc/extension/util/DriverConfiguration.java
  zap/src/main/java/ch/csnc/extension/util/OptionsParamExperimentalSliSupport.java
  zap/src/main/java/org/parosproxy/paros/extension/option/ExtensionOption.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsParamCertificate.java
  zap/src/main/java/org/parosproxy/paros/model/OptionsParam.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/parosproxy/paros/network/SSLConnector.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/resources/org/zaproxy/zap/resources/drivers.xml
  zap/src/test/java/ch/csnc/extension/httpclient/AliasCertificateUnitTest.java
  zap/src/test/java/ch/csnc/extension/httpclient/AliasKeyManagerUnitTest.java
  zap/src/test/java/ch/csnc/extension/httpclient/PKCS11ConfigurationUnitTest.java
  zap/src/test/java/ch/csnc/extension/httpclient/SSLContextManagerUnitTest.java
  zap/src/test/java/ch/csnc/extension/util/DriverConfigurationUnitTest.java
Labels: enhancement

#7310 Pass Control, Model, View singletons to scripts
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: enhancement, Component-Scripts

#7302 Clarify History Tags vs Alert Tags
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/AntiCsrfDetectScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTaskHelper.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/RegexAutoTagScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScanner.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AlertUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PluginPassiveScannerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScannerUnitTest.java
Labels: enhancement

#7311 Use passed singleton variables in script templates
  docker/integration_tests/configs/scripts/af_context_tests.js
  docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js
  docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
  zap/src/main/dist/scripts/templates/standalone/Loop through history table.js
  zap/src/main/dist/scripts/templates/standalone/Traverse sites tree.js
Labels: Type-Task

#7312 chore: Tweak scanners.md content
  docs/scanners.md
Labels: Type-Task
