Repository zaproxy/zaproxy, pull requests merged in 2023-10, with the labels that each got.

#8094 Use host normalization flag in break panel
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanel.java
Labels: Type-Task

#8097 Update Commons Lang3
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#8098 Update JRE bundled in macOS packages
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
Labels: Type-Task

#8099 Include BOM in main (GitHub) release
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
  zap/zap.gradle.kts
Labels: Type-Task

#8106 Update version for 2.14.0
  zap/src/main/java/org/parosproxy/paros/Constant.java
Labels: Type-Task

#8101 Extend ScanEventPublisher to support params
  zap/src/main/java/org/zaproxy/zap/model/ScanEventPublisher.java
  zap/src/test/java/org/zaproxy/zap/model/ScanEventPublisherUnitTest.java
Labels: enhancement

#8110 Bundle runtime BOM in dists
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  zap/zap.gradle.kts
Labels: Type-Task

#8109 Make SBOM zip available via GUI, cmdline and API.
  zap/src/main/java/org/parosproxy/paros/CommandLine.java
  zap/src/main/java/org/zaproxy/zap/CommandLineBootstrap.java
  zap/src/main/java/org/zaproxy/zap/control/AddOn.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/java/org/zaproxy/zap/utils/ZapSupportUtils.java
  zap/src/main/java/org/zaproxy/zap/view/ZapSupportDialog.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/control/AddOnUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/CoreAPIUnitTest.java
Labels: enhancement

#8115 Use bold font for `TitledBorder` highlight
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/HighlighterUtils.java
Labels: Type-Task

#8118 Record config stats
  zap/src/main/java/org/zaproxy/zap/CommandLineBootstrap.java
  zap/src/main/java/org/zaproxy/zap/DaemonBootstrap.java
  zap/src/main/java/org/zaproxy/zap/GuiBootstrap.java
  zap/src/main/java/org/zaproxy/zap/ZapBootstrap.java
Labels: Type-Task

#8120 Prepare next dev iteration
  zap/gradle.properties
  zap/gradle/japicmp.yaml
Labels: Type-Task

#8123 Add/update packages in release steps
  RELEASING.md
Labels: Type-Task

#8130 Allow to set handler for content encodings
  zap/src/main/java/org/parosproxy/paros/network/HttpMessage.java
  zap/src/test/java/org/parosproxy/paros/network/HttpMessageUnitTest.java
Labels: Type-Task

#8131 Fix a typo
  zap/src/main/java/org/parosproxy/paros/control/Control.java
Labels: Type-Task

#8072 fix: Context API including a parent Tech should include children
  zap/src/main/java/org/zaproxy/zap/extension/api/ContextAPI.java
  zap/src/main/java/org/zaproxy/zap/model/TechSet.java
  zap/src/test/java/org/zaproxy/zap/model/TechSetUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/TechUnitTest.java
Labels: Type-Task

#8135 Guard against param panels' errors during init
  zap/src/main/java/org/parosproxy/paros/view/AbstractParamContainerPanel.java
Labels: enhancement, Component-UI, Usability

#8139 Tidy up JavaDoc and use more `List` in HttpBody
  zap/src/main/java/org/parosproxy/paros/network/HttpBody.java
Labels: Type-Task

#8143 Stop adding API key param to API calls in Python
  zap/src/main/java/org/zaproxy/zap/extension/api/PythonAPIGenerator.java
Labels: Type-Task

#8142 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#8136 Keep Import Menu Items Sorted Alphabetically
  zap/src/main/java/org/parosproxy/paros/view/MainMenuBar.java
  zap/src/main/java/org/zaproxy/zap/view/ZapSortedMenu.java
Labels: enhancement, Component-UI, Usability

#8154 Docker: Add ZAP client profile
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
  docker/firefox/1337hack.zap-client-profile/firefox-extension-preferences.json
  docker/firefox/profiles.ini
Labels: Type-Task, Docker

#8149 sonar workflow: Switch to Java 17
  .github/workflows/sonar.yml
Labels: Type-Task

#8156 Use newer Toolkit API in ViewDelegate
  zap/src/main/java/org/parosproxy/paros/extension/ViewDelegate.java
Labels: Type-Task
