Repository zaproxy/zaproxy, pull requests merged in 2023-04, with the labels that each got.

#7814 Prevent exception when uninstalling add-on's help
  zap/src/main/java/org/zaproxy/zap/extension/help/ExtensionHelp.java
Labels: bug, Component-UI

#7813 Do not remove add-ons from installation dir
  zap/src/main/java/org/zaproxy/zap/control/AddOnLoader.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnLoaderUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnTestUtils.java
Labels: Type-Task

#7822 Reserve Verification Detection scan rule ID
  docs/scanners.md
Labels: Type-Task

#7824 Update FlatLaf and RSyntaxTextArea
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#7831 Add initial authentication integration tests
  docker/integration_tests/af_plan_tests.sh
  docker/integration_tests/configs/plans/auth-json-bearer-cookie.yaml
  docker/integration_tests/configs/plans/auth-json-bearer.yaml
  docker/integration_tests/configs/plans/auth-non-std-json-bearer.yaml
  docker/integration_tests/configs/plans/auth-simple-json.yaml
Labels: Type-Task

#7828 Fix JavaDoc issues
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/main/java/org/parosproxy/paros/network/ConnectionParam.java
  zap/src/main/java/org/zaproxy/zap/ZapGetMethod.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanParam.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/ExtensionSpider.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/SpiderScan.java
  zap/src/main/java/org/zaproxy/zap/spider/Spider.java
Labels: Type-Task

#7840 Reserve ID for alerts raised by the GraphQL Add-on
  docs/scanners.md
Labels: Type-Task

#7843 Deprecate `Proxy`/`ProxyServer` related methods
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/main/java/org/zaproxy/zap/extension/proxies/ExtensionProxies.java
Labels: enhancement

#7844 Retain add-on's mandatory state
  zap/src/main/java/org/parosproxy/paros/control/Control.java
  zap/src/main/java/org/zaproxy/zap/control/AddOnCollection.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnCollectionUnitTest.java
Labels: bug
