Repository zaproxy/zaproxy, pull requests merged in 2023-07, with the labels that each got.

#7931 Update version for 2.13.0
  zap/src/main/java/org/parosproxy/paros/Constant.java
Labels: Type-Task

#7930 Update dependencies
  LEGALNOTICE.md
  zap/src/main/java/org/zaproxy/zap/ZAP.java
  zap/zap.gradle.kts
Labels: Type-Task

#7748 fixed ascan category summaries not updated
  zap/src/main/java/org/zaproxy/zap/extension/ascan/PolicyAllCategoryPanel.java
Labels: Type-Task

#7933 Search auth messages
  zap/src/main/java/org/zaproxy/zap/extension/search/SearchThread.java
Labels: enhancement

#7936 Update content-length in auth template scripts
  zap/src/main/dist/scripts/templates/authentication/Authentication default template.js
  zap/src/main/dist/scripts/templates/authentication/BodgeIt Store Authentication.js
  zap/src/main/dist/scripts/templates/authentication/Simple Form-Based Authentication.js
  zap/src/main/dist/scripts/templates/authentication/Wordpress Authentication.js
Labels: bug, Component-Scripts

#7937 Deprecate Active Scan option Delay When Scanning
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/HostProcess.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Plugin.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/ScannerParam.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ExtensionActiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/OptionsScannerPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/parosproxy/paros/core/scanner/AbstractPluginUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/HostProcessUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/PluginTestUtils.java
Labels: enhancement

#7855 Remove CFU checks in Docker scripts
  docker/CHANGELOG.md
  docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js
  docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
Labels: Type-Task, Docker

#7938 Allow to read enum values with `AbstractParam`
  zap/src/main/java/org/parosproxy/paros/common/AbstractParam.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanParam.java
  zap/src/test/java/org/parosproxy/paros/common/AbstractParamUnitTest.java
Labels: enhancement

#7925 Main add-ons: Add authhelper and update the rest
  zap/src/main/main-add-ons.yml
Labels: Type-Task

#7944 Include other required add-ons in Core package
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
Labels: Type-Task

#7942 Update release checklist
  RELEASING.md
Labels: Type-Task

#7951 Validate API parameter names
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiElement.java
  zap/src/test/java/org/zaproxy/zap/extension/api/ApiElementUnitTest.java
Labels: enhancement

#7953 Update baseline integration test results
  docker/integration_tests/results/baseline1-1.out
  docker/integration_tests/results/baseline2-1.out
  docker/integration_tests/results/baseline3-1.out
  docker/integration_tests/results/baseline3-2.out
  docker/integration_tests/results/baseline4-1.out
Labels: Type-Task

#7963 Update `SECURITY.md` when preparing release
  RELEASING.md
  buildSrc/src/main/java/org/zaproxy/zap/tasks/PrepareMainRelease.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
Labels: Type-Task

#7968 Workaround sonar issue
  .github/workflows/sonar.yml
  build.gradle.kts
Labels: Type-Task

#7966 Define the core add-ons in `main-add-ons.yml`
  buildSrc/src/main/java/org/zaproxy/zap/tasks/internal/MainAddOn.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  zap/src/main/main-add-ons.yml
Labels: Type-Task
