Repository zaproxy/zaproxy, pull requests merged in 2023-02, with the labels that each got.

#7701 Add nearest match handling to Jump To History functionality
  zap/src/main/java/org/parosproxy/paros/extension/history/ExtensionHistory.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuJumpTo.java
Labels: Type-Task

#7708 Use Title Caps in Installer
  zap/src/main/installer/resources/Messages.properties
Labels: Type-Task

#7721 Add application/hal+json to expected API types
  docker/CHANGELOG.md
  docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
Labels: Type-Task

#7726 Fix integration tests
  docker/integration_tests/baseline_tests.sh
  docker/integration_tests/results/baseline1-1.out
  docker/integration_tests/results/baseline2-1.out
  docker/integration_tests/results/baseline3-1.out
  docker/integration_tests/results/baseline4-1.out
Labels: Type-Task

#7727 docker: Skip building the bare image for `linux/arm64`
  .github/workflows/release-main-docker.yml
Labels: Type-Task, Docker

#7720 Add Java 19 to CI and update Gradle
  .github/workflows/ci.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/installers.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  zap/gradle/debian-package.gradle
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyServer.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/PluginFactory.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiImplementor.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  zap/src/main/java/org/zaproxy/zap/extension/callback/ui/CallbackTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/callback/ui/DefaultCustomColumnHistoryReferencesTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptAPI.java
  zap/src/main/java/org/zaproxy/zap/utils/LocaleUtils.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantCookieUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantHeaderUnitTest.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantURLPathUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/ascan/filters/impl/GenericFilterUtilityTest.java
  zap/src/test/java/org/zaproxy/zap/model/VulnerabilitiesLoaderUnitTest.java
  zap/src/test/java/org/zaproxy/zap/network/HttpBodyTestUtils.java
  zap/src/test/java/org/zaproxy/zap/utils/LocaleUtilsUnitTest.java
  zap/src/test/java/org/zaproxy/zap/utils/MessagesLocaleUnitTest.java
  zap/src/test/java/org/zaproxy/zap/utils/TimeStampLocaleUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#7722 CFU Title Caps & scanner/scan rule standardization
  zap/src/main/installer/resources/Messages.properties
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/parosproxy/paros/core/scanner/HostProcessUnitTest.java
Labels: Type-Task

#7749 Remove extraneous chars from SQL queries
  zap/src/main/dist/db/hsqldb.properties
  zap/src/main/dist/db/mysql.properties
Labels: bug

#7536 Set/remove the Content-Type when mutating the method
  zap/src/main/java/org/parosproxy/paros/network/HttpMessage.java
  zap/src/test/java/org/parosproxy/paros/network/HttpMessageUnitTest.java
Labels: Type-Task

#7728 Tooltip Title Caps
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7750 Correct - Consistently prompt when deleting history/sites items
  zap/src/main/java/org/parosproxy/paros/extension/history/ExtensionHistory.java
  zap/src/main/java/org/parosproxy/paros/view/SiteMapPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuPurgeSites.java
Labels: bug, Component-UI

#7401 Add option to choose the icon size
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsParamView.java
  zap/src/main/java/org/parosproxy/paros/extension/option/OptionsViewPanel.java
  zap/src/main/java/org/zaproxy/zap/utils/DisplayUtils.java
  zap/src/main/java/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7758 Add task to generate .NET ZAP API endpoints
  zap/zap.gradle.kts
Labels: Type-Task

#7693 Add Clear button to History tab
  zap/src/main/java/org/parosproxy/paros/extension/history/LogPanel.java
  zap/src/main/java/org/zaproxy/zap/view/table/HistoryReferencesTable.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: enhancement, Component-UI
