Repository zaproxy/zaproxy, pull requests merged in 2023-06, with the labels that each got.

#7886 Include whole `org.zaproxy` package in log config
  zap/src/main/resources/org/zaproxy/zap/resources/log4j2-home.properties
Labels: enhancement

#7897 Push Docker images to GHCR
  .github/workflows/release-live-docker.yml
  .github/workflows/release-main-docker.yml
  .github/workflows/release-weekly-docker.yml
  .github/workflows/run-integration-tests.yml
  docker/CHANGELOG.md
  docker/Dockerfile-tests
Labels: Type-Task, Docker

#7899 Update Docker release workflows
  .github/workflows/release-live-docker.yml
  .github/workflows/release-main-docker.yml
  .github/workflows/release-weekly-docker.yml
  .github/workflows/run-integration-tests.yml
Labels: Type-Task, Docker

#7900 Fix Docker integration tests workflow
  .github/workflows/run-integration-tests.yml
Labels: Type-Task, Docker

#7901 Update Docker release workflows
  .github/workflows/release-live-docker.yml
  .github/workflows/release-main-docker.yml
  .github/workflows/release-weekly-docker.yml
  .github/workflows/run-integration-tests.yml
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task, Docker

#7902 Fix Dockerfiles
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task, Docker

#7887 Show alert ref in the Alert panel
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertViewPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: enhancement, Component-UI, Usability

#7906 Update gradle-launch4j plugin
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/installers.gradle.kts
  zap/zap.gradle.kts
Labels: Type-Task

#7918 Use Adoptium for Java download in the executable
  buildSrc/src/main/kotlin/org/zaproxy/zap/installers.gradle.kts
Labels: enhancement, OpSys-Windows

#7888 Deprecate Global Exclude URLs
  zap/src/main/java/org/parosproxy/paros/model/OptionsParam.java
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/zaproxy/zap/control/CoreFunctionality.java
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/DialogAddToken.java
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/DialogModifyToken.java
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/ExtensionGlobalExcludeURL.java
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/GlobalExcludeURLParam.java
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/GlobalExcludeURLParamToken.java
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/OptionsGlobalExcludeURLPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/globalexcludeurl/OptionsGlobalExcludeURLTableModel.java
Labels: enhancement

#7927 2.13.0: Update macOS details
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  zap/src/main/macOS/OWASP ZAP.app/Contents/Info.plist
Labels: Type-Task
