Repository zaproxy/zaproxy, pull requests merged in 2023-08, with the labels that each got.

#7970 Update readme
  README.md
Labels: Type-Task

#7971 Update POM of zap artifact
  buildSrc/src/main/kotlin/org/zaproxy/zap/publish.gradle.kts
Labels: Type-Task

#7972 Update RSyntaxTextArea
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#7973 Publish Docker images to SSP DockerHub organization
  .github/workflows/release-live-docker.yml
  .github/workflows/release-main-docker.yml
  .github/workflows/release-weekly-docker.yml
  docker/CHANGELOG.md
Labels: Type-Task, Docker

#7977 Remove my authorship JavaDoc
  zap/src/main/java/org/zaproxy/zap/utils/TimeStampUtils.java
Labels: Type-Task

#7978 Remove Java 11 requirement for `buildSrc`
  buildSrc/build.gradle.kts
Labels: Type-Task

#7979 Update Crowdin links
  CONTRIBUTING.md
Labels: Type-Task

#7982 Update docs and image used in packaged scans
  CONTRIBUTING.md
  RELEASING.md
  docker/CHANGELOG.md
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
  zap/src/main/dist/README
  zap/src/main/dist/README.weekly
Labels: Type-Task, Docker

#7985 Fix release of macOS dist in CI
  .github/workflows/release-main-version.yml
  buildSrc/src/main/java/org/zaproxy/zap/tasks/UploadAssetsGitHubRelease.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
Labels: Type-Task

#7986 Update snap info
  snap/snapcraft.yaml
Labels: Type-Task

#7988 Use short name for home dir in Windows
  zap/src/main/dist/zap.bat
  zap/src/main/java/org/parosproxy/paros/Constant.java
Labels: Type-Task

#7987 Update labels, readme, and program name
  zap/src/main/dist/README
  zap/src/main/dist/README.weekly
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/zap.gradle.kts
Labels: Type-Task

#7989 Update Webswing data
  docker/webswing.config
  docker/zap-webswing.sh
Labels: Type-Task

#7990 Remove superseded doc template
  docs/templates/release_tracker.md
Labels: Type-Task

#7992 Update more names in docs and snap shortcut
  CONTRIBUTING.md
  LEGALNOTICE.md
  RELEASING.md
  snap/snap/gui/zaproxy.desktop
Labels: Type-Task

#7984 Allow to display script without focusing
  zap/gradle/japicmp.yaml
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptUI.java
Labels: enhancement, Component-UI

#7996 Update installers and Windows executable
  buildSrc/src/main/kotlin/org/zaproxy/zap/installers.gradle.kts
  python/scripts/generic-pytest/test_zap.py
  zap/src/main/dist/README
  zap/src/main/installer/zap.install4j
Labels: Type-Task

#7997 Use newer Python ZAP API client
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
  docker/zap-api-scan.py
  docker/zap-baseline.py
  docker/zap-full-scan.py
  docker/zap_common.py
Labels: Type-Task

#7981 Update macOS dist
  RELEASING.md
  buildSrc/src/main/java/org/zaproxy/zap/tasks/CreateDmg.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  zap/src/main/macOS/ZAP.app/Contents/Info.plist
  zap/src/main/macOS/ZAP.app/Contents/MacOS/ZAP.sh
  zap/src/main/macOS/ZAP.app/Contents/PkgInfo
Labels: Type-Task

#7991 Remove build of deb package
  BUILDING.md
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/github-releases.gradle.kts
  zap/gradle/debian-package.gradle
  zap/src/main/debian/owasp-zap.desktop
  zap/src/main/debian/zap
  zap/src/main/debian/zapicon.png
Labels: Type-Task

#8003 Use newer Python ZAP API client
  docker/requirements.txt
  docker/zap_common.py
Labels: Type-Task, Docker

#8006 Remove singleton usage in Docker scripts
  docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js
  docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
Labels: Type-Task, Docker

#8002 API Support file transfer
  zap/src/main/java/org/parosproxy/paros/network/HttpHeader.java
  zap/src/main/java/org/zaproxy/zap/extension/api/API.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/api/OptionsApiPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/api/OptionsParamApi.java
  zap/src/main/java/org/zaproxy/zap/extension/api/WebUI.java
  zap/src/main/java/org/zaproxy/zap/model/SessionStructure.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/api/APIUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/CoreAPIUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/api/OptionsParamApiUnitTest.java
Labels: Type-Task

#8009 Fix appends in last PR
  zap/src/main/java/org/zaproxy/zap/extension/api/WebUI.java
Labels: Type-Task

#8013 Use add-on class loader for interface from script
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: bug, Component-Scripts

#8023 workflows: Adjust packaged scans python version matrix
  .github/workflows/test-packaged-scans.yml
  docker/CHANGELOG.md
Labels: Type-Task, Docker

#8028 Set the view to `ExtensionAdaptor` sooner
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionAdaptor.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/main/java/org/zaproxy/zap/extension/help/ExtensionHelp.java
  zap/src/main/java/org/zaproxy/zap/extension/uiutils/ExtensionUiUtils.java
  zap/src/test/java/org/parosproxy/paros/extension/ExtensionLoaderUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/uiutils/ExtensionUiUtilsUnitTest.java
Labels: bug, Component-UI

#8032 Update paths in config after renaming ZAP home
  zap/src/main/java/org/parosproxy/paros/Constant.java
Labels: Type-Task

#8033 Add/use Log4j JUL adapter
  LEGALNOTICE.md
  zap/src/main/java/org/zaproxy/zap/ZAP.java
  zap/zap.gradle.kts
Labels: enhancement

#8030 Update Docker changelog
  docker/CHANGELOG.md
Labels: Type-Task, Docker

#8036 Correct overridden method in `AddOnLoader`
  zap/src/main/java/org/zaproxy/zap/control/AddOnClassLoader.java
  zap/src/main/java/org/zaproxy/zap/control/AddOnLoader.java
Labels: Type-Task

#8015 Remove vulnerability data and deprecate code
  zap/gradle/crowdin.yml
  zap/src/main/dist/lang/vulnerabilities_ar_SA.xml
  zap/src/main/dist/lang/vulnerabilities_az_AZ.xml
  zap/src/main/dist/lang/vulnerabilities_bn_BD.xml
  zap/src/main/dist/lang/vulnerabilities_bs_BA.xml
  zap/src/main/dist/lang/vulnerabilities_ceb_PH.xml
  zap/src/main/dist/lang/vulnerabilities_da_DK.xml
  zap/src/main/dist/lang/vulnerabilities_de_DE.xml
  zap/src/main/dist/lang/vulnerabilities_el_GR.xml
  zap/src/main/dist/lang/vulnerabilities_es_ES.xml
  zap/src/main/dist/lang/vulnerabilities_fa_IR.xml
  zap/src/main/dist/lang/vulnerabilities_fil_PH.xml
  zap/src/main/dist/lang/vulnerabilities_fr_FR.xml
  zap/src/main/dist/lang/vulnerabilities_ha_HG.xml
  zap/src/main/dist/lang/vulnerabilities_he_IL.xml
  zap/src/main/dist/lang/vulnerabilities_hi_IN.xml
  zap/src/main/dist/lang/vulnerabilities_hr_HR.xml
  zap/src/main/dist/lang/vulnerabilities_hu_HU.xml
  zap/src/main/dist/lang/vulnerabilities_id_ID.xml
  zap/src/main/dist/lang/vulnerabilities_it_IT.xml
  zap/src/main/dist/lang/vulnerabilities_ja_JP.xml
  zap/src/main/dist/lang/vulnerabilities_ko_KR.xml
  zap/src/main/dist/lang/vulnerabilities_mk_MK.xml
  zap/src/main/dist/lang/vulnerabilities_ms_MY.xml
  zap/src/main/dist/lang/vulnerabilities_nb_NO.xml
  zap/src/main/dist/lang/vulnerabilities_nl_NL.xml
  zap/src/main/dist/lang/vulnerabilities_pcm_NG.xml
  zap/src/main/dist/lang/vulnerabilities_pl_PL.xml
  zap/src/main/dist/lang/vulnerabilities_pt_BR.xml
  zap/src/main/dist/lang/vulnerabilities_pt_PT.xml
  zap/src/main/dist/lang/vulnerabilities_ro_RO.xml
  zap/src/main/dist/lang/vulnerabilities_ru_RU.xml
  zap/src/main/dist/lang/vulnerabilities_si_LK.xml
  zap/src/main/dist/lang/vulnerabilities_sk_SK.xml
  zap/src/main/dist/lang/vulnerabilities_sl_SI.xml
  zap/src/main/dist/lang/vulnerabilities_sq_AL.xml
  zap/src/main/dist/lang/vulnerabilities_sr_CS.xml
  zap/src/main/dist/lang/vulnerabilities_sr_SP.xml
  zap/src/main/dist/lang/vulnerabilities_tr_TR.xml
  zap/src/main/dist/lang/vulnerabilities_ur_PK.xml
  zap/src/main/dist/lang/vulnerabilities_vi_VN.xml
  zap/src/main/dist/lang/vulnerabilities_yo_NG.xml
  zap/src/main/dist/lang/vulnerabilities_zh_CN.xml
  zap/src/main/dist/lang/vulnerabilities_zh_TW.xml
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertViewPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/lang/LangImporter.java
  zap/src/main/java/org/zaproxy/zap/model/Vulnerabilities.java
  zap/src/main/java/org/zaproxy/zap/model/VulnerabilitiesLoader.java
  zap/src/main/java/org/zaproxy/zap/model/Vulnerability.java
  zap/src/main/resources/org/zaproxy/zap/resources/vulnerabilities.xml
  zap/src/test/java/org/zaproxy/zap/extension/lang/LangImporterUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/ValidateTranslatedVulnerabilitiesFilesUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/VulnerabilitiesLoaderUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#8017 Do not remove headers when proxying
  zap/src/main/java/org/parosproxy/paros/extension/history/ProxyListenerLog.java
  zap/src/test/java/org/parosproxy/paros/extension/history/ProxyListenerLogUnitTest.java
Labels: Type-Task

#8040 Add prompt text to search input fields
  zap/src/main/java/org/parosproxy/paros/view/AbstractParamContainerPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/search/SearchPanel.java
  zap/src/main/java/org/zaproxy/zap/utils/ZapTextField.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#8042 Find: use focus owner
  zap/src/main/java/org/parosproxy/paros/extension/edit/ExtensionEdit.java
Labels: enhancement, Component-UI, Usability
