Repository zaproxy/zaproxy, pull requests merged in 2023-12, with the labels that each got.

#8230 Docker: better parse error
  docker/CHANGELOG.md
  docker/zap_common.py
Labels: Type-Task, Docker

#8236 Update Gradle to 8.5
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/crowdin-upload-files.yml
  .github/workflows/handle-release.yml
  .github/workflows/prepare-release-main-version.yml
  .github/workflows/release-live-docker.yml
  .github/workflows/release-main-docker.yml
  .github/workflows/release-main-version.yml
  .github/workflows/release-snap.yml
  .github/workflows/release-weekly-docker.yml
  .github/workflows/release-weekly.yml
  .github/workflows/run-integration-tests.yml
  .github/workflows/sonar.yml
  .github/workflows/test-packaged-scans.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/installers.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  settings.gradle.kts
  zap/zap.gradle.kts
Labels: Type-Task

#8246 Update Webswing
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
  docker/zap-webswing.sh
Labels: Type-Task

#8248 Include cores and max memory in Support Info
  zap/src/main/java/org/zaproxy/zap/utils/ZapSupportUtils.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: enhancement

#8252 Use name of enum as default value for configs
  zap/src/main/java/org/parosproxy/paros/common/AbstractParam.java
  zap/src/test/java/org/parosproxy/paros/common/AbstractParamUnitTest.java
Labels: bug

#8270 Allow to add custom field with a vertical weight
  zap/src/main/java/org/zaproxy/zap/view/StandardFieldsDialog.java
Labels: Type-Task

#8265 Deprecate Script Scan Rules and related classes
  zap/gradle/japicmp.yaml
  zap/src/main/java/org/parosproxy/paros/core/scanner/PluginFactory.java
  zap/src/main/java/org/zaproxy/zap/control/CoreFunctionality.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScript.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScript2.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ScriptsActiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScript.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScanner.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/PluginFactoryUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/ascan/ScriptsActiveScannerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/ScriptsPassiveScannerUnitTest.java
Labels: enhancement

#8274 Improve logs related to loading of pscanrules
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScannerList.java
Labels: enhancement
