Repository zaproxy/zaproxy, pull requests merged in 2023-03, with the labels that each got.

#7769 Remove duplicate Message properties
  zap/src/main/java/org/zaproxy/zap/control/AddOnRunIssuesUtils.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: bug

#7770 Remove add-on `ResourceBundle` on soft uninstall
  zap/src/main/java/org/zaproxy/zap/control/AddOnInstaller.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnInstallerUnitTest.java
Labels: Type-Task

#7774 Unload dependent extensions on soft uninstall
  zap/src/main/java/org/zaproxy/zap/control/AddOnLoader.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnLoaderUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#7791 Prevent Toolkit init when updating without view
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
Labels: Type-Task

#7792 Remove comments in main resource messages
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#7796 Clarify SQLi scan rules which focus on timing based injections
  docs/scanners.md
Labels: Type-Task

#7763 Modify NodeJS API client generator to support axios library and drop callbacks
  zap/src/main/java/org/zaproxy/zap/extension/api/NodeJSAPIGenerator.java
Labels: Type-Task

#7801 Override `host` in `VariantHeader`
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantHeader.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantHeaderUnitTest.java
Labels: Type-Task

#7804 Ensure passive scan runs even with high traffic
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanController.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScanControllerUnitTest.java
Labels: bug

#7805 Update timing assertion
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScanControllerUnitTest.java
Labels: Type-Task

#7806 Deprecate CFU HTTP sender initiator
  zap/src/main/dist/scripts/templates/httpsender/HttpSender default template.js
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/Downloader.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java
  zap/src/main/java/org/zaproxy/zap/extension/forceduser/ExtensionForcedUser.java
  zap/src/main/java/org/zaproxy/zap/extension/httpsessions/ExtensionHttpSessions.java
  zap/src/test/java/org/zaproxy/zap/extension/autoupdate/DownloadManagerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/autoupdate/DownloaderUnitTest.java
  zap/src/test/java/org/zaproxy/zap/testutils/TestHttpSender.java
Labels: enhancement
