Repository zaproxy/zaproxy, pull requests merged in 2023-11, with the labels that each got.

#8162 Add stat for uncaught exceptions
  zap/src/main/java/org/zaproxy/zap/ZAP.java
  zap/src/test/java/org/zaproxy/zap/ZAPUnitTest.java
Labels: enhancement

#8159 Reserve id for DNS Active Scanner
  docs/scanners.md
Labels: Type-Task

#8165 Small Title Caps Fix-View Toolbar
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#8164 workflow: Adjust PR Labeler, skip if already labeled
  .github/workflows/pr-labeler.yml
Labels: Type-Task

#8168 Set `uploadFile` as a POST endpoint
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiElement.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiOther.java
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/api/PythonAPIGenerator.java
  zap/src/test/java/org/zaproxy/zap/extension/api/ApiElementUnitTest.java
Labels: Type-Task

#8150 Increase search border highlights
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/HighlighterUtils.java
  zap/src/main/java/org/zaproxy/zap/view/panelsearch/items/TreeNodeElementSearch.java
Labels: enhancement, Component-UI

#8171 Fix rendering of Physical fonts
  zap/src/main/java/org/zaproxy/zap/utils/FontUtils.java
Labels: Type-Task

#8147 Multipart Form Params - Extract boundary from body if not in header
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantMultipartFormParameters.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantMultipartFormParametersUnitTest.java
Labels: bug

#8182 Fix zap.sh for macOS
  zap/src/main/dist/zap.sh
Labels: bug

#8183 Reserve Client pscan IDs
  docs/scanners.md
Labels: Type-Task

#8184 Replace usage of Commons Lang v2
  buildSrc/src/main/java/org/zaproxy/gradle/spotless/ValidateImports.java
  zap/src/main/java/ch/csnc/extension/httpclient/PKCS11Configuration.java
  zap/src/main/java/org/apache/commons/httpclient/HttpMethodBase.java
  zap/src/main/java/org/parosproxy/paros/control/MenuFileControl.java
  zap/src/main/java/org/parosproxy/paros/core/proxy/ProxyThread.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/Analyser.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantAbstractQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantDirectWebRemotingQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantJSONQuery.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantMultipartFormParameters.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantURLPath.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantXMLQuery.java
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableHistory.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
  zap/src/main/java/org/parosproxy/paros/extension/manualrequest/ManualRequestEditorDialog.java
  zap/src/main/java/org/parosproxy/paros/network/HttpBody.java
  zap/src/main/java/org/parosproxy/paros/network/HttpMessage.java
  zap/src/main/java/org/parosproxy/paros/view/OutputPanel.java
  zap/src/main/java/org/zaproxy/zap/GuiBootstrap.java
  zap/src/main/java/org/zaproxy/zap/Version.java
  zap/src/main/java/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/control/AddOn.java
  zap/src/main/java/org/zaproxy/zap/control/AddOnInstaller.java
  zap/src/main/java/org/zaproxy/zap/control/AddOnRunIssuesUtils.java
  zap/src/main/java/org/zaproxy/zap/db/sql/DbSQL.java
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  zap/src/main/java/org/zaproxy/zap/extension/api/API.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiException.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiResponseConversionUtils.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiResponseElement.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiResponseList.java
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiResponseSet.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/AddOnWrapper.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/AddOnsTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/AutoUpdateAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/brk/impl/http/HttpBreakpointMessage.java
  zap/src/main/java/org/zaproxy/zap/extension/custompages/DialogAddCustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuExportSelectedURLs.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/request/RequestByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/impl/models/http/response/ResponseByteHttpPanelViewModel.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/StatsPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/spider/ExtensionSpider.java
  zap/src/main/java/org/zaproxy/zap/extension/stats/ExtensionStats.java
  zap/src/main/java/org/zaproxy/zap/extension/users/UsersAPI.java
  zap/src/main/java/org/zaproxy/zap/model/VulnerabilitiesLoader.java
  zap/src/main/java/org/zaproxy/zap/session/ScriptBasedSessionManagementMethodType.java
  zap/src/main/java/org/zaproxy/zap/spider/SpiderTask.java
  zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderODataAtomParser.java
  zap/src/main/java/org/zaproxy/zap/utils/ClassLoaderUtil.java
  zap/src/main/java/org/zaproxy/zap/utils/HarUtils.java
  zap/src/main/java/org/zaproxy/zap/utils/ZapSupportUtils.java
  zap/src/main/java/org/zaproxy/zap/view/ZapTable.java
  zap/src/main/java/org/zaproxy/zap/view/widgets/UsersListModel.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantAbstractQueryUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRFUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/script/ScriptVarsUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#8185 Registering Full Path Disclosure Scan ID
  docs/scanners.md
Labels: Type-Task

#8180 Drop "to Clipboard" from ZAP copy menu items
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#8166 scripts: Synchronize contents and file methods
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptWrapper.java
Labels: bug

#8188 Allow to hook param panels with parents
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionHookView.java
  zap/src/main/java/org/parosproxy/paros/extension/ExtensionLoader.java
Labels: enhancement

#8198 URL Path Input Vector - attack end path too
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantURLPath.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantURLPathUnitTest.java
Labels: enhancement

#8199 Use HTTP method in Java API client generator
  zap/src/main/java/org/zaproxy/zap/extension/api/JavaAPIGenerator.java
Labels: Type-Task

#8200 Actions: allow weekly to release without the tests
  .github/workflows/release-weekly.yml
Labels: Type-Task

#8201 Allow to build weekly with normal output
  .github/workflows/release-weekly.yml
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
Labels: Type-Task

#8206 Use HTTP method in NodeJs API client generator
  zap/src/main/java/org/zaproxy/zap/extension/api/NodeJSAPIGenerator.java
Labels: Type-Task

#8203 Option to encode cookie values
  zap/src/main/java/org/parosproxy/paros/core/scanner/ScannerParam.java
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantCookie.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/OptionsVariantPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/VariantFactory.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantCookieUnitTest.java
Labels: enhancement

#8210 Warn of root user usage and include core count and max memory on start up
  zap/src/main/java/org/zaproxy/zap/ZapBootstrap.java
Labels: enhancement

#8190 alert: Add CWE Alert Tag when building and CWE ID has been set
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AlertUnitTest.java
Labels: enhancement

#8213 Remove dependency on `git` to build the weekly
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
Labels: Type-Task

#8218 Added JWT in Browser Storage
  docs/scanners.md
Labels: Type-Task

#8216 chore: Update Dependencies
  LEGALNOTICE.md
  build.gradle.kts
  buildSrc/src/main/kotlin/org/zaproxy/zap/jflex.gradle.kts
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.java
  zap/zap.gradle.kts
Labels: Type-Task
