Repository zaproxy/zaproxy, pull requests merged in 2023-09, with the labels that each got.

#8053 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#8055 Include country name for duplicated languages
  zap/src/main/java/org/zaproxy/zap/utils/LocaleUtils.java
  zap/src/test/java/org/zaproxy/zap/utils/LocaleUtilsUnitTest.java
Labels: bug, Component-UI, Usability

#8050 Allow to select a script node without focusing
  zap/gradle/japicmp.yaml
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptUI.java
Labels: enhancement, Component-UI

#8054 Add API to delete alerts within a context and update 'alerts' view API to allow filtering by context
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertAPI.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#8063 Add labeler workflow
  .github/workflows/conf/pr-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: Type-Task

#8061 AlertAPI: Address SAST (sonarlint) items
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertAPI.java
Labels: Type-Task

#8073 scripts: Persist enable state automatically
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptParam.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptWrapper.java
  zap/src/test/java/org/zaproxy/zap/extension/script/ExtensionScriptUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/script/ScriptParamUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/script/ScriptWrapperUnitTest.java
Labels: Type-Task

#8080 Add postman to the weekly release
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#8081 Register scan rule ID for SameOrigin Method Execution
  docs/scanners.md
Labels: Type-Task

#8083 Wrap message panel's header components
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/HttpPanel.java
Labels: Type-Task

#8089 Break: Allow host header manipulation
  zap/src/main/java/org/zaproxy/zap/extension/brk/BreakPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/resources/resource/icon/fugue/server.png
Labels: enhancement

#8090 Remove missed vulnerabilities file
  zap/src/main/dist/lang/vulnerabilities_uk_UA.xml
Labels: Type-Task
