Repository zaproxy/zaproxy, pull requests merged in 2024-12, with the labels that each got.

#8744 Deprecate/disable core passive scanner
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/AntiCsrfDetectScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveController.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanActions.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanController.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanData.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTask.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTaskHelper.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanThread.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PluginPassiveScannerUnitTest.java
Labels: Type-Task

#8749 Update JRE for MacOS
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
Labels: Type-Task

#8751 Update dependencies
  LEGALNOTICE.md
  zap/src/main/java/org/parosproxy/paros/core/scanner/Analyser.java
  zap/src/test/java/org/zaproxy/zap/utils/PausableScheduledThreadPoolExecutorUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#8752 Make HarLib an implementation dependency
  zap/zap.gradle.kts
Labels: enhancement

#8753 Deprecate `HarUtils`
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/search/SearchAPI.java
  zap/src/main/java/org/zaproxy/zap/utils/HarUtils.java
Labels: enhancement

#8747 Pin non-GitHub actions with full sha in workflows
  .github/workflows/ci.yml
  .github/workflows/cla.yml
  .github/workflows/lock.yml
  .github/workflows/release-live-docker.yml
  .github/workflows/release-main-docker.yml
  .github/workflows/release-snap.yml
  .github/workflows/release-weekly-docker.yml
  .github/workflows/run-integration-tests.yml
Labels: Type-Task

#8755 2.16 Update version
  zap/src/main/java/org/parosproxy/paros/Constant.java
Labels: Type-Task

#8754 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#8756 Tweak JavaDoc packages
  zap/zap.gradle.kts
Labels: Type-Task

#8757 Docker: Update webswing to 24.2.2
  docker/CHANGELOG.md
  docker/Dockerfile-live
  docker/Dockerfile-weekly
Labels: Type-Task

#8763 Deprecate context menu method no longer needed
  zap/src/main/java/org/zaproxy/zap/view/popup/PopupMenuItemContextInclude.java
Labels: enhancement

#8766 Update RSyntaxTextArea
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#8768 Include more info when logging DB max size limits
  zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableHistory.java
  zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableHistory.java
Labels: enhancement

#8759 Use always latest request sent if same status
  zap/src/main/java/org/parosproxy/paros/model/SiteMap.java
Labels: enhancement

#8771 Fix OverlayIcon scaling
  zap/src/main/java/org/zaproxy/zap/utils/DisplayUtils.java
  zap/src/main/java/org/zaproxy/zap/view/OverlayIcon.java
Labels: bug

#8773 Add missing scaling to some icons
  zap/src/main/java/org/parosproxy/paros/view/AbstractParamContainerPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertPanel.java
  zap/src/main/java/org/zaproxy/zap/utils/TableExportAction.java
Labels: bug, Component-UI

#8770 Fix contractions of it is in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Type-Task

#8774 Add constants for Client Spider
  zap/src/main/java/org/parosproxy/paros/model/HistoryReference.java
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/parosproxy/paros/network/HttpSender.java
  zap/src/main/java/org/zaproxy/zap/extension/compare/ExtensionCompare.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/search/SearchThread.java
Labels: enhancement

#8775 Weekly: add client
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#8779 Add temp history ID for Client Spider
  zap/src/main/java/org/parosproxy/paros/model/HistoryReference.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/ExtensionAlert.java
Labels: Type-Task

#8778 Support swapping output panel implementation
  zap/src/main/java/org/parosproxy/paros/extension/ViewDelegate.java
  zap/src/main/java/org/parosproxy/paros/view/OutputPanel.java
  zap/src/main/java/org/parosproxy/paros/view/View.java
  zap/src/main/java/org/zaproxy/zap/view/OutputSource.java
Labels: enhancement, Component-UI
