Repository zaproxy/zaproxy, pull requests merged in 2024-08, with the labels that each got.

#8585 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#8589 Correct label in a Structural Modifier dialogue
  zap/src/main/java/org/zaproxy/zap/view/ContextStructurePanel.java
Labels: bug, Component-UI

#8590 Correct `StructuralNodeModifier` key check
  zap/src/main/java/org/zaproxy/zap/model/StructuralNodeModifier.java
  zap/src/test/java/org/zaproxy/zap/model/StructuralNodeModifierUnitTest.java
Labels: bug

#8601 Update CLA Assistant
  .github/workflows/cla.yml
Labels: Type-Task

#8602 Make some dialog messages copyable.
  zap/src/main/java/org/parosproxy/paros/view/View.java
Labels: enhancement, Component-UI, Usability

#8612 Bump Docker image for Weekly and use Java 17
  docker/CHANGELOG.md
  docker/Dockerfile-weekly
Labels: Type-Task, Docker

#8614 Update `dependabot` username in CLA workflow
  .github/workflows/cla.yml
Labels: Type-Task

#8615 Remove "Nashorn" JavaScript templates
  zap/src/main/dist/scripts/templates/active/Active default template.js
  zap/src/main/dist/scripts/templates/authentication/Authentication default template.js
  zap/src/main/dist/scripts/templates/authentication/BodgeIt Store Authentication.js
  zap/src/main/dist/scripts/templates/authentication/Simple Form-Based Authentication.js
  zap/src/main/dist/scripts/templates/authentication/Wordpress Authentication.js
  zap/src/main/dist/scripts/templates/httpsender/AddZapHeader.js
  zap/src/main/dist/scripts/templates/httpsender/HttpSender default template.js
  zap/src/main/dist/scripts/templates/passive/Passive default template.js
  zap/src/main/dist/scripts/templates/proxy/Proxy default template.js
  zap/src/main/dist/scripts/templates/session/Juice Shop Session Management.js
  zap/src/main/dist/scripts/templates/session/Session Management default template.js
  zap/src/main/dist/scripts/templates/standalone/Loop through history table.js
  zap/src/main/dist/scripts/templates/standalone/Standalone default template.js
  zap/src/main/dist/scripts/templates/standalone/Traverse sites tree.js
  zap/src/main/dist/scripts/templates/targeted/Find HTML comments.js
  zap/src/main/dist/scripts/templates/targeted/Targeted default template.js
  zap/src/main/dist/scripts/templates/variant/Input Vector default template.js
  zap/src/main/dist/scripts/templates/variant/Site modifying JSON example.js
  zap/src/test/java/org/zaproxy/zap/VerifyScriptTemplates.java
Labels: enhancement

#8617 Update the API Minimal policy
  docker/CHANGELOG.md
  docker/policies/API-Minimal.policy
Labels: Type-Task, Docker
