Repository zaproxy/zaproxy, pull requests merged in 2024-01, with the labels that each got.

#8276 Remove hardcoded sizes in Add Note dialog
  zap/src/main/java/org/zaproxy/zap/extension/history/NotesAddDialog.java
Labels: Type-Task

#8283 Anti-CSRF Handling should always account for partial matching
  zap/src/main/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRF.java
  zap/src/test/java/org/zaproxy/zap/extension/anticsrf/ExtensionAntiCSRFUnitTest.java
Labels: enhancement

#8293 Fix itest typo
  docker/integration_tests/configs/plans/auth-json-bearer-js-cookie.yaml
Labels: Type-Task

#8296 ITests: Add diags for new-json plan
  docker/integration_tests/configs/plans/auth-password-new-json.yaml
Labels: Type-Task

#8298 Prevent NPE if no user creds
  zap/src/main/java/org/zaproxy/zap/users/User.java
  zap/src/test/java/org/zaproxy/zap/users/UserUnitTest.java
Labels: bug

#8304 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#8305 Allow to skip unwrap in Python API generator
  zap/src/main/java/org/zaproxy/zap/extension/api/PythonAPIGenerator.java
Labels: Type-Task

#8295 Allow setting the log level via a CLI argument
  zap/src/main/java/org/parosproxy/paros/CommandLine.java
  zap/src/main/java/org/zaproxy/zap/ZapBootstrap.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: enhancement

#8318 Update CodeQL workflow to use v3 actions
  .github/workflows/codeql.yml
Labels: Type-Task

#8313 Feat: Support URL input for hostname override (issue #8312)
  docker/CHANGELOG.md
  docker/zap-api-scan.py
Labels: Type-Task, Docker

#8317 ZAP CLA v1.0
  .github/workflows/cla.yml
  CLA.md
  CONTRIBUTING.md
Labels: Type-Task

#8323 CLA action: add workflow_call
  .github/workflows/cla.yml
Labels: Type-Task

#8325 CLA action: add secrets
  .github/workflows/cla.yml
Labels: Type-Task

#8326 CLA action: removed GITHUB_TOKEN
  .github/workflows/cla.yml
Labels: Type-Task

#8324 Add Java 21 to CI
  .github/workflows/ci.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/zaproxy/zap/tasks/HandleWeeklyRelease.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/SendRepositoryDispatch.java
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/zaproxy/zap/ZAP.java
  zap/src/main/java/org/zaproxy/zap/control/AddOn.java
  zap/src/main/java/org/zaproxy/zap/control/AddOnCollection.java
  zap/src/main/java/org/zaproxy/zap/extension/help/ZapTocView.java
  zap/src/main/java/org/zaproxy/zap/utils/ByteBuilder.java
  zap/src/test/java/org/parosproxy/paros/CommandLineUnitTest.java
  zap/src/test/java/org/zaproxy/zap/ZAPUnitTest.java
  zap/src/test/java/org/zaproxy/zap/control/AddOnUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/autoupdate/DownloadManagerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/autoupdate/DownloaderUnitTest.java
  zap/zap.gradle.kts
Labels: Type-Task

#8302 Fix context inclusion issues
  zap/src/main/java/org/parosproxy/paros/model/Session.java
  zap/src/main/java/org/parosproxy/paros/model/SiteMap.java
  zap/src/main/java/org/parosproxy/paros/model/SiteNode.java
  zap/src/main/java/org/zaproxy/zap/model/Context.java
  zap/src/test/java/org/parosproxy/paros/model/SessionUnitTest.java
  zap/src/test/java/org/parosproxy/paros/model/SiteMapUnitTest.java
  zap/src/test/java/org/zaproxy/zap/model/ContextUnitTest.java
Labels: bug
