Repository zaproxy/zaproxy, pull requests merged in 2024-09, with the labels that each got.

#8630 Adjusted L&F button text
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#8623 Fix typos in comments and log messages
  zap/src/main/java/org/zaproxy/zap/extension/custompages/DefaultCustomPage.java
  zap/src/main/java/org/zaproxy/zap/extension/help/ExtensionHelp.java
  zap/src/main/java/org/zaproxy/zap/users/User.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantODataUnitTest.java
Labels: Type-Task

#8632 Fix EDT access on script node changes
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: bug

#8628 Change some messages to title caps
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#8321 Update zap.sh script to get memory usage in containers
  docker/CHANGELOG.md
  docker/Dockerfile-bare
  zap/src/main/dist/zap.sh
Labels: enhancement

#8547 Allow moving tabs to new windows
  zap/src/main/java/org/parosproxy/paros/view/AbstractFrame.java
  zap/src/main/java/org/parosproxy/paros/view/MainFrame.java
  zap/src/main/java/org/parosproxy/paros/view/WorkbenchPanel.java
  zap/src/main/java/org/zaproxy/zap/view/TabbedPanel2.java
  zap/src/main/java/org/zaproxy/zap/view/TabbedPanelTab.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/main/resources/resource/icon/fugue/ui-tab-exclamation.png
Labels: enhancement, Component-UI

#8641 Add names to columns in Manage Add-ons Dialogue
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/InstalledAddOnsTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/autoupdate/UninstalledAddOnsTableModel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#8648 Rebrand
  CONTRIBUTING.md
  README.md
Labels: Type-Task

#8654 Update cla workflow to 2.6.1
  .github/workflows/cla.yml
Labels: Type-Task

#8655 Issue templates and picker minor grammar tweaks
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/third-party-addon.yml
Labels: Type-Task
