Repository zaproxy/zaproxy, pull requests merged in 2024-05, with the labels that each got.

#8469 Fix NPE in `AbstractAppParamPlugin`
  zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractAppParamPlugin.java
Labels: bug, weekly

#8472 Address JavaDoc error
  zap/src/main/flex/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.flex
  zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.java
Labels: Type-Task

#8473 Update Gradle Crowdin plugin
  zap/zap.gradle.kts
Labels: Type-Task

#8470 CoreAPI: Add logging handling
  zap/src/main/java/org/zaproxy/zap/extension/api/CoreAPI.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
  zap/src/test/java/org/zaproxy/zap/extension/api/CoreAPIUnitTest.java
Labels: Type-Task

#8476 Prepare next dev iteration
  zap/gradle.properties
  zap/gradle/japicmp.yaml
Labels: Type-Task

#8478 Update Log4j 2
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#8480 Correct annotations in main Docker images
  .github/workflows/release-main-docker.yml
Labels: Type-Task, Docker

#8481 Update actions in GitHub workflows
  .github/workflows/lock.yml
  .github/workflows/run-integration-tests.yml
Labels: Type-Task

#8494 Docker: Rename test image
  .github/workflows/run-integration-tests.yml
Labels: Type-Task

#8493 Grpc: gRPC-web-text constant added in NameValuePair
  zap/src/main/java/org/parosproxy/paros/core/scanner/NameValuePair.java
Labels: Type-Task

#8490 Deprecate and disable script API
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiGeneratorUtils.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
  zap/src/main/java/org/zaproxy/zap/extension/script/ScriptAPI.java
Labels: Type-Task

#8495 Skip unwrap of automation progress
  zap/src/main/java/org/zaproxy/zap/extension/api/PythonAPIGenerator.java
Labels: Type-Task

#8496 Fix exceptions for no/empty path in path variant
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantURLPath.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/VariantURLPathUnitTest.java
Labels: bug

#8498 Do not use null domain in auth credentials
  zap/src/main/java/org/zaproxy/zap/authentication/HttpAuthenticationMethodType.java
Labels: bug
