Repository zaproxy/zaproxy, pull requests merged in 2024-11, with the labels that each got.

#8701 branding & support related adjustments
  zap/src/main/java/org/parosproxy/paros/Constant.java
  zap/src/main/java/org/zaproxy/zap/view/AboutDialog.java
  zap/src/main/java/org/zaproxy/zap/view/AboutPanel.java
  zap/src/main/java/org/zaproxy/zap/view/SplashScreen.java
  zap/src/main/resources/resource/zap-banner-square.png
  zap/src/main/resources/resource/zap-by-checkmarx.png
Labels: Type-Task

#8704 Add scanpolicies add-on to weekly
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#8034 Deprecate `ValueGenerator`
  zap/src/main/java/org/zaproxy/zap/extension/spider/ExtensionSpider.java
  zap/src/main/java/org/zaproxy/zap/model/DefaultValueGenerator.java
  zap/src/main/java/org/zaproxy/zap/model/ValueGenerator.java
  zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlFormParser.java
  zap/src/test/java/org/zaproxy/zap/spider/SpiderControllerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/spider/parser/SpiderHtmlFormParserUnitTest.java
Labels: Type-Task

#8685 Add manual alert add/modify and vuln selection stats
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertAddDialog.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertViewPanel.java
Labels: enhancement

#8707 Fix exception when printing null to error stream
  zap/src/main/java/org/zaproxy/zap/ZAP.java
Labels: bug

#8709 Deprecate unused passive scan methods
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
Labels: Type-Task

#8708 Itests: add sequence tests
  docker/integration_tests/configs/plans/data/seq-simple.har
  docker/integration_tests/configs/plans/seq-ascan-fail.yaml
  docker/integration_tests/configs/plans/seq-simple.yaml
Labels: Type-Task

#8710 Itests - remove zap-cli check
  docker/integration_tests/python_tests.sh
Labels: Type-Task

#8711 Deprecate/remove passive scan related options
  zap/src/main/java/org/zaproxy/zap/extension/pscan/DialogAddAutoTagScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/DialogModifyAutoTagScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/OptionsPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/OptionsPassiveScanTableModel.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanController.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanParam.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanRuleManager.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTask.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTaskHelper.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScannerList.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScannerOptionsPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PluginPassiveScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PolicyPassiveScanPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/RegexAutoTagScanner.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScanControllerUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScanParamUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/PassiveScannerListUnitTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/DefaultRegexAutoTagScannerTest.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/RegexAutoTagScannerUnitTest.java
Labels: Type-Task

#8734 Log ID of the active scans
  zap/src/main/java/org/parosproxy/paros/core/scanner/Scanner.java
Labels: enhancement

#8742 Allow setting exit code to zero
  zap/src/main/java/org/parosproxy/paros/control/Control.java
Labels: Type-Task
