Repository zaproxy/zaproxy, pull requests merged in 2024-07, with the labels that each got.

#8539 Integration tests fix - extra test
  docker/integration_tests/results/baseline1-1.out
  docker/integration_tests/results/baseline2-1.out
  docker/integration_tests/results/baseline3-1.out
  docker/integration_tests/results/baseline3-2.out
  docker/integration_tests/results/baseline4-1.out
Labels: Type-Task

#8532 Deprecate and disable pscan API
  zap/src/main/java/org/zaproxy/zap/extension/api/ApiGeneratorUtils.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanAPI.java
  zap/src/main/weekly-add-ons.json
Labels: Type-Task

#8541 Remove stats passive scan rule
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/StatsPassiveScanner.java
  zap/src/test/java/org/zaproxy/zap/extension/pscan/scanner/StatsPassiveScannerUnitTest.java
Labels: Type-Task

#8540 Stop un/loading add-on passive scan rules
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
Labels: Type-Task

#8544 Remove passive scan status label
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanController.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#8546 Prevent adding same add-on's `ResourceBundle`
  zap/src/main/java/org/zaproxy/zap/control/ExtensionFactory.java
Labels: bug

#8545 Add plugin ID for Tech Detection alert functionality
  docs/scanners.md
Labels: Type-Task

#8549 Disable and deprecate `ExtensionLog4j`
  zap/src/main/java/org/zaproxy/zap/control/CoreFunctionality.java
  zap/src/main/java/org/zaproxy/zap/extension/ascan/AttackModeScanner.java
  zap/src/main/java/org/zaproxy/zap/extension/log4j/ExtensionLog4j.java
  zap/src/test/java/org/zaproxy/zap/extension/log4j/ExtensionLog4jUnitTest.java
Labels: Type-Task

#8551 Remove Passive Rules script type
  zap/src/main/java/org/zaproxy/zap/extension/pscan/ExtensionPassiveScan.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#8212 Bump Nightly Docker image to Debian Bookworm and use Java 17
  docker/CHANGELOG.md
  docker/Dockerfile-live
Labels: Type-Task

#8555 Update RSyntaxTextArea
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#8557 Update engine name in integration tests
  docker/integration_tests/configs/plans/contexts/session-script.context
Labels: Type-Task

#8559 Fallback to Graal.js in the API packaged scan
  docker/CHANGELOG.md
  docker/zap-api-scan.py
Labels: Type-Task, Docker

#8560 Do not warn when Nashorn not found
  zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java
Labels: Type-Task

#8564 Update FlatLaf
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task

#8565 Address warnings when building Docker images
  docker/Dockerfile-bare
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task, Docker

#8566 Fix auth type isTypeForMethod implementations
  zap/src/main/java/org/zaproxy/zap/authentication/FormBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/HttpAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/JsonBasedAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/ManualAuthenticationMethodType.java
  zap/src/main/java/org/zaproxy/zap/authentication/ScriptBasedAuthenticationMethodType.java
Labels: Type-Task

#8568 ITests: ajax spider browser based auth
  docker/integration_tests/configs/plans/auth-ajax-simple.yaml
Labels: Type-Task

#8536 Add the possibility to search into notes
  zap/src/main/java/org/zaproxy/zap/extension/search/ExtensionSearch.java
  zap/src/main/java/org/zaproxy/zap/extension/search/SearchAPI.java
  zap/src/main/java/org/zaproxy/zap/extension/search/SearchPanel.java
  zap/src/main/java/org/zaproxy/zap/extension/search/SearchThread.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: Type-Task

#8571 ITests: continue on error
  .github/workflows/run-integration-tests.yml
Labels: Type-Task

#8572 Itests: Check for errors on auto update
  .github/workflows/check-zap-errors.yml
  .github/workflows/conf/af-check-errors.yml
Labels: Type-Task

#8573 Itests: fix error check image
  .github/workflows/check-zap-errors.yml
Labels: Type-Task

#8574 Itests: fix error check dir path
  .github/workflows/check-zap-errors.yml
Labels: Type-Task

#8575 Itests: fix error check plan name
  .github/workflows/check-zap-errors.yml
Labels: Type-Task

#8576 Itests: fix check error - needed checkout
  .github/workflows/check-zap-errors.yml
Labels: Type-Task

#8578 Itest: error check - perform a real scan
  .github/workflows/check-zap-errors.yml
  .github/workflows/conf/af-check-errors.yml
Labels: Type-Task

#8579 Action: error check, run vs nightly too
  .github/workflows/check-zap-errors.yml
Labels: Type-Task

#8580 ITests: conditional diagnostics
  docker/integration_tests/configs/plans/auth-ajax-simple.yaml
  docker/integration_tests/configs/plans/auth-json-bearer-cookie.yaml
  docker/integration_tests/configs/plans/auth-json-bearer-js-cookie.yaml
  docker/integration_tests/configs/plans/auth-json-bearer.yaml
  docker/integration_tests/configs/plans/auth-non-std-json-bearer.yaml
  docker/integration_tests/configs/plans/auth-password-added-json.yaml
  docker/integration_tests/configs/plans/auth-password-hidden-json.yaml
  docker/integration_tests/configs/plans/auth-password-new-json.yaml
  docker/integration_tests/configs/plans/auth-simple-json.yaml
  docker/integration_tests/configs/plans/jigsaw-basic-user.yaml
  docker/integration_tests/configs/plans/petstore-openapi.yaml
  docker/integration_tests/configs/plans/testfire-form-user.yaml
  docker/integration_tests/configs/scripts/standalone/af-diags.js
Labels: Type-Task

#8581 Itests: continueOnFailure
  docker/integration_tests/configs/plans/auth-ajax-simple.yaml
  docker/integration_tests/configs/plans/auth-json-bearer-cookie.yaml
  docker/integration_tests/configs/plans/auth-json-bearer-js-cookie.yaml
  docker/integration_tests/configs/plans/auth-json-bearer.yaml
  docker/integration_tests/configs/plans/auth-non-std-json-bearer.yaml
  docker/integration_tests/configs/plans/auth-password-added-json.yaml
  docker/integration_tests/configs/plans/auth-password-hidden-json.yaml
  docker/integration_tests/configs/plans/auth-password-new-json.yaml
  docker/integration_tests/configs/plans/auth-simple-json.yaml
  docker/integration_tests/configs/plans/jigsaw-basic-user.yaml
  docker/integration_tests/configs/plans/petstore-openapi.yaml
  docker/integration_tests/configs/plans/testfire-form-user.yaml
Labels: Type-Task

#8583 Update dependencies
  LEGALNOTICE.md
  zap/zap.gradle.kts
Labels: Type-Task
