Repository zaproxy/zaproxy, pull requests merged in 2025-02, with the labels that each got.

#8841 Add URL to RPC warning
  zap/src/main/java/org/parosproxy/paros/core/scanner/VariantAbstractRPCQuery.java
Labels: Type-Task

#8852 Update ubuntu in test packages scans action
  .github/workflows/test-packaged-scans.yml
Labels: Type-Task

#8860 Docker: add jq to the right images
  docker/Dockerfile-live
  docker/Dockerfile-stable
  docker/Dockerfile-weekly
Labels: Type-Task

#8862 Fix alert editing through the GUI
  zap/src/main/java/org/parosproxy/paros/core/scanner/Alert.java
  zap/src/main/java/org/zaproxy/zap/extension/alert/AlertViewPanel.java
  zap/src/test/java/org/parosproxy/paros/core/scanner/AlertUnitTest.java
Labels: bug

#8867 Update Java version in start script automatically
  buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts
  zap/src/main/dist/zap.sh
  zap/zap.gradle.kts
Labels: Type-Task

#8868 Adjust Footer Status Icons Label
  zap/src/main/java/org/parosproxy/paros/view/MainFooterPanel.java
  zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties
Labels: enhancement, Component-UI

#8871 Update Gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/zaproxy/zap/tasks/CreateDmg.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/GradleBuildWithGitRepos.java
  buildSrc/src/main/java/org/zaproxy/zap/tasks/JFlexGenerator.java
  buildSrc/src/main/kotlin/org/zaproxy/zap/japicmp/AcceptMethodAbstractNowDefaultRule.kt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  zap/zap.gradle.kts
Labels: Type-Task

#8872 Tag verification requests
  zap/src/main/java/org/zaproxy/zap/authentication/AuthenticationHelper.java
  zap/src/main/java/org/zaproxy/zap/authentication/AuthenticationMethod.java
Labels: enhancement
