Repository zaproxy/zaproxy, pull requests merged in 2025-07, with the labels that each got.

#8992 Allow to copy rule config fields
  zap/src/main/java/org/zaproxy/zap/extension/ruleconfig/DialogEditRuleConfig.java
Labels: enhancement, Component-UI

#8999 Itests: update for new (passing) pscan rule
  docker/integration_tests/results/baseline1-1.out
  docker/integration_tests/results/baseline1-2.out
  docker/integration_tests/results/baseline2-1.out
  docker/integration_tests/results/baseline3-1.out
  docker/integration_tests/results/baseline4-1.out
Labels: Type-Task

#9014 Reserve scan rule ID 100043
  docs/scanners.md
Labels: Type-Task

#9015 Do not warn on charset aliases
  zap/src/main/java/org/parosproxy/paros/network/HttpMessage.java
  zap/src/test/java/org/parosproxy/paros/network/HttpMessageUnitTest.java
Labels: bug

#9017 Replace full paths in AF itest plans
  docker/integration_tests/configs/plans/auth-ajax-simple.yaml
  docker/integration_tests/configs/plans/auth-client-script-ajax-spider.yaml
  docker/integration_tests/configs/plans/auth-client-script-client-spider.yaml
  docker/integration_tests/configs/plans/auth-client-script-simple-json-blocking-ui-scroll-fields.yaml
  docker/integration_tests/configs/plans/auth-client-script-simple-json-blocking-ui.yaml
  docker/integration_tests/configs/plans/auth-client-simple.yaml
  docker/integration_tests/configs/plans/auth-json-bearer-cookie.yaml
  docker/integration_tests/configs/plans/auth-json-bearer-js-cookie.yaml
  docker/integration_tests/configs/plans/auth-json-bearer.yaml
  docker/integration_tests/configs/plans/auth-json-diff-cookies.yaml
  docker/integration_tests/configs/plans/auth-non-std-json-bearer.yaml
  docker/integration_tests/configs/plans/auth-password-added-json.yaml
  docker/integration_tests/configs/plans/auth-password-hidden-json.yaml
  docker/integration_tests/configs/plans/auth-password-new-json.yaml
  docker/integration_tests/configs/plans/auth-simple-json-shadow-dom.yaml
  docker/integration_tests/configs/plans/auth-simple-json.yaml
  docker/integration_tests/configs/plans/jigsaw-basic-user.yaml
  docker/integration_tests/configs/plans/petstore-openapi.yaml
  docker/integration_tests/configs/plans/seq-simple.yaml
  docker/integration_tests/configs/plans/testfire-form-user.yaml
Labels: Type-Task
