Repository zaproxy/zaproxy, pull requests merged in 2025-01, with the labels that each got.

#8785 Add local address to HTTP request header
  zap/src/main/java/org/parosproxy/paros/network/HttpRequestHeader.java
Labels: enhancement

#8786 Fix ITests (just new valid results)
  docker/integration_tests/results/baseline1-2.out
  docker/integration_tests/results/baseline2-2.out
  docker/integration_tests/results/baseline3-3.out
  docker/integration_tests/results/baseline4-2.out
Labels: Type-Task

#8792 Update base image and Java of main Docker images
  docker/CHANGELOG.md
  docker/Dockerfile-bare
  docker/Dockerfile-stable
Labels: Docker

#8794 Update core dist add-ons
  zap/src/main/main-add-ons.yml
Labels: Type-Task

#8793 Fix snap build
  snap/snapcraft.yaml
Labels: Type-Task

#8801 Fix snap build, round 2
  snap/snapcraft.yaml
Labels: Type-Task

#8802 Fix snap build, round 3
  snap/snapcraft.yaml
Labels: Type-Task

#8803 Update build dependencies
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/zaproxy/zap/tasks/CreatePullRequest.java
Labels: Type-Task

#8805 Stop publishing to `softwaresecurityproject`
  .github/workflows/release-live-docker.yml
  .github/workflows/release-main-docker.yml
  .github/workflows/release-weekly-docker.yml
  docker/CHANGELOG.md
Labels: Type-Task, Docker

#8806 Pin chalk action in live Docker workflow
  .github/workflows/release-live-docker.yml
Labels: Type-Task

#8808 Unpin chalk action in live Docker workflow
  .github/workflows/release-live-docker.yml
Labels: Type-Task

#8809 Pin chalk binary in live Docker workflow
  .github/workflows/release-live-docker.yml
Labels: Type-Task, Docker

#8796 Remove Bugcrowd links
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  RELEASING.md
  SECURITY.md
Labels: Type-Task

#8737 Workflow: Send bluesky message on check failure
  .github/workflows/check-zap-errors.yml
  .github/workflows/release-live-docker.yml
Labels: Type-Task

#8812 Fix bluesky post?
  .github/workflows/check-zap-errors.yml
Labels: Type-Task

#8822 Itests - use zaproxy instead of example
  docker/integration_tests/baseline_tests.sh
  docker/integration_tests/configs/baseline2.conf
  docker/integration_tests/configs/baseline3.conf
  docker/integration_tests/results/baseline1-1.out
  docker/integration_tests/results/baseline1-2.out
  docker/integration_tests/results/baseline2-1.out
  docker/integration_tests/results/baseline2-2.out
  docker/integration_tests/results/baseline3-1.out
  docker/integration_tests/results/baseline3-2.out
  docker/integration_tests/results/baseline3-3.out
  docker/integration_tests/results/baseline4-1.out
  docker/integration_tests/results/baseline4-2.out
Labels: Type-Task

#8824 Itests: New baseline result + bluesky warning
  .github/workflows/run-integration-tests.yml
  docker/integration_tests/results/baseline1-2.out
Labels: Type-Task

#8825 itests: fix conditional?
  .github/workflows/run-integration-tests.yml
Labels: Type-Task

#8833 Fix snap packaging
  snap/snapcraft.yaml
Labels: Type-Task

#8834 ITests: Add Client Script Auth tests for Ajax and Client Spiders
  docker/integration_tests/configs/plans/auth-client-script-ajax-spider.yaml
  docker/integration_tests/configs/plans/auth-client-script-client-spider.yml
  docker/integration_tests/configs/scripts/auth/clientScriptAuth.zst
Labels: Type-Task

#8835 iTests: Fix auth-client-script-ajax-spider and client-spider
  docker/integration_tests/configs/plans/auth-client-script-ajax-spider.yaml
  docker/integration_tests/configs/plans/auth-client-script-client-spider.yaml
Labels: Type-Task

#8836 iTests: Fix script name
  docker/integration_tests/configs/plans/auth-client-script-ajax-spider.yaml
  docker/integration_tests/configs/plans/auth-client-script-client-spider.yaml
Labels: Type-Task

#8837 iTests: Tweak onFail values
  docker/integration_tests/configs/plans/auth-client-script-ajax-spider.yaml
  docker/integration_tests/configs/plans/auth-client-script-client-spider.yaml
Labels: Type-Task
